### ISSUE TITLE
[Backport] [21] Exception on reading MemoryUsage

### ISSUE THREAD

**Issue by gian1200** [oracle/graal#10175]
**Backport request**

**Provide a list of links to PRs or commit SHAs you would like to backport.**
https://github.com/oracle/graal/pull/6930

**List the GraalVM versions you would like to see the changes backported to.**
GraalVM for JDK 21 (Community Edition)

**Describe the motivation for the backport.**
Bug fix on a LTS Java version. Original issue: https://github.com/oracle/graal/issues/6814

**Additional context.**

**Comment by zakkak** [comment]
Hi @roberttoyonaga, could you please provide feedback regarding whether:

1. Backporting #6930 to GraalVM for JDK 21 would be the right thing to do? Are there other patches we should backport along it?
2. Backporting #6930 is considered safe?

**Comment by roberttoyonaga** [comment]
Hi @zakkak 
1. https://github.com/oracle/graal/pull/6930 can be backported alone. It shouldn't need other patches backported along with it. I think backporting this would be the right thing to do as lacking the patch can cause unexpected exceptions to be thrown (as in https://github.com/oracle/graal/issues/6814). **However**, if users are erroneously relying on those max memory pool values, backporting this patch will be a breaking change for them (though they really shouldn't be using that data to begin with since max memory pool values don't actually report the true "max").
2.  Aside from the fact that it will affect those relying on the "max" pool sizes, this should be safe. It's very isolated, and I do not believe any machinery internal to SubstrateVM relies on the "max" pool sizes exposed by the memory pool MXBeans, its only for external monitoring.

**Comment by zakkak** [comment]
Moved to https://github.com/graalvm/graalvm-community-jdk21u/issues/30
