### ISSUE TITLE
Is allowAllAccess still needed for Ruby, R and Python

### ISSUE THREAD

**Issue by ralleman** [oracle/graal#1043]
It's still in the doc, stating:

> Context provides an execution environment for guest languages. Please note that Ruby, R and Python require the allowAllAccess flag to be set to true.

But I found this post https://stackoverflow.com/questions/50027675/graalvm-access-to-native-code-is-not-allowed-by-the-host-environment/50039062 which states that this is not necessary for Python.

Can someone clarify please? If they still require all access, is there a plan to restrict these?

Richard

**Comment by eregon** [comment]
Ruby now boots fine with just `Context.create()` and no additional permissions.
However, functionality will be limited as it cannot make any native call.

@timfel Can you answer for Python?
@lukasstadler Can you answer for R?

We should update the website, indeed.

**Comment by timfel** [comment]
Python Boots without additional permissions. But many things (e.g. regular expressions, distutils, package installation, or even some parts of the math module) need native access through Sulong.

**Comment by lukasstadler** [comment]
R needs native access on startup.
(it can be configured in a mode where it doesn't, but with limited functionality)

The statement on the website is arguably true, since it refers to the specific example.
It is possible to run these languages without native access, but at least IO permissions or a custom filesystem will be necessary, but that's a more complex topic that needs to be explained on its own.

**Comment by ralleman** [comment]
Thanks guys for the answers.
