### ISSUE TITLE
UnresolvedElementException with ByteBuffer.flip()

### ISSUE THREAD

**Issue by dustpuppyNGTI** [oracle/graal#1060]
I'm trying to compile a simple HTTP server with graalvm-ce-1.0.0-rc13. The '--allow-incomplete-classpath' option makes the code compile but also fail during runtime. Is ByteBuffer.flip() supported by Graal? Is there an alternative?

```
[14:53:47] [~/Projects/java-nio-http-server] $ native-image --no-server -jar target/server.jar
[server:28196]    classlist:   1,988.57 ms
[server:28196]        (cap):   1,544.55 ms
[server:28196]        setup:   3,124.12 ms
[server:28196]     analysis:   6,794.63 ms
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: java.nio.ByteBuffer.flip(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: java.nio.ByteBuffer.flip(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing http.HttpServer.processing(HttpServer.java:151)
Call path from entry point to http.HttpServer.processing(AsynchronousSocketChannel): 
        at http.HttpServer.processing(HttpServer.java:144)
        at http.HttpServer.lambda$listening$0(HttpServer.java:129)
        at http.HttpServer$$Lambda$355/1695173164.run(Unknown Source)
        at java.lang.Shutdown.runHooks(Shutdown.java:123)
        at java.lang.Shutdown.sequence(Shutdown.java:167)
        at java.lang.Shutdown.shutdown(Shutdown.java:234)
        at com.oracle.svm.core.jdk.RuntimeSupport.shutdown(RuntimeSupport.java:181)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image building with exit status 1
make: *** [build] Error 1
```

**Comment by cstancu** [comment]
Yes, we should support `java.nio.ByteBuffer.flip()`, however, it looks like it cannot be found on the classpath. Can you provide a reproducible example and/or the output when you run `native-image` with the `--verbose` flag?

Since you are using HTTP you should also read the corresponding [documentation]( 
https://github.com/oracle/graal/blob/master/substratevm/URL-PROTOCOLS.md#url-protocols-on-substrate-vm).

**Comment by dmlloyd** [comment]
This usually indicates that you've compiled on Java 9+, as ByteBuffer has a covariant override for flip() on that version. The fix is typically to do clean rebuild of your classes on JDK 8, or on a later JDK with the `--release=8` option.

**Comment by dustpuppyNGTI** [comment]
I'm quite certain I pointed maven to Java 8, doesn't Graal complain about the version number in the class files when you compile with 9+? It doesn't matter though, I discovered that the Spark Framework compiles flawlessly with Graal so I've thrown out the previous HTTP server.
If anyone else feels like confirming things; the code I was trying to compile is this: https://github.com/jccarrillo/java-nio-http-server. Feel free to close the issue.

**Comment by dmlloyd** [comment]
> I'm quite certain I pointed maven to Java 8, doesn't Graal complain about the version number in the class files when you compile with 9+?

It's not a Graal problem at all, it's just that SubstrateVM is *noticing* the problem because of the aggressive/complete way that it analyzes the class path.

JDKs allow you to compile to old bytecode versions without restricting the class path to the corresponding JDK version.  So for example you'll get this particular covariance problem if you include *any* artifact that includes a reference to `flip` which was compiled with JDK 9 or later (plus `-source 8 -target 8`).  That's what the `--release` switch is for: it says not only that you want to build Java 8 class files, but you also want to only compile against what a JDK 8 would have available.

**Comment by cstancu** [comment]
@dmlloyd thanks for your input!

**Comment by dustpuppyNGTI** [comment]
@dmlloyd got it. I rechecked the project and maven had both target and source set to 8 and JAVA_HOME was pointing to a JDK 8 installation it still had the original error. This configuration however fixed the error:
```
    <properties>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.release>8</maven.compiler.release>
    </properties>
```
target and source cannot be removed or maven won't compile, and the release setting is necessary to fix the classpath issue. The code now compiles and runs :)
