### ISSUE TITLE
Running NodeJS scripts from Java programs

### ISSUE THREAD

**Issue by janostgren** [oracle/graal#1222]
Is it possible to run NodeJS JavaScript from Java programs using PolyGlot API.
I need to use require() and await async etcetera.
The use case is to manage Puppeteer script from Graal VM.

**Comment by fniephaus** [comment]
It's not officially supported, but have a look at [NodeJVM](https://github.com/mikehearn/nodejvm/).

**Comment by ralleman** [comment]
Related: https://github.com/graalvm/graaljs/issues/50

**Comment by wirthi** [comment]
Hi,

Since GraalVM 20.0.0, we have [experimental support for common.js require()](https://github.com/graalvm/graaljs/blob/master/docs/user/NodeJSVSJavaScriptContext.md#experimental-support-for-commonjs-npm-modules-in-the-context-api). This way, you can interop from Java to JavaScript (via the `Context` API) and use npm modules there. You cannot use the Node.js event loop, though, and for some internal packages you have to use replacements (similar to what tools like Browserify would do). See the documentation linked above for more details.

Another option is to start in a `node`  application and then interop into Java. You have to take care around multithreading, but in general, this is possible. See [our Blogpost on Multigthreaded Java-JavaScript interoperability](https://medium.com/graalvm/multi-threaded-java-javascript-language-interoperability-in-graalvm-2f19c1f9c37b).

Best,
Christian

**Comment by newk5** [comment]
There is also another project that implemented this behaviour successfully. I'd suggest checking out [javet](https://github.com/caoccao/Javet), it allows you to embed a full node.js runtime and you can use node.js features from java and java features from node.
