### ISSUE TITLE
PRNG should be seeded from /dev/urandom, not /dev/random

### ISSUE THREAD

**Issue by lvh** [oracle/graal#1293]
When installing GraalVM 19.0.0., `jre/lib/security/java.security` has the following line:

```
securerandom.source=file:/dev/random
```

This should be `/dev/urandom`. There's a lot of fearmongering around "/dev/urandom is actually unsafe sometimes" that is unwarranted. Lots of OSes already patch this out; for example, if I install OpenJDK11 on Fedora, I already get /dev/urandom. The Linux manpage has caused tons of damage (in real actual vulns) over the years here, but fortunately now admits that the API is archaic and bad:

> The  /dev/random  device  is a legacy interface which dates back to a time where the cryptographic primitives used in the implementation of /dev/urandom were not widely trusted.

The good line is:

```
securerandom.source=file:/dev/urandom
```

**Comment by dougxc** [comment]
The best thing to do here is to submit this as an [OpenJDK RFE](https://bugs.openjdk.java.net). There are many factors to consider for such a change ranging from backwards compatibility to different behavior on various OS distributions. Since Graal is a drop-in JDK replacement, we'd prefer not to deviate from the default config. That said, the default config can be changed easily enough by anyone as a post-GraalVM installation step.
