### ISSUE TITLE
Scala classes not working for graal.js

### ISSUE THREAD

**Issue by gzoller** [oracle/graal#1319]
I made a discovery that graal.js doesn't support Scala classes.  They *should* be the same as Java classes, but apparently not.

Here's my test jig:

Java class:
```java
public class Record {
    public int x = 42;
    public double y = 42.0;
    public String name() {
        return "foo";
    }
}
```

Scala code:
```scala
class Record2() {
  val x: Int = 42
  def name() = "foo"
}
class Record3() {
  val x: Value = toGraalValue(42)
  def name() = "foo"
}

object Parseme extends App {

  val engine = new ScriptEngineManager().getEngineByName("graal.js")
  val bindings = engine.createBindings()
  bindings.put("polyglot.js.allowAllAccess", true)
  engine.setBindings(bindings, ScriptContext.ENGINE_SCOPE)

  val fnName = "foo"
  engine.eval(s"""var $fnName = function(a){ return "Hi, " + a.x + " : "+a.name(); }""")

  val inv = engine.asInstanceOf[Invocable]

  import model.JSHelper._
  val r = new co.blocke.Record() // Hi, 42 : foo  <-- Java class works!
  val r2 = new Record2() // Hi, foreign {} : foo  <-- Scala data member not accessible
  val r3 = new Record3() // Hi, foreign {} : foo  <-- Scala data member not accessible
  val stuff = List(r)

  println(inv.invokeFunction(fnName, stuff: _*))
}
```

As you can see, passing the pure Java class, methods & members are both accessible from Javascript.  When passing Scala objects I can call methods, but can't access the data members.

**Comment by mukel** [comment]
Scala var/vals are translated to a private field + accessors. The js interop can only access public members, so you have to use the public accessors to read/write the field (val/var).
You can see how it looks from Java using `javap` (I changed x to `var` to see the setter):
```
javap -p -cp target/scala-2.12/classes Record2
Compiled from "Parseme.scala"
public class Record2 {
  private int x;
  public int x();
  public void x_$eq(int);
  public java.lang.String name();
  public Record();
}
```
This works:
```scala
engine.eval(s"""var $fnName = function(a){
  a.x_$$eq(123);
  return "Hi, " + a.x() + " : "+a.name();
}""")
```

**Comment by gzoller** [comment]
Thank you for this explanation--makes sense.   In my particular application didn't want any special accommodations (knowledge of the JVM-side language) on the javascript side (I want it to be compatible regardless of the JVM-side code).

I have no idea what terror this means within the Graal ecosystem, but it'd be pretty cool if somehow Graal know 1) Scala was going on, 2) differentiate data members from actual functions/members, and 3) auto-converted (via some kind of proxy?) those data accessors into JS-visible primitives.  4) <Bonus> If it knew how to handle var vs val, so JS could actually mutate the vars, but not the vals.

**Comment by wirthi** [comment]
Hi,

> I have no idea what terror this means within the Graal ecosystem, but it'd be pretty cool if somehow Graal know 1) Scala was going on, 2) differentiate data members from actual functions/members, and 3) auto-converted (via some kind of proxy?) those data accessors into JS-visible primitives. 

The solution for (3) is: wrap the Scala object in a `org.graalvm.polyglot.proxy.ProxyObject` before sending it to JavaScript. Then you can decide what members you want to expose, and how they should look like to all other languages, and what happens when they are written to (or executed, or deleted). [ProxyObject JavaDoc ](https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/proxy/ProxyObject.html)

> 4) If it knew how to handle var vs val, so JS could actually mutate the vars, but not the vals.

JavaScript does not and should not understand the semantics of other languages (like Scala). If we teach all X GraalVM-based languages the semantics of (X-1) other langues, we will have to define `x*(x-1)` mappings. As X is in the ballpark of 10 at the moment (Java, Scala, Kotlin, JavaScript, Ruby, Python, R, LLVM, SOM, ...), this quickly becomes unfeasible.

The way the polyglot interop is designed is that [messages](https://en.wikipedia.org/wiki/Object-oriented_programming#Dynamic_dispatch/message_passing) are sent to the language "owning" an object. This means: when JavaScript writes a value to a Scala object, it sends Scala a `WRITE` message. Scala can then decide what to do (and accept it for `var`s, reject it for `val`s, for instance). This way, JavaScript does not need to know anything about Scala; it does not even need to know what other language it is talking to.

Again, when you combine that with `ProxyObject`s, you can define your own behavior, and e.g. publish the values of `val`s to other languages, but reject the writing to them (throw an error, silently ignore the write, whatever is appropriate).

Best,
Christian
