### ISSUE TITLE
memory leak when using graal.js

### ISSUE THREAD

**Issue by mungco** [oracle/graal#1366]
I am pretty sure that I used the context in a right way(graal.js version is RC10). in my online systems, it seems that the BasicShape object has memory leak. I refered other issues, and just wanna confirm that the RC14 and later version has fixed it?

and I really want to know how the memory leak happens, thanks.

```text
ClassLoader @ 0x500801318"has loaded 9,201,640 instances of Class "com.oracle.truffle.object.basic.ShapeBasic". occupied 6,334,303,976 (67.18%)bytes
```

**Comment by dougxc** [comment]
Hi @mungco , does this still occur on GraalVM 19.0? If so, can you please provide a reproducer for further investigation.

**Comment by wirthi** [comment]
Hi @mungco 

thanks for your report. As Doug mentioned, we fixed at least two memory leaks in Graal.js since RC10, that could have caused that behavior. Please try with the latest version (GraalVM 19).

If that does not help, can you provide (relevant parts of) your code, or a heap dump, so we can investigate?

Thanks,
Christian
