### ISSUE TITLE
What errors would it catch?

### ISSUE THREAD

**Issue by douglas-schwingel** [oracle/graal#1399]
What errors/exceptions would Graal catch that the JIT compiler wouldn't? e.g.: Bad casting

**Comment by dougxc** [comment]
I’m not sure what you mean since Graal is a JIT compiler. If you mean bad casts in Graal’s implementation, then Graal will normally catch these and bail out of the compilation, allowing the VM to continue executing.

**Comment by douglas-schwingel** [comment]
Using the Native Image, Graal is able to compile the code Ahead-of-Time, right? I was told recently that AOT compilers can identify some problems that a normal JIT compiler wouldn't be able to, making them good not just for a faster startup time but also for being able to see those problems.

If so, what would those errors be?

**Comment by dougxc** [comment]
The native-image tool in GraalVM runs some of the application's code during AOT compilation (in particular, [some class initializers](https://github.com/oracle/graal/blob/master/substratevm/CLASS-INITIALIZATION.md#explicitly-specifying-class-initialization)). If errors occur during those initializers, you will see them at AOT time. Otherwise, native-image should compile all other code to behave as it on a normal JVM (modulo the [documented limitations](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md)).

**Comment by dougxc** [comment]
@douglas-schwingel please close this issue unless you have further questions.
