### ISSUE TITLE
[Truffle] Efficient Host Interaction?

### ISSUE THREAD

**Issue by mattkendall** [oracle/graal#1436]
Hello! I'm having a lot of fun building a prototype of a simple scripting language using Truffle. The library is really amazing. Today I've run into a snag and my suspicion is that I'm thinking about the problem the wrong way or using the wrong tools.

In my prior (bytecode generation based) implementation of this language, instances of language objects were routinely created outside the scripting environment itself. Helper libraries, e.g. JSON decoding, would create instances of objects and pass them into user defined scripting.

With Truffle, I've tried to follow the same path by evaluating a `Source` that returns an executable `Value` representing the user defined script. However, when I try to pass this function an instance of my efficient object representation, it gets wrapped inside a `HostObject`. After some research, I understand that's by design from reading the Embedding Reference guide, so I'd like to understand the "correct" way to do this in Truffle.

I have an existing body of code that's expecting to be able to create language objects and pass them into scripts, what's the most efficient way to bridge that gap? I can get it to work with `ProxyObject`, but then it looks like I'm going to lose many of the in-lining and `@Specialization` features that I want out of Truffle? Is there an interop message or language setting I can change that allows the host to pass through objects without `HostObject` decoration? Or am I thinking about the problem the wrong way?

**Comment by chumer** [comment]
Truffle languages communicate to the outside world and other languages using the Truffle interoperability protocol. We put this abstraction in place to make embedder code portable between multiple languages. We use the same approach when we share values between languages.

In this case the HostObject class is a wrapper to add interoperability semantics to provided Java value to the language. This has the advantage that the language implementation does not need to know where the object comes from, in this case that it is a Java object. It may come from the host application, or from another guest language, or even a tool.

So instead of unboxing the HostObject I suggest you use the `InteropLibrary` to invoke messages on that external Java object [1, 2].

In order to invoke a method on an object it would look like this:
{code}
 abstract static class InvokeMethod  extends Node {
    
     abstract Object execute(Object obj, String methodName, Object[] arguments);

     @Specialization(guards = "objLibrary.hasMembers(array)", limit = "4")
     int doDefault(Object obj, String methodName, Object[] arguments,
                     @CachedLibrary("obj") InteropLibrary objLibrary) {
         try {
             return objLibrary.invokeMember(methodName, arguments);
         } catch (InteropException e) {
               // TODO translate errors to your language errors
         }
     }
 }
{code}

The good thing about this is that you automatically support objects coming from any other language as well.

[1] https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/library/CachedLibrary.html
[2] https://www.graalvm.org/truffle/javadoc/index.html?com/oracle/truffle/api/interop/InteropLibrary.html

**Comment by mattkendall** [comment]
OK, I see. So that will work, but I'm curious if there's not some way to create a `TruffleObject` in the Host space and pass it to a guest function as an argument? In my language I have static types, so I'd really like to be able to utilize object layouts and remove boxing. If all of my calls are going through library interop code onto a `HostObject`, I won't be able to do those things, correct?

As a concrete example, if I have some sort of REST interface and I basically want to do:

```
LanguageObject input = mapFromJSONToTruffleObject(jsonString);
LanguageObject output = scriptingLangRootNode.call(input);
return mapFromTruffleObjectToJSON(output);
```

It looks like I can partially do this by registering my object types as symbols within the polyglot binding space and then invoking `newInstance` on them from within Host code. That allows me to do things like bind values into my objects from JSON via the `Value` interface. It appears to work, but may be a terrible idea...?

I see the benefit to the polyglot protocol. It'd actually be really cool to be able to pass JavaScript objects and functions into my language and have them interoperate, so I really appreciate what you've built. I'm just trying to figure out the most efficient way to marshal object data into my scripts. The main reason I'm looking at Truffle is to gain access to the JIT-style `@Specialization` stuff, but I'm worried that I won't get any real performance gains if it's slow to marshal/unmarshal objects.

**Comment by chumer** [comment]
You can actually pass a TruffleObject directly from the host. But you won't be able to unbox it later on (e.g. from `Value`). But I'd not recommend this because we typically try to separate the language implementations from the host application using separate class loaders. If you use APIs that are shared between the language and host application you lose portability and make compatibility with harder to manage. You would actually need to disable JVMCI class loading in order to make this work, which we don't recommend besides testing.

Can you pass the JSON string into your language and do the conversion there e.g. by calling a guest function? Java strings are not boxed and directly passed to the language. This way you would avoid the boxing into host object. 

BTW.: I don't think the host object wrapping is very expensive. I also think we have some room to improve performance on our side. I'd recommend measuring with a micro-benchmark to make sure. JMH can be a good tool for that.

**Comment by chumer** [comment]
Forgot to mention. The most efficient host to guest calls you get if you entirely rely on a side-effecting  method and use the `Value.executeVoid` method without arguments. 

For example, you could do something like this with Java side-effects like this:
```
public static class Arguments {
    @Export public int arg0;
    @Export public int arg1;
    @Export public int result;
}

public static void main(String[] args) {
    Context context = Context.create();
    Arguments data = new Arguments();
    context.getBindings("js").putMember("data", data);
    Value jsFunction = context.eval("js", "(function() {data.result = data.arg0 + data.arg1;})");
    context.enter();
    try {
        for (int i = 0; i < 1000; i++) {
            data.arg0 = i;
            data.arg1 = i;
            jsFunction.executeVoid();
            assert data.result == i * 2;
            System.out.println(data.result);
        }
    } finally {
        context.leave();
    }
}
```
That is the most efficient way to cross the boundary. But make sure you actually need it using a benchmark, as it is less nice to read than just passing arguments to a function.
Explicit enter/leave only makes sense if you actually transition many times between the host/guest. If you only transition once, then don't use the explicit enter/leave.

**Comment by mattkendall** [comment]
Thanks for all the help and input. I'll play around with these things and likely be back with other questions :).

**Comment by 0c3d7r4** [comment]
@chumer so you say "Truffle languages communicate to the outside world and other languages using the Truffle interoperability protocol." but the way something like Arrays is implemented is the following

```java
public class HostObject implements TruffleObject {
    boolean isList(HostClassCache hostClassCache) {
        return hostClassCache.isListAccess() && obj instanceof List;
    }
}
```
This just means that in the end of the day, there will always be the "common" abstraction language which is _Java_, so what's the point of hiding the actual obj inside the HostObject anyway? Other than security, it's not "interoperability" strictly speaking where a "host" means actual language of another object (maybe it holds for complex object but not _primitives_ like lists).

**Comment by chumer** [comment]
@0c3d7r4 

> This just means that in the end of the day, there will always be the "common" abstraction language which is Java, so what's the point of hiding the actual obj inside the HostObject anyway?

As the name implies, HostObject is the specific implementation of the Truffle interop protocol for Java host objects. These objects are wrapped primarily to strictly decouple the guest language implementation from the host environment.

While the underlying platform may be Java, the guest language (JS, Python, Ruby, etc.) should not need to know that an object originated from Java. It only needs to know that the object respects the common interop protocol which is implemented through HostObject.

Theoretically, we could skip the wrapper, but this would introduce significant drawbacks:

- Ambiguity with Language Implementation: Many Truffle languages are themselves implemented in Java. If a language implementation uses a java.util.HashMap to represent its own internal scope or objects, and we also pass a raw host HashMap to the guest, the runtime cannot easily distinguish between them. The wrapper acts as a marker, ensuring the runtime knows: "This is a foreign object from the host, treat it via HostAccess rules," versus "This is an internal language structure."

- Polyglot Isolates: In scenarios involving Native Image isolates, the host and the guest may run in separate memory heaps. You cannot pass a raw Java reference across these boundaries. A wrapper/handle mechanism is required to marshal calls between the isolated contexts.

- Sandboxing and Security: Wrapping the object allows GraalVM to enforce HostAccess policies. If we exposed the raw Java object, it would be much harder to control which members or methods (like reflection) are visible to the guest language, potentially breaking the sandbox.

- Heap Memory Boundaries: The wrapper establishes a clear boundary between where the "host world" ends and the "guest world" begins. This distinction is vital for enforcing heap memory limits. It allows the runtime to accurately calculate how much memory is being consumed by the guest context specifically, rather than conflating it with the embedding application's memory usage.

I hope this explains our reasoning a little.
Do you have any specific questions?

**Comment by 0c3d7r4** [comment]
@chumer thanks for detailed answer. yes i understand that the interop protocol is required, but my question is about something like byte[] - it's not a list, and it's not an object - as i said, i'm concerned about _primitive_ types and byte array is essentially a primitive type. there's no way for me to know via interop that it's specifically byte array. when i invoke a java method like "".getBytes from js, it enters the js realm as a foreign object, but i can't specialise methods on byte array specifically without looking at the actual type of the host object. so whereas in the js implementation i can do things like
```java
public abstract class JSStringGetBytesNode extends JSStringOperation {
 @Specialization(guards = "isUndefined(charsetArg)")
 protected Object getBytesDefault(TruffleString thisStr, @SuppressWarnings("unused") Object charsetArg,
   @Cached TruffleString.ReadByteNode readByteNode,
   @Cached TruffleString.SwitchEncodingNode switchEncodingNode) {
  return getBytesForEncoding(thisStr, TruffleString.Encoding.UTF_8, readByteNode, switchEncodingNode);
 }

 // Helper method to get bytes for a specific encoding
 private Object getBytesForEncoding(TruffleString str, TruffleString.Encoding encoding,
   TruffleString.ReadByteNode readByteNode,
   TruffleString.SwitchEncodingNode switchEncodingNode) {

  // Convert string to target encoding
  TruffleString encodedStr = switchEncodingNode.execute(str, encoding);
  int byteLength = encodedStr.byteLength(encoding);
  byte[] byteValues = new byte[byteLength];

  for (int i = 0; i < byteLength; i++) {
   byte byteValue = (byte) readByteNode.execute(encodedStr, i, encoding);
   byteValues[i] = byteValue; // Ensure unsigned
  }

  return JSArray.createConstantByteArray(getContext(), getRealm(), byteValues);
 }
}
```
just fine, i can't use the interop protocol to basically do this
```java
protected final Object convertForeignReturn(Object returnValue) {
            if(getRealm().getEnv().isHostObject(returnValue)) {
                var hostObject = getRealm().getEnv().asHostObject(returnValue);
                if(hostObject instanceof byte[] byteArray){
                    return JSArray.createConstantByteArray(getJSContext(), getRealm(), byteArray);
                }
            }
}
```
the above is the hack that accesses the raw host object - and as you said, this potentially isn't safe for isolates and sandboxing. 
So the question is how am i supposed to work with arrays specialised against primitives like `byte[]`. I just think just like truffle string, there needs to be a truffle array so that i can use guards like "isForeignByteArray". 

- Also since there's a method called `asHostObject`, you'll see people using it a lot to work around limitations like this, with potential security implications, so i'm pretty sure the shouldn't even be `asHostObject` public method.
- Also, the doc for `asHostObject` goes: _Returns the java host representation of a Truffle guest object if it represents a Java host language object._ so as i said, there's 2 kinds of foreign objects - the complete "alien" that might come from another language, and a java object (true host object) so i think there's a slight confusion about interop in the first place. any language implementation would still have to use an underlying host (java) model for something like byte arrays, so that abstraction you're talking about can't really exist fully without Java as the common _foundational_ language, again unless you completely mimic all use cases by introducing stuff like _TruffleArray_ etc, which i don't think is happening.

**Comment by chumer** [comment]
> So the question is how am i supposed to work with arrays specialised against primitives like byte[].

Strictly speaking, Truffle Interop does not currently support typed arrays. While we have evaluated several proposals over the last few years, we have not yet moved forward with a standardized implementation. Consequently, the interop protocol does not expose specific type information for arrays.

From the perspective of interop, a byte[] is simply an array of generic numbers that happen to fit within the byte range. Therefore, the only solution to exclusively specialize for a host byte[] effectively is casting to the host type, exactly as you are currently doing.

The core philosophy of interop is not to fully encapsulate the semantics of every language. It is intentionally designed as a "best effort" protocol. When precise language-specific semantics (like Java primitive arrays) are required, we expect users to cast to the specific host type or evaluate a snippet/call in the target language to handle the conversion/behavior.


Some notes on your concerns:

- You can wrap the byte[] in a host ByteBuffer. This makes it an interop buffer, which allows for optimized buffered reads via the interop library: https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/InteropLibrary.java#L1549

- We have recently updated the host interop APIs to strictly follow the interop contract (targeted for release 25.1). You will be able to use InteropLibrary.asHostObject(...), but it will now throw a HeapIsolationException if the heap is isolated. This allows you to handle the failure gracefully rather than risking unsafe access: https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/InteropLibrary.java#L3095

- You can perform a specific type check for byte[] without an host interop cast by using InteropLibrary. You can look up the "byte array" class symbol in the language Env and use InteropLibrary.isMetaInstance(...) to verify if the foreign object is indeed a byte array.

**Comment by 0c3d7r4** [comment]
@chumer 
<ol>
<li> if access to the host object is possible from language implementations via the interop.asHostObject method at any time, does it mean the security sandbox model has a leak and not truly reliable as there's no host access option that allows to disable that at engine level?
<li> is that a security vulnerability - e.g. if somehow the memory in that region gets overridden, the wrong object might get read? is it why you introduce HeapIsolationException  - but only in the next version, so prior to 25.1 it's technically a CVE?
   <blockquote>The memory isolation also gives security guarantees: objects from one isolate (maybe associated with a particular user) cannot be erroneously accessed by another isolate (associated with a different user). Bugs that allow information to leak between users via, e.g., static fields or caches maintained by libraries, are prevented by the isolation.     </blockquote>
<p>^ the above passage from <a href="https://medium.com/graalvm/isolates-and-compressed-references-more-flexible-and-efficient-memory-management-for-graalvm-a044cc50b67e">isolates blogpost</a> illustrates where this could be problematic - if a lang implementation receives direct access to the static but not final field, it would allow it to change a type in such static field eg a list by adding new items. 
<li> would results of AOT-compiled host code still be still available asHostObject in isolates without the error?
</ol>

**Comment by chumer** [comment]
Thanks for the questions.


> if access to the host object is possible from language implementations via the interop.asHostObject method at any time, does it mean the security sandbox model has a leak and not truly reliable as there's no host access option that allows to disable that at engine level?


With our UNTRUSTED sandboxing mode we require heap isolation, so the old and the new API would fail as accesses across heaps are not allowed. The only thing that changes with this new API is that we fail with a more explicit checked exception and not with a runtime error as we did before, giving and inviting the language implementation to handle this case more gracefully.

All accesses across isolated heaps must go through the interop protocol and are carefully vetted for leaks.

Our security sandbox trusts the language implementation. We actively perform security reviews of language implementations that support sandboxing to make sure we do not introduce leaks like that.  So even if it would be allowed to unbox objects from other heaps we would likely capture issues like that in those reviews. It would not be possible to unbox Java objects from other heaps without resorting to unsafe APIs. All our unsafe API usages are required to be security reviewed.


> is that a security vulnerability - e.g. if somehow the memory in that region gets overridden, the wrong object might get read? is it why you introduce HeapIsolationException - but only in the next version, so prior to 25.1 it's technically a CVE?


As mentioned before,  we were already failing before, just not with a checked exception. So not a CVE.


> would results of AOT-compiled host code still be still available asHostObject in isolates without the error?

This issue is not related to whether the host code is AOT compiled. It depends whether the guest context is isolated from the host application. This can happen on HotSpot as well as in AOT compiled code. Both modes behave the same. If no isolation is enabled / the sandbox is disabled host unboxing is supported. We still do not use it extensively in our current language implementations. In fact we were reducing the number of usages and generally we try to use interop instead as naturally those features would otherwise not be supported with sandboxing enabled. 

I hope this makes sense.

**Comment by 0c3d7r4** [comment]
@chumer "Our security sandbox trusts the language implementation" 😂 so if i can prove that through a buggy language implementation i can escape the sandbox and change data on the host, i could get listed on https://www.oracle.com/security-alerts/ right? and who approves language implementation then, you mean like only the offical ones counts? surely the engine configures what the language can access or not, which is why is said the engine host options then there should be like model-verification that it's impossible to escape the sandbox otherwise you have adobe flash just on the server

**Comment by chumer** [comment]
>  if i can prove that through a buggy language implementation i can escape the sandbox and change data on the host, i could get listed on https://www.oracle.com/security-alerts/ right?

Yes, provided the bug is in an Oracle-supported language that is vetted for sandboxing. The polyglot sandbox (specifically the UNTRUSTED policy) is an Oracle GraalVM enterprise feature supported only for a specific set of Oracle-developed languages (e.g., GraalJS, GraalWasm). If you find a vulnerability in one of these approved implementations that allows guest code to break isolation, that is a valid CVE and should be reported.

However, this does not apply to arbitrary or custom language implementations. We do not support the UNTRUSTED sandboxing policy for languages we have not verified and approved.

It is important to distinguish between the guest code (untrusted) and the language interpreter (trusted). In our model, the language implementation (the interpreter) is part of the Trusted Computing Base (TCB). We trust the interpreter to enforce the sandbox rules on the guest code. This is why we perform rigorous security reviews specifically verifying they do not misuse Unsafe or leak references across isolated heaps.

Technically, heaps are isolated, making accidental access across boundaries difficult. On supported platforms, we also utilize hardware Memory Protection Keys (MPK) as a defense-in-depth measure to physically prevent a language from accessing memory outside its own isolate, even if a logic bug exists.

In the latest release we also added support for engine.IsolationMode=external which runs the guest application in separate OS process. For additional defense against language implementation bugs/crashes. But it is not required to run UNTRUSTED guest code.
