### ISSUE TITLE
Why SVM cannot automatically detect reflection on getDeclaredFields?

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#1470]
SVM requires configuration for reflections such as getDeclaredFields. It seems very easy to obtain such a fixed function name automatically. Why still need to explicitly set "allDeclaredFields=true" in the configuration file?

**Comment by kaspernielsen** [comment]
Because there is a lot of code out there that needs to filter the result of getDeclaredFields(). For example, let's say you are writing a dependency injection framework. And you want to find all methods annotated with @Inject. The only way to do this is programmatically. That is, call getDeclaredFields() and check whether or not each field is annotated with @Inject. 

If allDeclaredFields was automatically set to true, this would mean that every component/bean would automatically have every field and method added.

**Comment by cstancu** [comment]
As @kaspernielsen mentioned this could lead to too many fields being registered for reflection. We prefer that reflection registration is either explicit or it is the result of using the Native Image agent to profile the application.
