### ISSUE TITLE
 ForkJoinPool.commonPool() in the image heap

### ISSUE THREAD

**Issue by lburgazzoli** [oracle/graal#1524]
So while working on making camel running on quarkus I've run into some issues related to the ` ForkJoinPool.commonPool()` found in the image heap as result of how Caffeine constructs caches:

- https://github.com/ben-manes/caffeine/issues/332
- https://github.com/quarkusio/quarkus/issues/3300

As mention in the issues a possible workaround is to lazily initialized the pool but that's not always possible as 3th party libraries using Caffeine may not expose a way to do so. 
Another solution is to move the initialization of some classes at runtime which lead to have all the classes that depends on the offending one being needed to be initialized at runtime too which remove some benefits of build time initialization.

/cc @ben-manes

**Comment by ben-manes** [comment]
Is it reasonable to have Graal transform the calls to by lazy if possible (no direct usage)? In Caffeine’s case it is setting the executor instance field, not invoking it. If possible I’d like to avoid adding a workaround as the issue seems better to address by improving graal instead. What is the expectation for developers, both library and application?
