### ISSUE TITLE
C1/C2 Compilers vs GraalVM

### ISSUE THREAD

**Issue by up-to-you** [oracle/graal#1543]
Can C1/C2 compilers in standard JDK/JVM distributions be ever replaced by GraalVM JIT ? Are there any future plans or expectations?

**Comment by thomaswue** [comment]
This is a question for the OpenJDK community and not for the GraalVM project. We provide a fully compatible Java SE 8 distribution with the GraalVM just-in-time compiler at https://www.graalvm.org/downloads/.

**Comment by adinn** [comment]
Thanks for referring this to the correct forum, Thomas. I agree that it would be better directed to the OpenJDK discuss list.

However, I will note right here that I doubt the first question will receive an answer even in that forum. That's mainly because it not clear (to me at least) that replacing one with the other is something either project necessarily wants.

I know the question asks about possibility, but it also rather unfortunately makes it sound like the two projects are in a race to the death. The truth is that they /can/ co-exist and offer distinct advantages. For that reason I don't believe that first question is currently being seriously considered and investigated by the OpenJDK team.

Which really answers the second question but I'll state it explicitly: as far as I am aware there are no definite plans or expectations to /replace/ C1+C2 with GraalVM.
