### ISSUE TITLE
CopyingImageHeapProvider unavailable via command line flag

### ISSUE THREAD

**Issue by sliverdragon37** [oracle/graal#1576]
When using native-image on linux, the heap provider implementation defaults to LinuxImageHeapProvider. However, while it appears that --features=com.oracle.svm.core.os.ImageHeapProviderFeature should allow the selection of the CopyingImageHeapProvider, in practice the LinuxImageHeapProvider is still selected.

**Comment by peter-hofer** [comment]
The `ImageHeapProviderFeature` is only supposed to register a `CopyingImageHeapProvider` when no "better" implementation is available. `CopyingImageHeapProvider` copies all image heap memory, possibly has to read parts of it from disk first to do so, and then all of the image heap stays in physical memory or can only be swapped out. In contrast, `LinuxImageHeapProvider` and `DarwinImageHeapProvider` are typically more efficient because they only create a mapping of the image file to memory, which doesn't require that all of the file is read from disk initially, and any unmodified memory regions can be shared between isolates or even released from physical memory when they haven't been accessed for some time.

Do you have a specific use case for which you would prefer `CopyingImageHeapProvider`?

**Comment by sliverdragon37** [comment]
We're looking at supporting an execution environment where mmap and other system calls are unavailable. It sounds like the CopyingImageHeapProvider is intended for that kind of use case, but it isn't clear to us how it is intended to be enabled.

**Comment by peter-hofer** [comment]
We currently don't support directly selecting an implementation, the `Feature`s are designed so they register applicable providers in order of preference and the first one to succeed wins. However, if you don't need isolate support, you can bypass the `ImageHeapProvider` code altogether using option `-H:-SpawnIsolates`. Otherwise, if you're comfortable editing the source code, you could disable `LinuxImageHeapProvider` by removing its `@AutomaticFeature` annotation or overriding its `isInConfiguration` method to check an option (see `SubstrateOptions`, `HostedOptionKey`).

**Comment by peter-hofer** [comment]
Closing: a platform without `mmap` (and other system calls) likely needs more work than using a different `ImageHeapProvider`, at the very least implementing a different `VirtualMemoryProvider`.
