### ISSUE TITLE
Graal runs SLOWER than regular java?

### ISSUE THREAD

**Issue by tomerz90** [oracle/graal#1593]
Im trying the Blender example from here:
https://www.graalvm.org/docs/examples/java-performance-examples/

And for some reason the run times I get for Graal are 980~ms, when I add the flag that disables Graal I get the same timings as in the example (even a bit faster).
What am I doing wrong? Im running on Ubuntu 18.04 with community edition Graal, I added the Graal dir as first in my PATH (regular java is also there, last)

**Comment by thomaswue** [comment]
Thanks for pointing us to this issue. This example is approximately the same speed with CE and substantially faster only with EE, which is not what the documentation for the example indicates.

The problem with it is that it does not appropriately show case partial escape analysis (PEA). It only shows full escape analysis (EA) and double arithmetic optimizations, both of which are also present in standard C2.

Here is a modified version of the example that actually show cases the partial escape analysis - i.e., an object that is allocated on a common path and escapes only on an uncommon path: 

`
public class Blender {

    private static class Color {
        int r, g, b;

        private Color(int r, int g, int b) {
            this.r = r;
            this.g = g;
            this.b = b;
        }

        public void add(Color other) {
            r += other.r;
            g += other.g;
            b += other.b;
        }
    }

    private static final Color[][][] colors = new Color[100][100][100];

    public static void main(String[] args) {
        for (int j = 0; j < 10; j++) {
            long t = System.nanoTime();
            for (int i = 0; i < 100; i++) {
                initialize(new Color(j, j, j));
            }
            long d = System.nanoTime() - t;
            System.out.println(d / 1_000_000 + " ms");
        }
    }

    private static void initialize(Color id) {
        for (int x = 0; x < colors.length; x++) {
            Color[][] plane = colors[x];
            for (int y = 0; y < plane.length; y++) {
                Color[] row = plane[y];
                for (int z = 0; z < row.length; z++) {
                    Color color = new Color(x, y, z);
                    color.add(id);
                    if ((color.r + color.g + color.b) % 42 == 0) {
                        // PEA only allocates a color object here.
                        row[z] = color;
                    } else {
                        // In this branch the color object is not allocated at all.
                    }
                }
            }
        }
    }
}
`

Let me know if this example works as intended.

**Comment by tomerz90** [comment]
Thanks for the reply and the modified example Thomas!
I will check it shortly, however, this is not what worries me.
At least in my books, and maybe im wrong somehow, but ~50% slower is not "approximately the same"... Im getting 980~ms with Graal CE and 660~ms with regular java...

**Comment by plokhotnyuk** [comment]
@tomerz90 I'm wondering too... why this issue was classified as bug in docs, while you have detected a real performance issues with CE?

**Comment by tomerz90** [comment]
Thanks @plokhotnyuk 
I was under the impression Graal JIT's code is at least as performant as the code generated by C1/C2, is that wrong?
The reason I was playing around with the examples is that I took one of our production services and compared a day's load (same load) with C1/C2 and with Graal, and Graal came out inferior, which was weird to me considering all the good reviews I have been seeing, so I thought I was misusing somehow and thought I'll start with the examples first and see that everything works as expected.
Maybe this is some sort of regression? @thomaswue

**Comment by thomaswue** [comment]
For maximum throughput on long-running programs, we recommend the EE version, which does a lot more advanced optimizations at the expense of compilation times. 

The CE version currently creates better code than C2 for programs with many abstractions (like the Scala code of Twitter for example). There are some open performance issues with the CE version that we are working on. Find here some data on CE vs EE vs C2 on larger workloads: https://renaissance.dev/. We are interested in any performance data you are able to share from your production workload.

@plokhotnyuk I did the analysis why CE is slower here and the reason is loop peeling. In many circumstances, loop peeling can help with improving performance, but this is a case where it results in a severe performance hit. Passing "-Dgraal.LoopPeeling=false" makes CE perform better than C2 by ~15%. I am surprised by how much of a difference this makes. We can fix this, but need to be careful about the impact on other workloads.

@tomerz90 Can you run the example with "-Dgraal.LoopPeeling=false" also on your machine?

**Comment by tomerz90** [comment]
That was indeed the issue, I am now getting 590~ms on Graal.

**Comment by thomaswue** [comment]
OK, thanks for confirming that GraalVM CE is ~12% faster than C2 with this flag also on your machine. 

We recommend GraalVM users to test both CE and EE on their workloads. There is always the possibility to tune your workloads by modifying flags. We need to make compromises between workloads, so for a specific workload one can always get a few more percentages by specializing the flag configuration. Chris Thalinger from Twitter has a nice talk about that where he uses machine learning for GraalVM flags to improve performance. Check it out here: https://www.youtube.com/watch?v=ldk8CL0fygE

We create major releases every 3 months and mention in release notes notable performance improvements. Best to follow our Twitter handle @graalvm or out mailing list graalvm-announce@oss.oracle.com.

**Comment by plokhotnyuk** [comment]
@thomaswue WDYT about using of ML on some broad (to avoid overfitting) set of benchmarks to get optimal values of default options for GraalVM CE/EE? or use it to detect most impactful of them for performance tuning guidelines?

**Comment by thomaswue** [comment]
We have been doing this for optimizing default values. It is a great suggestion to derive performing tuning guidelines from the variance in the results. @farquet is the engineer behind our parameter tuning technology.

**Comment by farquet** [comment]
We are doing parameter tuning to : 
- Find best default values
- Explore the behavior of the compiler in many different configurations to discover opportunities to improve the compiler optimizations further

@plokhotnyuk, publishing a list of flags ranked by average performance impact is an interesting idea. However, I am not sure this is something we should encourage people to do because this strategy only works on tiny toy benchmarks like the one above because it is completely dominated by a few optimizations.
For instance, on all benchmark suites we test, disabling LoopPeeling never helps (but it can lead to up to 3% regression in some benchmarks).

In a real-world application, touching those boolean flags will then probably never help. And if it does, that's a bug that should be reported to us. Changing non-boolean flags is much trickier since the parameter space becomes much bigger and they interact with each other, that's something we are doing too for finding reasonable defaults, and that's what Twitter does to overfit the Graal inliner on their workload.

However, what we **strongly encourage** is to help us grow our set of benchmarks with new workloads that people care about nowadays. If one can share a good benchmark (for instance to https://github.com/renaissance-benchmarks/renaissance ), we will do all our internal tuning and try to squeeze the most performance out of it. And maybe a future release will give a boost to that kind of workloads.

**Comment by tomerz90** [comment]
@farquet What info can I provide to help you guys? Obviously I cant provide the code or the JIT created code, is there anything else that can be of use to you guys?

**Comment by farquet** [comment]
If sharing JFR recordings of a C2 run versus a GraalVM run is an option, that would be best.
If not possible, a description of what the application does, what kind of technology or frameworks it uses would be a good starting point.
Ideally, we would like to have a minimal reproducer where we see that performance difference.

You could also compare the JFR profiles yourself to identify which method is taking more time in Graal vs C2. The profile will also tell you what dominates the time spent in the application, which is a useful piece of information anyway.
