### ISSUE TITLE
Anonymous Union

### ISSUE THREAD

**Issue by webfolderio** [oracle/graal#1760]
Is it possible to add annoymous union usage to [CInterfaceTutorial.java](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.tutorial/src/com/oracle/svm/tutorial/CInterfaceTutorial.java)

I am trying to bind libuv structures to C interface but couldn't find a proper way to do it.

_Sample code snipplet:_

```C
typedef struct uv_stdio_container_s {
  uv_stdio_flags flags;

  union {
    uv_stream_t* stream;
    int fd;
  } data;
} uv_stdio_container_t;
```

**Comment by medoussboug** [comment]
To bind native structures like uv_stdio_container_t from the libuv library to Java, you typically use Java Native Interface (JNI) or other Java Native Access (JNA) libraries. However, directly using anonymous unions in Java is not straightforward because Java does not have a native concept of unions.
