### ISSUE TITLE
java.lang.ArrayStoreException thrown from precompiled Micronaut application

### ISSUE THREAD

**Issue by musketyr** [oracle/graal#1765]
Although the compilation by `native-image` reports no error I'm getting an exception when executing a Micronaut controller:

```
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
```

To reproduce the error:

1) install docker (https://docs.docker.com/install/)
2) install SAM CLI (https://github.com/awslabs/aws-sam-cli)
3) clone https://github.com/musketyr/geecon-lambda-function
4) run `./sam-local.sh` from the cloned repository
5) open http://localhost:3000/api/tasks or run `curl http://localhost:3000/api/tasks` in a different shell

the error is somehow related to following changes as the application was able to run gracefully before

https://github.com/musketyr/geecon-lambda-function/compare/master..3093872954143fe1791bf0b08047aee25b775931

**Comment by thomaswue** [comment]
Do you have a full stack trace? Can you post exact versions used?

**Comment by graemerocher** [comment]
@musketyr @thomaswue I tried catching the exception but `e.printStackTrace(System.err);` produces no output so the stack trace is empty.

These issues normally stem from a case where some annotation is referencing a class that is not on the classpath. With regular Java these annotations are not being touched but when running as a native image they are and it is causing this exception. 

Unfortunately the error gives no indication as to which annotation on which class is referencing which type that could be causing the error which makes it very hard to debug. The lack of a stack trace in fact means that tracking this down is going to be very complicated.

**Comment by musketyr** [comment]
@thomaswue as @graemerocher has already written there is no stack trace. the application is build using Graal's `19.2.0.1` Docker image.

the application current needs access to existing Postgres database. if you send me your IP I can add you to one created for this reproducer.

**Comment by musketyr** [comment]
just tested it with application compiled with `19.2.1` and the error is still there without any stack trace. At least showing some sensible stack trace would help to work around the issue.

**Comment by cstancu** [comment]
We touch annotations at image build time, but this should not result in any different behavior at run time than regular Java. I think this problem stems from the JDK bug https://bugs.openjdk.java.net/browse/JDK-7183985. When an annotation declares a `Class<?>` array parameter and one of the referenced classes is not present on the classpath parsing the annotations will result in an `ArrayStoreException` instead of caching of a `TypeNotPresentExceptionProxy` (which would then be materialized into an `TypeNotPresentException`). This results into an `java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy` thrown at runtime. During build time we defend against this by simply behaving as if the type doesn't declare any annotations. However, for runtime, to preserve the original JDK behavior, we pack and rethrow the original error. (You can search the SubstrateVM code base for `JDK-7183985` to find the code that deals with this.) This bug was fixed in JDK11+, but not in JDK8. Does your example work with normal JDK8?

Can you provide a minimal, self-contained reproducer that doesn't involve installing SAM which requires creating and AWS account and setting up an S3 bucket?

**Comment by graemerocher** [comment]
Here is a fork with the changes to use Netty https://github.com/graemerocher/geecon-lambda-function

To reproduce run:

```
./gradlew clean assemble
native-image --no-server --no-fallback -cp build/libs/geecon-lambda-function-0.1-all.jar
./server
```

**Comment by musketyr** [comment]
@cstancu thanks to @graemerocher I was able to create reproducer without SAM:

1. clone the latest `docker-only` branch (https://github.com/musketyr/geecon-lambda-function/tree/docker-only)
2. run `./docker-run.sh

**Comment by cstancu** [comment]
@musketyr I can build and run the app with the `docker-only` branch but I cannot replicate the problem. Running `./docker-run.sh` builds and executes the native image and then I get:
```
$ curl http://localhost:8080/api/tasks
[{"id":1,"summary":"Learn Micronaut with GraalVM","description":"Required","done":false}]
```

**Comment by musketyr** [comment]
Ok, it surprisingly works for me on another machine as well. Maybe something was cached. 

Please, try the following instead:

```
curl http://localhost:8080/api/tasks/search?q=micronaut
```
