### ISSUE TITLE
Sulong callbackLibrary.c headers still not found

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#1818]
I thought this was fixed - turns out just nobody was rebuilding Sulong itself to notice until we updated our CI.

Workaround is

```
SDKROOT=`xcrun --show-sdk-path`
```

```
/Users/anka/graal-shopify/sulong/tests/com.oracle.truffle.llvm.tests.native/src/callbackLibrary.c:30:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
1 error generated.
make: *** [bin/callbackLibrary.o] Error 1
```

Related to https://github.com/oracle/truffleruby/issues/1733.

**Comment by chrisseaton** [comment]
@eregon

**Comment by rschatz** [comment]
Hmm... That should be fixed already, our custom LLVM toolchain should automatically call all compile commands through `xcrun` on darwin: https://github.com/oracle/graal/blob/2f200c03e7f2b319ef5c46538900e7c8f19d6215/sulong/projects/com.oracle.truffle.llvm.toolchain.launchers/src/com/oracle/truffle/llvm/toolchain/launchers/common/ClangLike.java#L148-L152

Are you on an older version? Or do you maybe have some environment variables set that override what compiler is used?

**Comment by chrisseaton** [comment]
I'm on Graal `aee967f1d90e1f032b266c62d10fc8c32a805fb8` (which is what TruffleRuby uses.) That has the same code for the lines you've linked above.

`com.oracle.truffle.llvm.libraries.native` uses `"CLANG" : "<path:SULONG_LLVM_ORG>/bin/clang",` rather than `"CLANG": "<toolchainGetToolPath:native,CC>",`, is that intentional?

**Comment by rschatz** [comment]
Ah, right, that might be the problem. This library is really compiled to native code, not to bitcode, so it has to use the original clang, not our wrappers. I forgot about that. Because of that the fix doesn't help for the Sulong build itself, only for things built on top of that.

I'll check what we can do about that (after I find out how to uninstall the old workaround for that issue from my macbook :P ).

**Comment by chrisseaton** [comment]
Could `mx` set

```
SDKROOT=`xcrun --show-sdk-path`
```

globally before it runs the build?

**Comment by zapster** [comment]
Hi @chrisseaton!  This should now be fixed for real on master. In addition, `mx build --all` in `sulong` should now also work on macOS. I've added a build-all gate to our CI to keep it this way, but since macOS setups tend to differ quite a lot I encourage you to file any build issues you are experiencing. Thanks!
