### ISSUE TITLE
[native-image] Add runtime compilation support for AArch64

### ISSUE THREAD

**Issue by teshull** [oracle/graal#1841]
Currently in AArch64 SVM runtime compilation will not work. In particular, the patching performed in RuntimeCodeInstaller.java is very AMD64 specific. It would be nice to get this to work so Truffle could JIT compile code on AArch64.

In order to enable AArch64 support, so far I foresee that the following support needs to be added:

1. AArch64NativeImagePatcher filled in with correct patching methods
2. trampoline patches (8 bytes -- ldr scratch, [pc+offset]; br [scratch])
3. inline object constant patching (series of mov imm16 instructions)
4. coherency support for installing new code (In AArch64 other threads need to issue ISB (instruction synchronization barrier) before new code is installed)

I already have started to work on items 1,2, and 4. 

Items 1 and 2 are very straightforward.

For item 4 my idea is to add new state to each thread's safepoint status (statusTL). I want to be able to record that before a thread returns to the Java state it needs to issue an ISB. To do this, I am creating two new states: STATUS_IN_SYNCHRONIZED_NATIVE, and STATUS_IN_SYNCHRONIZED_JAVA. These states are equivalent to STATUS_IN_NATIVE and STATUS_IN_SAFEPOINT, except before eventually transitioning back to the status_in_java state an ISB is executed by the thread.

Currently I have implemented this new safepoint logic, but have made a mistake somewhere which frequently causes threads to get stuck in a spin loop.

Item 3 I believe requires move involved changes than I initially anticipated.  This is because the object constant immediate cannot fit into one instruction in AArch64. Moves in AArch64 can only fit 16bit immediates. This requires the patching to be performed differently, but it also looks to be a problem for some of the RuntimeCodeInfoAccess/GC methods which I think assume the entire reference will be contiguous in one immediate instruction.  (I have little to no familiarity with this code, so please correct me if I am wrong here.)

As a short-term fix, I wanted the compiler to not inline object constants, but instead create data section references. However, currently there seems to be issues with that as well (I posted that issue here: #1840). 

At this point I am creating this issue to:
1. See if my current approach makes sense to other people
2. Ensure this support is not being worked on by someone else and I am needlessly replicating their work.

If anyone wants to assist, that would be great as well. It would especially nice if someone with code-level access to GraalEE could apply my safepoint patch and use gdb to see where the spin loop is occurring.

**Comment by tshull226** [comment]
In case anyone is interested, I have posted my code for the new safepoint state [here](https://github.com/tshull226/graal/tree/new_safepoint_state)

I fixed my previous issue, so I am optimistic the code is correct now.

**Comment by adinn** [comment]
Hi Thomas,

I *am* interested in this ;-) just having difficulty finding the time to look at it. I'm concerned about the possibility that the runtime patching you are proposing for AArch64 may run up against coherency issues. In OpenJDK we rely on de-optimization + invalidation of compiled methods and recompilation to perform code update on AArch64 far more often than is done in the x86_64 port. That is because there is a much more limited  set of instructions or instruction sequences that can be safely patched on AArch64 when another thread might be executing code in the address range being patched. You may well get away with patching on a specific architecture but that does not guarantee that you can rely on it. It might be good to compare your plans with what OpenJDK does and also to discuss with someone at ARM (e.g. Stuart) or with Andrew Haley (who wrote most of the relevant OpenJDK AArch64 runtime code) what the architecture spec says about in-flight patching.

**Comment by adinn** [comment]
@theRealAph Perhaps you could look at Thomas's patch?

**Comment by tshull226** [comment]
Yes, Stuart pointed me to Arm Architecture Reference Manual Section K 11.5.2. For better or worse in SVM right now I believe all threads are at a safepoint when new code is installing, and code isn't dynamically loaded/unloaded, so the coherency issues shouldn't be as difficult to resolve as for OpenJDK.

Right now I'm not sure how much patching of existing code (for inline caching) is being performed in Truffle. It may be possible that they are doing a more data-driven memorization approach as is done in V8 so there is not patching at all. That is something I need to look more into.

**Comment by tshull226** [comment]
I added a patch with this support #1977. Let me know if you have any comments.
