### ISSUE TITLE
[native-image] AArch64 questionable usage of immediate addressing

### ISSUE THREAD

**Issue by teshull** [oracle/graal#1864]
Currently many places SubstrateAArch64Backend.java are using immediate addresses. While some of the addresses being created have hard coded offsets, others, such as in createJNITrampolineMethod, have offsets dependent on the given compilation.

My fear is that sometimes some of these program-dependent offsets will exceed the boundaries of the immediate operand within AArch64 instructions. It looks like for IMMEDIATE_UNSCALED addresses the offset range is limited to [-256, 255], so it seems very possible for these boundaries to be exceeded.

@bobmcwhirter @sanzinger @adinn @theRealAph  Do you agree this could be a problem? 

If so, I am happy to add in the wrapper code which, provided the offset exceeds the boundaries of the allowed immediate operand, would instead issue the needed series of mov instructions to load the offset into a register and use `createRegisterOffsetAddress` instead.

**Comment by theRealAph** [comment]
We'll have to do something like that. In the longer term we should have a pattern-matching code generator that only generates immediate instructions when they're in range. In the meantime, all uses of immediates with limited range should be wrapped with code which expands as needed.

**Comment by tshull226** [comment]
I've made a patch for this and plan to upload it on Monday.

Yeah, eventually this code should be the target of optimizations. Right now in AArch64 some of the IR nodes being lowered directly to assembly I think are too high level. I think for AMD64 it maybe works because they can be converted into one instruction (I still need to look at SubstrateAMD64Backend.java in detail), but on AArch64 many instructions are being produced. For AArch64 at least, I think it would be beneficial to have some of these nodes lowered to simpler nodes and allow pattern matching and other optimizations to be run on them.

**Comment by tshull226** [comment]
I made a PR for the patch #1894

**Comment by teshull** [comment]
Fixed via (https://github.com/oracle/graal/commit/eaf58f096727bad1c3fda677efe6bf902fbd6b1e)
