### ISSUE TITLE
[native image] -H:-MultiThreaded causes segfault

### ISSUE THREAD

**Issue by tshull226** [oracle/graal#1865]
When using the master branch at commit (7398fc8b9f9ecb72db3102d03b8de73ff357a9b3) if I run `mx native-image -H:-MultiThreaded HelloWorld` using the HelloWorld example on the SVM README, the executable created causes a segfault. Is this a know issue or I am doing something wrong?

I should also note that I am building this on linux-amd64 and am using openjdk1.8.0_232-jvmci-19.3-b05.

**Comment by christianwimmer** [comment]
This is a known issue. The single-threaded mode is not overly useful anymore and therefore not a high priority to fix. The {{JNIEnv}} that is handed out to C code via JNI is the same pointer as the internal {{IsolateThread}} - but that only exists in multi-threaded mode.
The single-threaded mode still works when switching back to the (now deprecated) substitution platform instead of linking in the C code of the JDK. But eventually both of them will be removed from the codebase to keep it small and maintainable.
