### ISSUE TITLE
`gu` missing

### ISSUE THREAD

**Issue by veganaize** [oracle/graal#1868]
The `gu` update utility is apparently missing from GraalVM 19.3.0 (Windows) community edition.  It is not located in $GRAALVM_HOME/bin/gu and doesn't seem to be found anywhere within the directory structure.

C:\graalvm-ce-java11-19.3.0\bin>java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-jvmci-19.3-b05-LTS)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode
, sharing)

**Comment by ezzarghili** [comment]
There are no extra plugins to pull for windows and native-image is part of the base build.

**Comment by ezzarghili** [comment]
Closing this, please feel free to reopen if you still have questions.

**Comment by fabrice-ducos** [comment]
I don't understand why this issue was closed. I have just downloaded [graalvm-jdk-21 for Linux](https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz) and the `gu` tool is not included in the bin directory, contrarily to what is documented [here](https://www.graalvm.org/22.0/reference-manual/graalvm-updater/).

The `native-image` tool is available and works. But the OP was asking for the `gu` tool, and it is definitely not.

**Comment by fabrice-ducos** [comment]
Thanks for the hint! Being new to GraalVM, my confusion came from the fact that the [documentation for GraalVM 22](https://www.graalvm.org/22.0/reference-manual/graalvm-updater/)  does refer to the `gu` tool, and that I thought that it was newer than GraalVM for JDK 21 (because 22 > 21), and therefore that the `gu` tool was still documented as available.
