### ISSUE TITLE
Explore Alternative Build Tools

### ISSUE THREAD

**Issue by bobmcwhirter** [oracle/graal#1914]
Per the Zurich community workshop discussions, opening this issue to further discuss the build system.

I've spent the last month or two with `mx`, `suite.py` and Maven.

While I've come to terms with `mx` and no longer despise it quite as much as I initially might have, it's still a hurdle and friction to people who may be needing to augment the build system.

I've also come to learn, though, that Graal in its current state, cannot simultaneous be defined by Maven in order for a CLI-based build while concurrently having appropriate dependencies laid down for IntelliJ or other IDEs, due to MRJAR support (or lack thereof) in Maven and IDEs.

Having `mx` generate Maven `pom.xml`s akin to the `ideinit` is less valuable and exciting.

I think my current _personal_ (not speaking for Red Hat or any other larger group) opinion is either stick with mx as-is, or make suitable adjustments to the project to allow a Maven build to be the canonical build system. Using Maven as a side-car won't really solve the friction problem, and given the current build and project layout strategy, can't achieve 100% parity with mx.

**Comment by dougxc** [comment]
Thanks for starting the discussion @bobmcwhirter. While I also like the idea of replacing mx with standard tooling, as you've discovered it's a non-trivial task.

The example you give of multi-release jars is just one example where mx has [special support](https://github.com/graalvm/mx#versioning-sources-for-different-jdk-releases). In fact, it goes  beyond multi-release jars to allow JDK 8-only projects (or `overlays` in mx terms) which is important for projects that use JDK 8 internal API.
 
Another example is the support we have for compiling JDK9+ code that uses [concealed packages](https://github.com/graalvm/mx#use-of-concealed-packages).

For the GraalVM team at Oracle, it would be too disruptive to move away from mx since we use it for almost everything. I think the best possibility is to see if the canonical description of dependencies can be moved to something like Maven's `pom.xml`s to replace `suite.py` for the purpose of building the code. However, even that is far from trivial given how much build logic is expressed outside of `suite.py` files.

**Comment by thomaswue** [comment]
@dougxc Is it one of the options to have mx auto-generate the pom files & check them into the project repository such that running mx is only necessary when changing project dependencies?

**Comment by dougxc** [comment]
I think that would not be hard.

**Comment by bobmcwhirter** [comment]
Things that seem difficult for a Maven-based lifestyle is the fact that the DIST artifacts seem to completely shade in their dependencies (truncating those that appear in other DIST dependencies) which is... not an easy Maven dependency solve.  And ultimately can confuse the IDE once loaded up.  I've struggled with this quite a bit.

**Comment by fernando-valdez** [comment]
Hi @bobmcwhirter, do you think this request applies due to the current state of the project?

**Comment by fernando-valdez** [comment]
Closed due to lack of response. Please feel free to re-open this ticket if this request is valid in the current sate of the project.
