### ISSUE TITLE
Regular segfaults

### ISSUE THREAD

**Issue by mark-christiaens** [oracle/graal#1932]
I'm starting an Eclipse in debug mode running on top of Graal VM from my development Eclipse.  I get regular crashes usually in the first moments of actually using the debuggee. 

When I use a regular OpenJDK to run my debug process then all is well.

I've attached the error logs.
[hs_err_pid708232.log](https://github.com/oracle/graal/files/3922286/hs_err_pid708232.log)
[hs_err_pid584511.log](https://github.com/oracle/graal/files/3922287/hs_err_pid584511.log)
[hs_err_pid583865.log](https://github.com/oracle/graal/files/3922288/hs_err_pid583865.log)

**Comment by dougxc** [comment]
@davleopo can you please look into this.

Two of the hs_err logs indicate that the crash happens after deoptimizing `java.util.ArrayList.elementData(I)Ljava/lang/Object;`. So we should try get graphs for this compilations as well as seeing if disabling compilation of this method is a workaround.

**Comment by davleopo** [comment]
@dougxc  sure.

@mark-christiaens thanks for the bug report.  Is there an easy way for you to provide a minimal example/setup to reproduce the problem? 

If not we should try to graphs of the compilations in order to narrow the problem down.
Assuming its indeed a problem in the compilation of the `java.util.ArrayList.elementData(I)Ljava/lang/Object;` method could you try to run your eclipse with the additional arguments enabling compilation graph dumping to your local file system via
`-Dgraal.Dump=:5 -Dgraal.MethodFilter=ArrayList.elementData -Dgraal.DumpPath=<directory where various Graal dump files are written to>` this should produce a folder with dumps of the compilations done by Graal. We could then inspect those.

Based on the hs_err logs you provided it seems you disabled bytecode verification with `-Xverify:none` . Does your application require to turn of bytecode verification to run?
Additionally, the enabling of jvmti with the debugging agent `-agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:38995` can also be related to the problem. 
When does the crash happen exactly? Right after startup or does it crash after you interact with the debugee?

**Comment by mark-christiaens** [comment]
- I won't be able to produce a minimal fix; we're talking a million line application here so I have no idea how to reduce it down.
- I'll try to generate the compilation graph.  I'll get back to you on that.
- No reason for the `-Xverify:none`.  I suspect we configured this once upon a time to increase startup speed a bit.  I'll remove it and see what happens.
- Eclipse starts nicely and then, when I actually start using it, I sometimes see the crash.  So, I would assume that by that time, Graal has successfully loaded thousands of classes and executed a big bunch of code.

**Comment by davleopo** [comment]
@mark-christiaens  sounds good.

Although the chances are low to catch it that way you could try to run with compiler assertions enabled with `-Dgraal.DetailedAsserts=true -Dgraal.VerifyGraalGraphs=true  -Dgraal.VerifyGraalGraphEdges=true -esa` that should catch anything obviously wrong during compilation.

**Comment by davleopo** [comment]
@mark-christiaens  do you have any further crashes or updates on this issue?

**Comment by mark-christiaens** [comment]
@davleopo I've been running graal 20.0.x and now 20.1.x continuously underneath my Eclipse development environment and the issue seems to be gone.  I'll close the ticket.  Thanks BTW for the great work!

**Comment by davleopo** [comment]
@mark-christiaens thanks, good to hear that, just re-open the issue if the crash pops up again!
