### ISSUE TITLE
License on native-image component 

### ISSUE THREAD

**Issue by acnologia000** [oracle/graal#2025]
i am not clear about licensing terms of native-image component 
its constantly referred as early adopter technology which further blurs assumptions about it having GPL v2 license

**Comment by christianwimmer** [comment]
Note that we cannot give legal advice here. You always need to consult a lawyer for a definitive answer regarding licenses.

But some remarks: I think you are confused because you are mixing up GraalVM Community Edition (CE) and GraalVM Enterprise Edition (EE):
* GraalVM CE is licensed entirely under open source licenses. GPLv2 with Classpath Exception in particular for the Native Image part. You can do with GraalVM CE whatever you want as long as you stay within the license terms. Oracle is not responsible for anything - it might work or not work.
* GraalVM EE is an Oracle product where you pay for support, and get guaranteed response times according to the support contract you have with Oracle. Part of that contract is that Native Image has early adopter status. Your Oracle sales representative can clarify for you what that means.
