### ISSUE TITLE
No HomeFinder when compiling with llvm

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2033]
when compiling using the LLVM backend, native image build fails:

```Error: ImageSingletons do not contain key org.graalvm.home.HomeFinder
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1504)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1266)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1227)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1186)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1683)```

The same code works fine when compiling without the LLVM backend.

**Comment by karussell** [comment]
Thanks @johanvos. Might be related to the recently merged PR #1890.

**Comment by loicottet** [comment]
@johanvos does it still fail with the changes in #1890?

**Comment by johanvos** [comment]
yes it does. Adding the feature manually (which was the workaround before #1890) works though.

**Comment by karussell** [comment]
How can I add the "feature manually"?

Or is there a way I can help here?

**Comment by johanvos** [comment]
@karussell add this in the pom.xml inside the <configuration> tag of the plugin (e.g. https://github.com/gluonhq/client-samples/blob/master/Maven/HelloFX/pom.xml#L54) 

`<nativeImageArgs>--features=org.graalvm.home.HomeFinderFeature</nativeImageArgs>
`

**Comment by karussell** [comment]
Cool & Thanks! This indeed worked and made the problem disappear.

Now I'm getting a different exception: 

[Caused by: java.lang.UnsatisfiedLinkError: 'com.oracle.svm.core.hub.DynamicHub com.oracle.svm.core.snippets.KnownIntrinsics.readHub(java.lang.Object)'](https://gist.github.com/karussell/882ed87e6f7a92ad7928a61dd894e40b).

Used labsjdk-ce-11.0.6-jvmci-20.0-b02 and a fresh compiled graal vm did not help. Should I create another issue here or is this gluon plugin related?

**Comment by loicottet** [comment]
Fixed by [dbe88d](https://github.com/oracle/graal/commit/dbe88d25df1608e54b3e95aa80793e931a8164ec)

**Comment by karussell** [comment]
Thanks, can confirm that it works now without `nativeImageArgs`.
