### ISSUE TITLE
before was unexpected (...) (Windows)

### ISSUE THREAD

**Issue by Wdestroier** [oracle/graal#2044]
Hi, when I try to create the native image I get a "before was unexpected (...)" message
GraalVM version: java8-19.3.0.2, community edition
OS: Windows 10
![cmd](https://user-images.githubusercontent.com/14764307/71560769-bde4f000-2a4c-11ea-930d-46f9b23830f6.png)

**Comment by anthonyvdotbe** [comment]
@Wdestroier isn't this an issue with the `findstr` part of the command-line, rather than native-image itself? (since I doubt GraalVM would give a localized message like "before foi inesperado neste momento.") Or in other words, can you give a command to reproduce this issue that doesn't pipe to `findstr`? Either way, please post the exact command you entered in text, because the command in the screenshot doesn't seem what you entered (since it has `-jar ... NativeHelloWorld` on both lines)

**Comment by Wdestroier** [comment]
Hi @anthonyvdotbe! I ran native-image -jar "C:\Users\Wagner\Desktop\HelloWorld.jar" NativeHelloWorld under the graalvm-ce-java8-19.3.0.2\bin folder. I was missing a ", but I still get an error.
![message](https://user-images.githubusercontent.com/14764307/72559941-be6eea80-3884-11ea-8823-cc8046e1d69e.png)

**Comment by anthonyvdotbe** [comment]
@Wdestroier [this issue](https://github.com/oracle/graal/issues/1509) has the same error, and it says "install the Microsoft Windows SDK for Windows 7" and "be careful to use the SDKSetup.exe in the Setup subdirectory of the iso image"

**Comment by Wdestroier** [comment]
@anthonyvdotbe followed the instructions, restarted the computer, but I still get the same message

**Comment by jramirez-isc** [comment]
@Wdestroier as @anthonyvdotbe commented you need to install [Microsoft Windows SDK for Windows 7](https://www.microsoft.com/en-us/download/details.aspx?id=8442). We recommend using the `SDKSetup.exe` in the `Setup` subdirectory of the iso image.

Here are some points that can help you verify if you are setting up things correctly.

- Read the install instructions in order to download the correct iso image.

- When installing the SDK select all available installation options.

- After installing the SDK check that there isn't any failure/error message. If you see any error fix it before continuing, [this link](https://stackoverflow.com/questions/1901279/windows-7-sdk-installation-failure) may be helpful.

- Use the `Windows SDK 7 Command Prompt` for executing the `native-image` command.
