### ISSUE TITLE
[native-image] Exposed heap memory is higher than overall memory usage 

### ISSUE THREAD

**Issue by petrbouda** [oracle/graal#2124]
I'm running native-image (Quarkus) inside my docker container and trying to print heap and non-heap memory https://github.com/petrbouda/native-image-profiling/blob/master/quarkus/src/main/java/pbouda/nativeimage/quarkus/NotesResource.java
Docker container: --memory 100MB, --cpus 2

- exposed memory by **ManagementFactory.getMemoryMXBean()**

FORK_JOIN_POOL:  parallelism: 7
HEAP MEMORY: init = -1(-1K) used = 26870240(26240K) committed = 39419560(38495K) max = -1(-1K)
NON-HEAP MEMORY: init = -1(-1K) used = 34484448(33676K) committed = 34484448(33676K) max = -1(-1K)
FORK_JOIN_POOL:  parallelism: 7
HEAP MEMORY: init = -1(-1K) used = 27738808(27088K) committed = 39550728(38623K) max = -1(-1K)
NON-HEAP MEMORY: init = -1(-1K) used = 34484448(33676K) committed = 34484448(33676K) max = -1(-1K)

- exposed memory by **docker stats**

CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
a851c43a4f72        server              8.38%               20.8MiB / 100MiB    20.80%              0B / 0B             0B / 0B             33

I found limited information about SubstrateVM (please, if you have any good source of information about SVM internal, let me know) but it's weird that used memory is higher than total memory, at the first sight.

I also noticed that native-image is not container-aware, _parallelism_ does not reflect 2 cpus for my container. 

One more question, what the **non-heap memory** is used for? 33MB? I supposed that a majority of non-heap structures are not included in native-image.

Thanks, Petr

**Comment by petrbouda** [comment]
Please, let me know if you need better reproducer, I could minimize my example into a separated repo.

**Comment by peter-hofer** [comment]
Our `MemoryMXBean` reports not only memory which is explicitly allocated at runtime, but also memory (heap and non-heap) that is part of the native image file on disk and mapped into the address space. This is likely where the discrepancy stems from, especially because Docker docs state that they subtract page cache usage from memory usage, which would at least partially include this memory.

Non-heap memory is primarily compiled code, mainly compiled ahead of time and embedded in the native image, but potentially also at runtime.

As far as I can tell, `ForkJoinPool` on JDK 11-based native images uses either the property `java.util.concurrent.ForkJoinPool.common.parallelism` when set or calls `Runtime.getRuntime().availableProcessors()`, which uses `sysconf(_SC_NPROCESSORS_ONLN)` on a lower level. The HotSpot VM however has an implementation looking at affinities, cgroups and quotas, which likely makes it container-aware.

**Comment by petrbouda** [comment]
Hmm interesting, thanks for your explanation :) ... I've tried it outside the docker and the result was the same. If the image heap is mapped into the address space then the size of the image heap should be reflected in RSS, am I right? When I digress a bit, in case of an isolation feature, the image heap si mapped to every isolation because I am able to mutate it. Or it's shared and SubstrateVM handles only mutation?
Thanks a lot. It's a super interesting topic, I'm moving teams to Native-image Quarkus at my current company. However, need to know some internals, how GC works, how to set resources and laso thinking about profiling because of missing all JVM convenient tools :) .. (and also writing an article about profiling a native-image app and this is something I came across)

**Comment by peter-hofer** [comment]
Resident set size includes only those memory pages which are resident, which in our case are those pages of the image heap which have been accessed (and have remained resident since). As long as those pages are only read, they are part of the system's page cache, which Docker subtracts from memory usage. Only when a native image writes a page in the image heap and it is copied (copy-on-write) or allocates additional memory, it becomes _anonymous_ memory that would be counted. In other words, the image heap (and other parts of the image) from the disk is shared between processes and only parts of it (typically 4K or 4M in size) are copied into private memory when they are modified.
You can look into Unique Set Size (USS) or Proportional Set Size (PSS) for related metrics that are available on Linux and often more informative than RSS.

**Comment by petrbouda** [comment]
Thank you Peter, I think we can close the issue.
