### ISSUE TITLE
"Could not find option 'UseLowLatencyGC'"

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [oracle/graal#2179]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[e.g. 19.3]** 20.0.0
 - CE or EE: **[e.g.: CE]** CE
 - Build Time or run time failure: **[eg run-time]** Build Time
 - JDK version: **[e.g.: JDK8]** JDK11

**Describe the issue**
log:
```
Build on Server(pid: 5894, port: 38273)*
Error: Could not find option 'UseLowLatencyGC'. Use -H:PrintFlags= to list all available options.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
##[error]Process completed with exit code 1.
```

**Comment by SergejIsbrecht** [comment]
Which operating system?

**Comment by gergo-** [comment]
The release notes at https://www.graalvm.org/docs/release-notes/20_0/ and the docs at https://www.graalvm.org/docs/reference-manual/native-image/#lower-latency-garbage-collection both specify that the `-H:+UseLowLatencyGC` option is only available when using GraalVM Enterprise. GraalVM CE not supporting this flag is expected behavior.
