### ISSUE TITLE
Windows - native-image - UUID.randomUUID() returns always the same uuid

### ISSUE THREAD

**Issue by rsvoboda** [oracle/graal#2265]
On Windows, native-image based binary always returns the same uuid when calling `UUID.randomUUID().toString()`. On macOS and Linux with native-image based binary, the returned value is always different.

Using GraalVM Version 20.0.0 CE JDK11 on all the systems

HelloWorld.java
```java
import java.util.UUID;
public class HelloWorld {
    public static void main(String[] args) {
      System.out.println("Hello, World!");
      System.out.println(UUID.randomUUID().toString());
    }
  }
```

```
javac HelloWorld.java && native-image HelloWorld
helloworld
helloworld
helloworld
```
Windows (always the same UUID)
![Screenshot 2020-03-17 07 07 28](https://user-images.githubusercontent.com/925259/76827811-f3190700-681f-11ea-8d10-a369ce3983fd.png)

macOS (different UUIDs)
<img width="1306" alt="Screenshot 2020-03-17 at 07 11 03" src="https://user-images.githubusercontent.com/925259/76827835-fc09d880-681f-11ea-8077-2c25f59558cf.png">

**Comment by ninja-** [comment]
I think the same problem was with netty(Random number generator?) and they manually blacklisted relevant classess from `build-time initialization`. So the main question should be - is there any GraalVM-managed blacklist of such classess, or is it up to user to blacklist these classess everytime?

**Comment by christianwimmer** [comment]
Answering here an email sent to the GraalVM-dev mailing list: https://oss.oracle.com/pipermail/graalvm-dev/2020-April/000049.html

Usually the problem for such issues is that a class that caches state in a static field needs to be re-initialized at run time. The class `UUID.Holder`, i.e., the actual holder of the `SecureRandom` instance, cannot be the problem because https://github.com/oracle/graal/blob/0ba015f795ffbfe4142ff56d74b673832d3181ae/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java#L117 already re-initializes the class at run time.
So the problem must be somewhere in Windows-specific code in the security framework.

Re-initializing a class at run time is a workaround for JDK classes that need to be initialized during image generation (because the image generator uses them). So the class initializer runs twice: at image build time and at image run time. That can have all sorts of strange side effects when used without the proper care.

To debug the issue further, I would recommend debugging your example application on the Java HotSpot VM to see which class in the end provides the random number (`SecureRandom` is just the facade that delegates to the provider from the security framework) and see where a seed might be stored in a static field.

**Comment by Karm** [comment]
@christianwimmer Thank you for the detailed answer, I will be looking into it further.

**Comment by Karm** [comment]
@christianwimmer Thanks again. I have a working fix. Testing it now with JDK8 too... (I used just JDK 11 before).

**Comment by cstancu** [comment]
Fixed by https://github.com/oracle/graal/pull/2359.

**Comment by juangon** [comment]
It seems it isn't possible now to use UUID with GraalVM on .Quarkus I tried adding java.util.UUID, UUID$Holder and java.security.SecureRandom to -`-initialize-at-run-time` but doesn't compile using Quarkus. Any ideas?
