### ISSUE TITLE
[LLVM] Can't compile fish with the LLVM toolchain

### ISSUE THREAD

**Issue by mikehearn** [oracle/graal#2301]
Using GraalVM EE 20.1-dev on macOS High Sierra

```
bash-3.2$ java -Xinternalversion
OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02) for bsd-amd64 JRE (11.0.6+9-jvmci-20.0-b02), built on Jan 20 2020 14:32:51 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)

bash-3.2$ gcc --version
clang version 9.0.0 (GraalVM.org llvmorg-9.0.0-5-g80b1d876fd-bgb66b241662 80b1d876fd4296b48433de5b66eaebe551897508)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Users/mike/JVMs/graalvm-ce-java11-20.1.0-dev/Contents/Home/lib/llvm/bin
```

I tried building the fish shell with the LLVM toolchain. It's a C++ app. It fails due to some sort of incorrect header path search order. The cause is that the fish build system creates a file called `version` in the root directory of the build, and there's an identically named file called `version` in the C++ stdlib headers directory. The wrong file is included and that creates build errors. Presumably the root directory of the build is being added as an include search path before the C++ stdlib is and this breaks the build.

**Comment by olyagpl** [comment]
Hello @mikehearn, 
Do you have command line developer tools from Xcode installed:
$ xcode-select --install

Also, on macOS Mojave, you have to install headers, as system headers aren't provided in standard locations:
$ open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

Could you please try that on High Sierra?

**Comment by mikehearn** [comment]
Yes they're installed. I can build fish (and bash) normally, it's only with the GraalVM LLVM toolchain that it doesn't work. So the headers and other tools are available.

**Comment by zapster** [comment]
Hi @mikehearn!

Thanks for the report! I've tried the [latest 20.1 prerelease](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.1.0-dev-20200506_1135) as well as _master_ and it looks like compiling _fish_ works out-of-the-box now. There have been a few changes lately to the toolchain so it is indeed possible that we fixed the bug you were seeing. Note that I used the CE versions, but for the native mode toolchain, CE and EE are equivalent. Could you please try to update and verify that the issue is fixed for you as well?

A word of caution. System applications such as shells (like fish #2301 or bash #2300) are very likely to use unsupported features such a `fork`, signal handlers, etc. (See "Limitations" in the [reference manual](https://www.graalvm.org/docs/reference-manual/languages/llvm/).) So even if the build succeeds, the result might not run.
That said, I encourage you give it a try and see how far you can get. And to file further issues along the way. :wink:

**Comment by mikehearn** [comment]
Yep, understood about fork - I'm not expecting actually running subcommands to work. I was wanting to play around a bit with seeing if I could intercept fork and redirect it to the Java subprocess API, just for the challenge. Superb work if it's fixed, I'll try next time I get some "graal hours".

**Comment by mikehearn** [comment]
Yep, fixed, thanks.

It hits the stub for sigaction and dies at that point trying to print a (C level) backtrace.
