### ISSUE TITLE
[native-image] Update patch generation for apps build with native-image

### ISSUE THREAD

**Issue by Ali-RS** [oracle/graal#2472]
**Feature request for native-image**

Hi

It will be nice to be able to generate an update patch for native apps.
So that every time I update my app, clients do not need to download whole
app again and be able to just download an update patch and install it.

Regards

**Comment by Ali-RS** [comment]
Hi, 

Can "Native Image Bundles" be used for this purpose?

**Comment by fernando-valdez** [comment]
Generating update patches for native applications created with GraalVM's native-image tool is a complex challenge due to the nature of these native binaries. The native-image utility compiles Java bytecode into a standalone executable, which is optimized for the specific architecture and operating system it's compiled on. This results in highly efficient binaries with several benefits such as reduced resource usage, fast startup times, and immediate peak performance. However, these advantages come with the trade-off of creating a tightly coupled, monolithic binary file​
