### ISSUE TITLE
Using upstream fdlibm

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#2514]
Hello all,

As discussed in https://oss.oracle.com/pipermail/graalvm-dev/2020-May/000059.html

Since `fdlibm` is part of the OpenJDK and can be built as a separate static library (already shipped with labsJDK) there is no apparent reason for GraalVM to keep using an older clone of `fdlibm`.

Could you please provide details on how to properly achieve this?

A _proof of concept_ patch can be seen in https://github.com/zakkak/mandrel/commit/91922abe1cd8ef81fb8a5292644fee521c541bfc 
Based on my experience we will need to annotate `Target_java_lang_StrictMath` with more than one `@CLibrary` to include `fdlibm` which is now part of `strictmath`.

Edit: Replaced discussion link to point to the latest email in the thread.

**Comment by christianwimmer** [comment]
Some guiding principles
* The JDK change significantly, so the solution must work with JDK 8, 11, and 15.
* We must keep the way the StrictMath functions are called with a `@CFunction` and not rely on JNI, since StrictMath must work when JNI is disabled.
* But we can call the JNI functions from the JDK C library. They all have the additional JNI environment parameters, but don't use them. So we can just pass the null pointer for these parameters.
* Some StrictMath functions are implemented in Java in later JDK versions. So some of the StrictMath substitutions will no longer be necessary on JDK 11. The substitutions can be easily made conditional on the JDK version.

So the substitutions can look something like this (don't expect that to compile, it is just a draft how I think things can look):

```
@TargetClass(java.lang.StrictMath.class)
final class Target_java_lang_StrictMath {
    @Substitute
    private static double sin(double a) {
        StrictMathInvoker.sin(WordFactory.nullPointer(), WordFactory.nullPointer(), a);
    }
}

@CLibrary(value = "fdlibm", requireStatic = true)
final class StrictMathInvoker {
    @CFunction(value = "(the JNI exported symbol name)", transition = CFunction.Transition.NO_TRANSITION)
    private static native double sin(WordBase jnienv, WordBase clazz, double a);
}
```

**Comment by jerboaa** [comment]
Thanks @christianwimmer for the guidance!

**Comment by zakkak** [comment]
Thanks for the help @christianwimmer 
I am also considering adding tests for StrictMath, suggestions are welcome.
