### ISSUE TITLE
RFC: Is it possible oracle/graal became subproject of OpenJDK community?

### ISSUE THREAD

**Issue by netroby** [oracle/graal#2538]
RFC: Is it possible oracle/graal became subproject of OpenJDK community?

The JCP progress is the most valuable part of the OpenJDK community. 

GraalVM looks very amazing. but it do not have the long term development roadmap. 
There is no strong community guidelines. code conduct . 

Only oracle itself can know what will happened.

**Comment by shelajev** [comment]
Some resources you mention: 

* Contribution guidelines: https://www.graalvm.org/community/contributors/
* Code of conduct: https://www.graalvm.org/community/conduct/
* Projects and roadmap for some GraalVM components: https://github.com/oracle/graal/projects

GraalVM is a separate open source project and has different goals, vision, etc from OpenJDK. These are both open source projects that use each other: GraalVM builds contain an OpenJDK based JDK, and OpenJDK takes in the GraalVM compiler (https://openjdk.java.net/jeps/317), so there's definitely collaboration happening. However, the scope of the GraalVM project is more broad, for example in terms of programming languages support. 

This is not the correct venue to discuss what is the most valuable part of other projects' communities, sorry.

**Comment by adinn** [comment]
> The JCP progress is the most valuable part of the OpenJDK community.

That's quite arguably a serious misnomer. The OpenJDK project makes very minimal use of the JCP process (essentially it uses it to rubber stamp releases that have already been agreed on by internal processes -- RFRs, CSRs and JEPs)

> GraalVM looks very amazing. but it do not have the long term development roadmap.
> There is no strong community guidelines. code conduct .
> Only oracle itself can know what will happened.

I don't believe those statements reflect what is happening in the project very accurately. There is certainly a large non-Oracle community involved in the project and we are all doing our best to work together (with Oracle) as a community and to create the capabilities we jointly need.

Ironically, people used to say much the same things about OpenJDK some years ago when community involvement was still growing (and it was probably not really correct then either).

Graal is an open source project. The way to ensure that the project does not end up as you describe is to do what was done with OpenJDK: find ways to contribute, add significant value, steer the project in the direction you want it to go by making the things you need actually happen rather than complaining or asking someone to do them for you, make sure you allow for everyone's needs rather than just your own, find a win-win.

Codes of conduct and guidelines don't make any of that happen, they reflect the fact that it is already happening. Likewise, trying to shoehorn Graal into another project is not going to remove or change the need to do all those things.
