### ISSUE TITLE
Windows 10 failed to install llvm-toolchain component.

### ISSUE THREAD

**Issue by netroby** [oracle/graal#2539]
OS: Windows 10 x64  2004 version
```
PS D:\soft\graalvm-ce-java8-20.1.0\bin> .\gu.cmd install native-image
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
Installing new component: Native Image (org.graalvm.native-image, version 20.1.0)
PS D:\soft\graalvm-ce-java8-20.1.0\bin> .\gu.cmd install llvm-toolchain
Downloading: Component catalog from www.graalvm.org
Error: Unknown component: llvm-toolchain
```

After download graalvm-ce-java8-20.1.0, try to install llvm-toolchain. but it said unknown component.

As you can see , we success installed the native-image component. but why not success install llvm-toolschain.

**Comment by Tracker09** [comment]
Same issue here for me

**Comment by zapster** [comment]
Hello and thanks for the report! Currently, the component is not available on Windows so the error you are seeing is actually the expected behavior. May I ask what you plan to do with the `llvm-toolchain`? There are two features in GraalVM that currently use it. First for compiling C/C++ code to bitcode for running on the GraalVM LLVM runtime and second as a backend for native image. The LLVM runtime does not yet support Windows. AFAIK the llvm backend for native image is also Linux/macOS only at the moment (I'll try to get a more definite answer about that).

**Comment by loicottet** [comment]
The LLVM backend is also not supported on Windows, that is correct.

**Comment by TempleLin** [comment]
Any chance of supporting Windows in the future? It seems like a pretty crucial feature.

**Comment by MartinBalin** [comment]
GU could in the future print some info that given component is not available for particular version/platform/arch/JDK. This will require big changes to catalog so GU has this information.

**Comment by eat-the-red-pill** [comment]
```bash
$ gu -L install ./llvm-toolchain-installable-java17-linux-amd64-22.2.0.jar
Processing Component archive: ./llvm-toolchain-installable-java17-linux-amd64-22.2.0.jar
Installing new component: LLVM.org toolchain (org.graalvm.llvm-toolchain, version 22.2.0)
Installation of LLVM.org toolchain failed: /mnt/d/graalvm/graalvm-ce-java17/3rd_party_license_llvm-toolchain.txt: Operation not permitted
I/O error occurred: /mnt/d/graalvm/graalvm-ce-java17/3rd_party_license_llvm-toolchain.txt: Operation not permitted
```
here is WSL in windows 10.
`Linux LAPTOP-68ARNRIN 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
