### ISSUE TITLE
GraalVM CE downloads don't include src.zip files for Graal classes

### ISSUE THREAD

**Issue by adinn** [oracle/graal#2551]
Current GraalVM downloads (20.1 and earlier) include a host of Graal jars whose classes get linked into native images but does not also include source jars. Sources for all such classes are needed in order to be able to debug the native image. Without them debugging of the native image fails to find source files whenever it steps into substrate, sdk or compiler code.

n.b. for all relevant class jars in the classpath (e.g. path/to/foo.jar) the native image generator expects to find sources in a corresponding src.zip file sitting in the same directory as the jar file (e.g. path/to/foo.src.zip).

GraalVM version: 20.1
JDK version: jdk11/jdk8
OS: Linux
Architecture: x86_64/AArch64.

**Comment by gilles-duboscq** [comment]
After #2785 the Graal SDK and Truffle API sources are included in the standard builds. This is controlled by the `--sources=sdk:GRAAL_SDK,truffle:TRUFFLE_API` argument passed to `mx` during the build.

The case of SDK code should be resolved but the issue remains for the compiler and SVM code.
I think it's OK to add both `compiler:GRAAL` and `substratevm:SVM` to this list.

Note that in 11+, code that is included in the jimage lands in `lib/src.zip`. I guess native-image already knows to look there for debugging since that's also where the rest of the corelibs classes are.

**Comment by adinn** [comment]
@gilles-duboscq Thanks for pointing us at the --sources option. I think it would probably be useful to have `substratevm:SVM` in the list for GraalVM builds. If the compiler code is in lib/src.zip for those builds then the current debug source manager should find it. In mandrel builds we don't jlink the compiler code but we can add `compiler:GRAAL` to the --sources list to ensue the relevant sources are found. @zakkak what do you think.

**Comment by zakkak** [comment]
> I think it would probably be useful to have `substratevm:SVM` in the list for GraalVM builds. If the compiler code is in lib/src.zip for those builds then the current debug source manager should find it.

I agree

> In mandrel builds we don't jlink the compiler code but we can add `compiler:GRAAL` to the --sources list to ensue the relevant sources are found. @zakkak what do you think.

We actually do this already (not through `--sources` though so the sources end up next to the jars instead of inside src.zip)

```
$ ls /opt/jvms/mandrel-java11-20.1.0.1.Final/lib/jvmci/     
graal.jar  graal-sdk.jar  graal-sdk.src.zip  graal.src.zip
```

I gave `GraalVM CE 20.3.0-dev-20200924_0204` a spin with:
```
./bin/native-image -g -H:Log=NativeBootImage:3 -Dgraal.LogFile=log.out --no-fallback Main && grep "Failed to" log.out
```

And it fails to find both `com.oracle.svm.*` and `org.graalvm.compiler.*` sources, so I think we need to add both `substratevm:SVM` **and** `compiler:GRAAL`.

**Comment by ansalond** [comment]
Fixed by https://github.com/oracle/graal/commit/bb1becf3a8eb2e8daab024acbf5261d7e964072f.

**Comment by zakkak** [comment]
Thank you @ansalond
