### ISSUE TITLE
[gu] Cannot debug Graal Updater

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2582]
Adding the usual `--vm.Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y` does not seem to work for the `gu` tool. It fails, wrongly insisting that `--vm.Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y` does not start with `--vm.X`:

```
$ bin/gu --vm.Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y available
Unrecognized vm option: '--vm.Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y'. Such arguments should start with '--vm.D', '--vm.XX:', or '--vm.X'
[1]    45732 exit 1     bin/gu --vm.Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y
```

*Tested with GraalVM CE 20.1.0 on macOS.*

**Comment by fniephaus** [comment]
This also seems to be odd and related:
```
$ bin/gu -d available
Unrecognized argument: '-d'. Use --help for usage instructions.
[1]    45800 exit 2     bin/gu -d available
$ bin/gu --debug available
Downloading: Component catalog from www.graalvm.org
...
```

**Comment by fniephaus** [comment]
I forgot to add `--jvm` to my initial command. Nonetheless, the error message is confusing.
This works:
```
bin/gu --jvm --vm.Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y available
```

**Comment by sdedic** [comment]
`--vm.Xrunjdwp` would probably have no effect anway since `gu` is AOTed binary built by native-image, that does not support debugging protocol. Will investigate why the message is printed - maybe the tools should print an error to alert the user things like `agentlib` or `Xrundjwp` are supported just in `jvm` mode.

re `-d`; the proper flag is `-e` (exceptions), another typo (in help screen); globals flags are not covered by tests yet, command flags are; will add testcase to ensure consistency

**Comment by gilles-duboscq** [comment]
The error message should now be more helpful edb4bb919f91271706aa2f01c23c2e4bec9ca459

**Comment by fniephaus** [comment]
Thanks, @gilles-duboscq!
