### ISSUE TITLE
Provide access to the application class path of the image that is currently built

### ISSUE THREAD

**Issue by christianwimmer** [oracle/graal#2600]
From within a `Feature` running at image build time, it is currently not possible to get the class path or module path of the application using proper API.

We should provide methods like this (exact list and signatures to be discussed):
* `List<Path> getClassOrModulePath()`: The value of the `-cp` or `-modulepath` options passed to `native-image`
* `boolean isModulePath()`: Whether the list is a class or module path
* `ClassLoader getApplicationClassLoader()`: Returns the class loader used for the classpath / modulepath.

The methods can either be in `FeatureAccess`, or in a separate class as `static` helper methods. I prefer `FeatureAccess` because the callers should be at a defined point in a `Feature` and not, e.g., at a random class initializer.

Why provide class and module path in the same method, and a boolean flag if distinction is necessary? Code that scans the path for, e.g., resources or classes likely works the same for class and module path, making it easier to support both.

Alternatives:
* Subclass and annotation information is currently available via non-API, but that is planned to be removed in https://github.com/oracle/graal/issues/2599
* The application class loader can also be queried by calling `getClassLoader()` on any known application class (like a `Feature` implementation class).

**Comment by olpaw** [comment]
> List<Path> getClassOrModulePath(): The value of the -cp or -modulepath options passed to native-image

Since --class-path and --module-path can be used in the same image build it is not either/or. We have to provide both
```
    List<Path> classpath();
    List<Path> modulepath();
```
On Java 8 `modulepath()` will simply always return the empty list.
On my modules branch I already have this abstracted from the specific `NativeImageClassLoader`:
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageClassLoaderShared.java
This needs to be made available on master and exposed via the `Feature` API.
