### ISSUE TITLE
GraalVM using almost 3x more memory than the standard JDK

### ISSUE THREAD

**Issue by newk5** [oracle/graal#2872]
I've created the most basic test and just noticed that GraalVM uses almost 3x more memory than a standard JDK. I'm unsure if this would be considered a bug or if it's just an accepted consequence of using GraalVM in non-native mode.

**Steps to reproduce the issue**
This is the code:

```java
public class Main {
    public static void main(String[] args) throws InterruptedException {
        System.out.println("Hello world"); 
        Thread.sleep(90000);
    }
}
```

**Describe GraalVM and your environment:**
 - GraalVM version: **graalvm-ce-java11-windows-amd64-20.2.0**
 - JDK major version: **11**
 - OS: **Windows 10**
 - Architecture: **64bit**

On JDK11 (AdoptOpenJDK) it's using 19.2mb (RSS) of memory and on GraalVM it's using 50.4mb, it's more than double, almost triple the amount. Is this normal?

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this issue, we will take a look into it.

**Comment by dougxc** [comment]
The extra space is probably mostly due to libgraal. It will be the memory used for mmapping `jvmcicompiler.dll` as well as for allocating the libgraal heap. In addition, the mmapped cost of the C2 compiler (part of `jvm.dll`) is paid even though C2 is not use (by default) in GraalVM.
In GraalVM EE as of 20.2, libgraal is unloaded when compilation becomes idle.

**Comment by oubidar-Abderrahim** [comment]
@dougxc do you think we need to do something regarding this issue? or should we close it?

**Comment by dougxc** [comment]
Close it. As state, recovery of RSS memory is a feature available in GraalVM EE.
