### ISSUE TITLE
External LLVMGlobal $ss23_ContiguousArrayStorageCMn cannot be found

### ISSUE THREAD

**Issue by libin049** [oracle/graal#2905]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.2**
 - CE or EE: **CE**
 - JDK version: **JDK8**
 - OS and OS Version: **ubuntu16.04**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`: 
```
 **OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (25.262-b10-jvmci-20.2-b03) for linux-amd64 JRE (1.8.0), built on Jul 21 2020 14:22:18 by "buildslave" with gcc 7.3.0**
```

**Describe the issue**
java call swift failed
- java file: Polyglot.java
- swift file: hello.swift

error messages is 
```
Exception in thread "main" External LLVMGlobal $ss23_ContiguousArrayStorageCMn cannot be found.
	at <llvm> null(Unknown)
	at org.graalvm.polyglot.Context.eval(Context.java:345)
	at Polyglot.main(Polyglot.java:10)
```

**Code snippet or code repository that reproduces the issue**
Polyglot.java is:
```java
import java.io.*;
import org.graalvm.polyglot.*;

class Polyglot {
    public static void main(String[] args) throws IOException {
        Context polyglot = Context.newBuilder().
                                       allowAllAccess(true).build();
        File file = new File("hello.bc");
        Source source = Source.newBuilder("llvm", file).build();
        Value cpart = polyglot.eval(source);
        System.out.println(cpart.canInvokeMember("$s5hello6getArrSaySiGyF"));
        System.out.println(cpart.invokeMember("$s5hello6getArrSaySiGyF"));
    }
}
```
hello.swift is:
```swift
func getArr()->[Int] {
  return [1,2,3,4,5]
}
```
**Steps to reproduce the issue**
steps:
1. ```swiftc hello.swift -emit-bc -O```
2.  ```javac Polyglot.java```
3. ```java Polyglot```

**Expected behavior**
print the array `[1,2,3,4,5]`

**Comment by oubidar-Abderrahim** [comment]
Looks like it's not finding some runtime library. It's probably implicitly linking against some swift library, and we don't see that. So the problem here is that bitcode files don't have a way of recording library dependencies. One solution is to find out what library it needs, and manually load it with the` llvm.libraries` option.
The better solution is to not use bitcode files, but ELF files with embedded bitcode in them. Then everything works out of the box. We have a patched toolchain for C/C++ that does this automatically, but for Swift, this would be a manual compile step. But I don't know swift well enough to know how to do that...

You may wanna check : https://medium.com/graalvm/graalvm-llvm-toolchain-f606f995bf for ideas

**Comment by oubidar-Abderrahim** [comment]
I am closing this issue. If you still need assistance you can reopen it
