### ISSUE TITLE
Will GraalVM support cross compiling in future?

### ISSUE THREAD

**Issue by UltraBurstXD** [oracle/graal#2931]
Hi,
I'm using GraalVM recently on my projects and I think it's cool. The programs uses less memory footprint, are smaller and blazing fast when compared to recently packing tool reintroduced in Java 14, **jpackage** with Hotspot JIT. But just like the previously mentioned tool, from what I recently saw **Native Image** only can target the host OS and what about Cross compiling with AOT? Will that any time soon or future  be available or possible? It would be more cooler if that was possible.

**Comment by oubidar-Abderrahim** [comment]
Hi,
I am afraid what you're expecting is next to impossible. A native image is nothing more than an executable program, having an executable that can be executed on any platform means you need to include all possible libraries you're going to need, thus you'll end up with something huge, a few dozens of Gigabytes and maybe more. and to my knowledge no other software has attempted to create an executable that can be run anywhere.
On the other hand, if having a cross platform application is the objective, well, Java is a cross-platform language. So, as long as you have a GraalVM installation on your machine you can use it as a JVM to run your Java program on top of it and it will run everywhere with the benefits of the GraalVM Compiler (low memory consumption, faster execution...)

**Comment by solvingj** [comment]
Several interesting things are technically possible, although this is not to say it's possible, feasible, or a priority for graalvm project.

First, golang can cross compile a native binary from any supported platform to any platform, because the language does not depend on glibc or msvc. It was a massive project to make it this way, but they did it. 

Second, a brilliant group of projects and research exist here, which demonstrates the possibility of making a single native executable which runs on all three major platforms (and others).

https://github.com/jart/cosmopolitan

Based on the concepts proven and explained here:

https://justine.lol/ape.html

Just food for new thought since graalvm in many ways represents ongoing research.

**Comment by DerekV** [comment]
> Hi, I am afraid what you're expecting is next to impossible. [...] having an executable that can be executed on any platform [...]

I'm lost .. That isn't what cross-compiling even means.  It means making an executable that only runs on one platform (native), but doing the compilation work on another platform.
It usually requires having files from the target system on the compiling system for linking purposes but otherwise there is not intrinsic relationship between the system that an executable targets and a system where it is compiled.

**Comment by DerekV** [comment]
This issue is redundant with https://github.com/oracle/graal/issues/407 anyways.

**Comment by NCLnclNCL** [comment]
.

**Comment by DaveJarvis** [comment]
> Hi, I am afraid what you're expecting is next to impossible. A native image is nothing more than an executable program, having an executable that can be executed on any platform means you need to include all possible libraries 

Have you seen APE?

- https://justine.lol/ape.html
- https://github.com/jart/cosmopolitan
