### ISSUE TITLE
[native-image] Agent fails to detect reflective instantion of Arrays-Float.

### ISSUE THREAD

**Issue by njrkay** [oracle/graal#3103]
**Describe the issue**
Hi On working with Apache's `BeanUtils.copyProperties(src, dest)` for copying the bean properties & found below error with Native image. The below error is generated during Runtime.
`Class java.lang.Float[] is instantiated reflectively but was never registered`

**GraalVM and your environment:**
 - GraalVM version **20.2**
 - JDK major version: **11.0.8**
 - OS: **Linux**
 - Architecture: **AMD64**
 - Quarkus: **1.8.1.Final**

**Additional Details**
Using `mvn clean install package -Pnative` to build native-image

**_pom.xml_** - BeanUtils dependency.
```
<dependency>
	<groupId>commons-beanutils</groupId>
	<artifactId>commons-beanutils</artifactId>	
	<exclusions>
	    <exclusion>
		     <groupId>commons-logging</groupId>
  	   	    <artifactId>commons-logging</artifactId>
	   </exclusion>
	</exclusions>		
</dependency>
```
**Stack Trace**
```
[java.lang.IllegalArgumentException: Class java.lang.Float[] is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection, 
at com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.arrayHubErrorStub(SubstrateAllocationSnippets.java:274), 
at org.apache.commons.beanutils.ConvertUtilsBean.registerArrayConverter(ConvertUtilsBean.java:796), 
at org.apache.commons.beanutils.ConvertUtilsBean.registerArrays(ConvertUtilsBean.java:766), 
at org.apache.commons.beanutils.ConvertUtilsBean.deregister(ConvertUtilsBean.java:603), 
at org.apache.commons.beanutils.ConvertUtilsBean.<init>(ConvertUtilsBean.java:161), 
at org.apache.commons.beanutils.BeanUtilsBean.<init>(BeanUtilsBean.java:113), 
at org.apache.commons.beanutils.BeanUtilsBean$1.initialValue(BeanUtilsBean.java:64), 
at org.apache.commons.beanutils.BeanUtilsBean$1.initialValue(BeanUtilsBean.java:60), 
at org.apache.commons.beanutils.ContextClassLoaderLocal.get(ContextClassLoaderLocal.java:154), 
at org.apache.commons.beanutils.BeanUtilsBean.getInstance(BeanUtilsBean.java:76), 
at org.apache.commons.beanutils.BeanUtils.copyProperties(BeanUtils.java:135)
```

Similar to issue- #1794

**Comment by mcraj017** [comment]
@njrkay thanks for reporting the issue
please provide the reproducer

**Comment by huw0** [comment]
I have found this issue through Google and am experiencing similar. Slightly newer environment than @njrkay , GraalVM `20.3`, Quarkus `1.11.0.Final`.

This brings in the latest `1.9.4` version of commons-beanutils.

In my case I have a class for conversion that calls BeanUtils.

```
    private void convert(final Object source, final Object target) {
        try {
            BeanUtils.copyProperties(target, source);
        } catch (IllegalAccessException | InvocationTargetException e) {
            throw new BeanConversionException(e);
        }
    }

    public <T> T convert(final Object source, final Class<T> clazz) {
        T target;
        try {
            target = clazz.getDeclaredConstructor().newInstance();
        } catch (final Exception e) {
            throw new BeanConversionException(e);
        }

        convert(source, target);

        return target;
    }
```

The types for clazz are two different implementations of an interface. Reflection for these implementations have been configured through `-H:ReflectionConfigurationFiles`.

In my case, I'm seeing the error for Boolean[] rather than Float[].

**Comment by mcraj017** [comment]
@huw0 Please provide the full reproducer

**Comment by mcraj017** [comment]
@huw0 please try the latest GraalVM 21.0.0 release 
and if still, the issue persists then provide the reproduce

**Comment by mcraj017** [comment]
@huw0 please let us know if the latest release works, if it doesn't then please reopen the issue

**Comment by Shpota** [comment]
We have this issue on GraalVM 21.1.0 (which is used in Quarkus 2.0.1).  Unfortunately I couldn't reproduce it on a test project, but it is constantly reproducible on our code base (which we cannot share). In our case it fails on reading a JSON with Jakson when calling `com.fasterxml.jackson.databind.ObjectMapper#readValue(java.lang.String, java.lang.Class<T>)` form a Kotlin coroutine context. The class which is referenced as of array type (like `Event[]`) actually never appears as an array in the input JSON, neither is it used in collections.

**Comment by kutzhang** [comment]
Still not works, my ENV is:

    GraalVM version 21.3.0
    JDK major version: 17.0.1
    OS: MacOS
    Quarkus: 2.6.2.Final

**Comment by ygyg70** [comment]
Had the same issue, root cause is that org.apache.commons.beanutils.ConvertUtilsBean will register many types for array conversions.
Adding this to reflection-config.json addresses seems to work:
`
{ "name": "boolean[]","unsafeAllocated": true },
{ "name": "byte[]","unsafeAllocated": true },
{ "name": "char[]","unsafeAllocated": true },
{ "name": "double[]","unsafeAllocated": true },
{ "name": "float[]","unsafeAllocated": true },
{ "name": "int[]","unsafeAllocated": true },
{ "name": "long[]","unsafeAllocated": true },
{ "name": "short[]","unsafeAllocated": true },
{ "name": "java.math.BigDecimal[]","unsafeAllocated": true },
{ "name": "java.math.BigInteger[]","unsafeAllocated": true },
{ "name": "java.lang.Boolean[]","unsafeAllocated": true },
{ "name": "java.lang.Byte[]","unsafeAllocated": true },
{ "name": "java.lang.Character[]","unsafeAllocated": true },
{ "name": "java.lang.Double[]","unsafeAllocated": true },
{ "name": "java.lang.Float[]","unsafeAllocated": true },
{ "name": "java.lang.Integer[]","unsafeAllocated": true },
{ "name": "java.lang.Long[]","unsafeAllocated": true },
{ "name": "java.lang.Short[]","unsafeAllocated": true },
{ "name": "java.lang.String[]","unsafeAllocated": true },
{ "name": "java.lang.Class[]","unsafeAllocated": true },
{ "name": "java.util.Date[]","unsafeAllocated": true },
{ "name": "java.util.Calendar[]","unsafeAllocated": true },
{ "name": "java.io.File[]","unsafeAllocated": true },
{ "name": "java.sql.Date[]","unsafeAllocated": true },
{ "name": "java.sql.Time[]","unsafeAllocated": true },
{ "name": "java.sql.Timestamp[]","unsafeAllocated": true },
{ "name": "java.net.URL[]","unsafeAllocated": true }
`
