### ISSUE TITLE
Using com.oracle.truffle.api classes causes ServiceConfigurationError

### ISSUE THREAD

**Issue by blazingkin** [oracle/graal#311]
I'm trying to convert a language to using Truffle.

After much effort, I finally have the graalvm working. I can use the org.graalvm.polyglot package, and when I do `Engine.newBuilder().build().getLanguages()` returns the list that I'd expect (R, js, python, etc...).

However, when I try to use any Truffle class (in com.oracle.truffle.api), I get the following exception

```
Exception in thread "main" java.util.ServiceConfigurationError: com.oracle.truffle.api.TruffleRuntimeAccess: Provider org.graalvm.compiler.truffle.runtime.hotspot.HotSpotTruffleRuntimeAccess not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
```

My JAVA_HOME is set to a labsjdk, and I'm using a graalvm java.

It seems like Truffle hasn't been updated to use the newer org.graalvm.polyglot package?

Am I missing something else?

**Comment by chumer** [comment]
Could you please provide the command line you are using to run your application?

LabsJDK is a JVMCI enabled JDK that is the basis for GraalVM. So GraalVM already contains the LabsJDK. 

If you use GraalVM then everything is setup by default (you won't need LabsJDK). GraalSDK with the polyglot API to interact with guest language from your applications is already on the bootclasspath. Truffle and Truffle languages and tools are on by default but are isolated in separate classloader.  This is intentional so implementation details of the language cannot propagate into the application.  So in order to make your language discoverable by the polyglot API you can either drop them in `graalvm/jre/languages/yourlanguage` or you can add your language jar to the truffle classpath using `-Dtruffle.class.path.append=yourlanguage.jar`. You should not add GraalSDK or Truffle to the application classpath on GraalVM manually, as that will duplicate certain classes that are already classpath and might lead to problems like you are seeing. The isolation has the consequence that, by default, you can only use the polyglot API and no Truffle APIs from your application classpath.

Did you have a look at our SimpleLanguage repo already? Its designed to get external language implementations started more quickly:
https://github.com/graalvm/simplelanguage/

Currently its still on 0.28, but it will be updated to 0.31 this week.

**Comment by blazingkin** [comment]
I'm using eclipse, but it should be equivalent to:
`/path/to/graal/bin/java -jar blz-ospl.jar`

From your explanation, it seems like my issue might be that I listed Truffle as a maven dependency so maven may be adding it to my classpath.

If that is the case, how am I supposed to create a jar with missing dependencies?

**Comment by chumer** [comment]
Unfortunately the SimpleLanguage repo is still on 0.28. 
For 0.31 you will need something like [this](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.sl.launcher/src/com/oracle/truffle/sl/launcher/SLMain.java) for your main.

For running the language needs to be split into two parts. One is the launcher and one the language implementation. The language implementation needs to be added using `-Dtruffle.class.path.append=blz.jar`. The launcher can be on the normal classpath and use the polyglot API.

If you want to access Truffle and language implementation classes from your application classpath, for e.g. testing (when running with maven) you can do so with `-XX:-UseJVMCIClassLoader` like the [sl launcher](https://github.com/graalvm/simplelanguage/blob/master/sl#L27) currently does (which we hope to eliminate with the 0.31 update).  

All of this applies only when your language runs on GraalVM. When running on HotSpot you can drop all the libs on the normal classpath, but it won't be fast as it cannot use Graal partial evaluation of the interpreter code.

From looking at your repo. Migrating existing languages to Truffle where most code was not designed for partial evaluation, can be a major effort. I think this applies to your language implementation. Don't expect it to be any faster from the start. This is said to manage your expectations. You might still be able to benefit out of the box, by running your non-Truffle Java interpreter on GraalVM. As Graal is also compiling your Java code to more efficient machine code.

This is very valuable feedback to us. Seems we have some more work to do to make external language integration easier. Thanks for your patience.

**Comment by smarr** [comment]
@blazingkin Interesting work, thanks for the link.

I just had a brief cursory look around, and found for instance: https://github.com/blazingkin/blz-ospl/blob/experimental-graal/src/com/blazingkin/interpreter/executor/executionstack/RuntimeStack.java

Looks like you'll probably need to rethink much of the related code to work well with Truffle.
The run-time stack is provide based on [VirtualFrame](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/frame/VirtualFrame.java#L28)s. For ideal performance, this would mean to will likely need to think about how to map your information onto frames.

As a side note, I haven't looked to closely, but `java.util.Stack` is synchronized, if I am not mistaken. You might not need this for stacks that are accessible only by one thread.

If you are looking for more high-level feedback, perhaps you could outline a little how your language works on the graal-dev mailing list, and we might be able to point you at relevant implementation strategies used in other languages.

**Comment by blazingkin** [comment]
Thanks so much! I've got the configuration working. Now I just have to implement it 😆.

I'm definitely expecting to have to change quite a few things to get it to be performant, but that's much better than trying to write a compiler / optimizer by myself.

I'll definitely use the graal-dev mailing list going forward.
