### ISSUE TITLE
OracleJDK8  - Dependencies for GraalVM

### ISSUE THREAD

**Issue by kdesineedi** [oracle/graal#3131]
Hi ,

I am trying to use GraalVM on a stock JDK (version OracleJDK8) On top of this I am trying to use this within an OSGI container.

It is failing with the below error:
osgi.ee; (&(osgi.ee=JavaSE)(version=9.0))

The versions I am using are:

                   <dependency>
			<groupId>com.ibm.icu</groupId>
			<artifactId>icu4j</artifactId>
			<version>64.2</version>
		</dependency>

		<dependency>
			<groupId>org.graalvm.sdk</groupId>
			<artifactId>graal-sdk</artifactId>
			<version>20.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.graalvm.js</groupId>
			<artifactId>js</artifactId>
			<version>20.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.graalvm.js</groupId>
			<artifactId>js-scriptengine</artifactId>
			<version>20.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.graalvm.truffle</groupId>
			<artifactId>truffle-api</artifactId>
			<version>20.3.0</version>
		</dependency>

Could you please suggest what versions of the above should I use or the minimum version of Java I need for GraalVM to be used   should be higher than Oracle Java 8 on a Stock JDK? Kindly note I cannot use Open JDK.

Upgrading Java above 8 is not feasible this year but could be an opportunity for next year based on the current project constraints.

**Comment by mcraj017** [comment]
@kdesineedi Please provide the reproducer

**Comment by kdesineedi** [comment]
Hi @mcraj017 

Please find the sampler attached and kindly follow the steps below.Please note I need to embed all GraalVM jars as per the dependencies but I have just embedded one as an example to illustrate the issue.

Hoping you can provide or guide with steps for the resolution at the earliest.

Once you unzip
Go to \sampler
Run mvn clean install
Check the generated Jar (OSGI bundle) under bundle/target 
Navigate to META-INF/MANIFEST.MF
Observe : Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)**(version=9.0)**)
[sampler.zip](https://github.com/oracle/graal/files/5871153/sampler.zip)

Now edit the sampler/bundle/pom.xml line 36 - remove graal-sdk from the <Embed-Dependency> tag
Follow the above steps and you will see the below in the new bundle's MAINFEST.MF
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)**(version=1.8)**)"

**javac -version**

javac 1.8.0_131

**java -version**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**mvn -version**

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Java version: 1.8.0_131, vendor: Oracle Corporation
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

**Comment by wirthi** [comment]
Hi @kdesineedi,

We have some documentation around running on a Stock JDK with adding the GraalVM libraries as dependencies in https://www.graalvm.org/reference-manual/js/RunOnJDK/ - We are currently updating this documentation with further clarifications, should show up by the end of the week.

Note, however, that we strongly discourage using stock JDK8. On JDK8, it is not possible to use the GraalVM compiler to optimize your JavaScript execution. The performance of your (JavaScript) application will be quite slow, you can expect a slowdown of around 20X compared to running the same application on GraalVM (or on JDK11+ with the GraalVM compiler enabled).

**The suggestion option is to use GraalVM JDK8**, instead of your current JDK8 - that should be as easy as [downloading the GraalVM JDK8 build](https://www.graalvm.org/downloads/) and updating your `$PATH`.

I cannot help you with the core OSGi problem - I have no experience with that, sorry.

Best,
Christian

**Comment by kdesineedi** [comment]
Thanks @wirthi for your details ..awaiting @mcraj017 response as well if there are any inputs on OSGI issue

**Comment by mcraj017** [comment]
@kdesineedi as suggested by @wirthi 

I have tried GraalVM java 8 instead of GraalVM dependencies and got 
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
so you can use GraalVM java 8 instead of OracleJDK8

**Comment by kdesineedi** [comment]
Hi  @wirthi so is it safe to conclude that GraalVM is not supported/recommended on OracleJDK8?

@mcraj017 When you use the sampler you saw the required capability to be 9.0 and not 1.8? Right? 

( i meant on java version "1.8.0_131")

**Comment by wirthi** [comment]
@kdesineedi 

_GraalVM_ is a full Java VM. It is a drop-in replacement for OracleJDK8. You cannot use it _in_, but _instead of_ it.

What you are trying to achieve is to reuse only one single specific component of GraalVM - the JavaScript interpreter - outside of GraalVM, on a different JVM. This is technically possible: the JavaScript interpreter is a plain Java application that will run on any Java VM. However, for good performance, you will need to run it in combination with another of GraalVM's compoments: the GraalVM optimizing compiler. And this one _cannot_ be dropped in as a plugin to a JDK8.

As described in https://www.graalvm.org/reference-manual/js/RunOnJDK/ you have two options:
- Use our GraalVM JDK8 build instead of your OracleJDK.
- Use an Oracle/OpenJDK of version 11+ where you can configure the GraalVM compiler as component

Best,
Christian

**Comment by kdesineedi** [comment]
Thanks Christian!!

cc: @wirthi
