### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by tommasobenatti** [oracle/graal#3233]
**Describe the issue**
Cannot tell

**Steps to reproduce the issue**
cannot tell

**Describe GraalVM and your environment:**
 - GraalVM version `GraalVM Community 21.0.0.2`
 - JDK major version: **[11]**
 - OS: **[Ubuntu Server 18.04.5]**
 - Architecture: **[AMD64]**

**More details**
https://pastebin.ubuntu.com/p/TsSZCCFRZz/ (is the full crash log)

**Comment by oubidar-Abderrahim** [comment]
@tommasobenatti To open an issue to GraalVM, you need to provide a description of the issue, paste the error logs in the issue and provide steps to reproduce. 
Since this issue does not respect any of that, it will be closed.
Please create a new issue respecting the above requirement and we will gladly review it and provide assistance. Thank you.
