### ISSUE TITLE
native-image bash launcher reports different version than native binary

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#3313]
**Describe the issue**
A recent master build from source, revision 32645548c1f3d09a7a077084fb530d6b8061b5e6, produces different versions for bash launchers vs. a produced native via `--macro:native-image-launcher`.

Bash launcher:
```
$ native-image --version
11.0.9+10-jvmci-21.0-b02 (Java Version 11.0.9+10-jvmci-21.0-b02)
```

Native launcher:
```
$ native-image --version
GraalVM 21.1.0-dev Java 11 CE (Java Version 11.0.9+10-jvmci-21.0-b02)
```

**Steps to reproduce the issue**
1. Produce a native image with a bash launcher:
```
$ mx --primary-suite substratevm --java-home $JAVA_HOME native-image HelloWorld
$./substratevm/svmbuild/vm/bin/native-image --version
11.0.9+10-jvmci-21.0-b02 (Java Version 11.0.9+10-jvmci-21.0-b02)
```
2. Produce a native image binary for the launcher and try again
```
$ ./substratevm/svmbuild/vm/bin/native-image --macro:native-image-launcher
$./substratevm/svmbuild/vm/bin/native-image --version
[...]
GraalVM 21.1.0-dev Java 11 CE (Java Version 11.0.9+10-jvmci-21.0-b02)
```
 
**Describe GraalVM and your environment:**
 - GraalVM version: master revision  32645548c1f3d09a7a077084fb530d6b8061b5e6
 - JDK major version: 11
 - OS: Linux
 - Architecture:  x86_64

**More details**
This looks to be caused by https://github.com/oracle/graal/commit/bcf982c95c1955f25c2bdf13b8996fed8a26911d

**Comment by jerboaa** [comment]
@olpaw Is this intentional? If so what's the recommendation to produce similar version output for bash launchers?

**Comment by olpaw** [comment]
> @olpaw Is this intentional? If so what's the recommendation to produce similar version output for bash launchers?

Yes. This is intentional. Only if you build a native-image **image** you will get reported `GraalVM 21.1.0-dev Java 11 CE (Java Version 11.0.9+10-jvmci-21.0-b02)` because that is what that image then actually is (the driver executable image produced by GraalVM 21.1.0-dev Java 11 CE). If you run the driver as an ordinary JVM application (i.e. via bash/cmd-launcher) it will now report running as such. See https://github.com/oracle/graal/blob/205f6ef0cf8b12ca39b5bcde83d804428df78c3e/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java#L84

**Comment by jerboaa** [comment]
OK, thanks!

**Comment by zakkak** [comment]
> Yes. This is intentional. Only if you build a native-image **image** you will get reported `GraalVM 21.1.0-dev Java 11 CE (Java Version 11.0.9+10-jvmci-21.0-b02)` because that is what that image then actually is (the driver executable image produced by GraalVM 21.1.0-dev Java 11 CE). If you run the driver as an ordinary JVM application (i.e. via bash/cmd-launcher) it will now report running as such.

Hi @olpaw ,

I am still a bit confused about this. In the case of tha bash-launcher we have a bash script that starts the Java application `com.oracle.svm.driver.NativeImage` so passing `--version` to it should print the version of that application and not the version of the JVM (or at least not only that).
Furthermore, I would expect `java MyApp --version` to give the same result as `native-image MyApp && myapp --version`.

My understanding is that there is a need to differentiate the bash launcher from the native launcher through `--version`, but the current state breaks the Mandrel distribution which ships with a bash launcher instead of a native image and we thus need a way to get the version of the `native-image` from the bash launcher as well.

Now, I understand that the native image driver is part of GraalVM and thus it doesn't have its own version, but we could say that it inherits its version from the GraalVM distribution it is part of. In that sense would something like
`native-image 21.1.0-dev (Java Version 11.0.9+10-jvmci-21.0-b02)`  make sense as the output of the bash launcher's `--version`?

Could you please re-open this issue or should we open a new one making this a feature request?

Thanks

**Comment by olpaw** [comment]
We use `System.getProperty("java.vm.version")` because for us the driver is always shipped as image. The bash/cmd-launcher for us are only intermediate ways of using native-image (bootstrapping). If you need a custom `--version` output for your usecase of always running the driver via launcher please provide a PR that adds this. E.g. you could add something like
```java
case "--version":
    args.poll();
    singleArgumentCheck(args, headArg);
    String message = System.getProperty("java.vm.version");
    if (NativeImage.IS_AOT) {
        message = System.getProperty("java.vm.version");
    } else {
        message = "native-image " + NativeImage.graalvmVersion;
    }
    String message = System.getProperty("java.vm.version");
    message += " (Java Version " + javaRuntimeVersion + ")";
    nativeImage.showMessage(message);
    System.exit(0);
```

**Comment by jerboaa** [comment]
This has been addressed with https://github.com/oracle/graal/pull/3329
