### ISSUE TITLE
targetMappings was assigned twice in the HostAccess.Builder(HostAccess access)

### ISSUE THREAD

**Issue by tangjfn** [oracle/graal#3481]
class Builder {
...
Builder(HostAccess access) {
this.accessAnnotations = copySet(access.accessAnnotations, Equivalence.IDENTITY);
this.excludeTypes = copyMap(access.excludeTypes, Equivalence.IDENTITY);
this.members = copySet(access.members, Equivalence.DEFAULT);
this.implementationAnnotations = copySet(access.implementableAnnotations, Equivalence.IDENTITY);
this.implementableTypes = copySet(access.implementableTypes, Equivalence.IDENTITY);
// first asign
this.targetMappings = access.targetMappings != null ? new ArrayList<>(access.targetMappings) : null;
this.excludeTypes = access.excludeTypes;
this.members = access.members;
// bug here, second asign
this.targetMappings = access.targetMappings;
...
}

**Comment by oubidar-Abderrahim** [comment]
Hi,

Thank you for reporting this, Unfortunately, the issue as it is now is unreadable and we cannot provide much assistance like this.

Could you please specify the following things:

1. What is the context of your application?
2. What is the full stacktrace of the error you face?
3. What version of GraalVM you're using (21.1.0? EE or CE? java 8 or 11)?
4. What OS you're using?
5. Can you please provide a small example that can allow me to see and debug this issue?

The more details you provide the easier it will be to assist, debug and fix this issue. Thank you for your understanding

**Comment by tangjfn** [comment]
master: graal/sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/HostAccess.java
line number: 589
this.targetMappings has been assigned twice
GraalVM 21.1.0

**Comment by oubidar-Abderrahim** [comment]
Thank you for you report, we will fix this shortly

**Comment by oubidar-Abderrahim** [comment]
@chumer We have a field that was assigned twice in `HostAccess.builder(HostAccess access)` the first assignment was in line [586](https://github.com/oracle/graal/blob/c656cf921a39eb73f96ff1edef12b85eaeeb5b7f/sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/HostAccess.java#L586) and the second is in line [589](https://github.com/oracle/graal/blob/c656cf921a39eb73f96ff1edef12b85eaeeb5b7f/sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/HostAccess.java#L589) 
I can create a PR for this, but we might want to add this to another PR to avoid running gates multiple times since it's a small change.
