### ISSUE TITLE
NativeImage size overflow

### ISSUE THREAD

**Issue by agibsonccc** [oracle/graal#3486]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Build any image where  the heap is big enough to cause an overflow in the NativeImageLoader

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]** Nightlies
 - JDK major version: **[e.g.:8]** 8
 - OS: **[e.g. macOS Catalina]** Linux
 - Architecture: **[e.g.: AMD64]** AMD64

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.

```java
tal error:com.oracle.svm.core.util.VMError$HostedError: java.lang.NegativeArraySizeException
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:685)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:497)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.NegativeArraySizeException
        at com.oracle.svm.hosted.image.RelocatableBuffer.<init>(RelocatableBuffer.java:51)
        at com.oracle.svm.hosted.image.NativeImage.build(NativeImage.java:463)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:674)
        ... 6 more
```

**Comment by mcraj017** [comment]
@agibsonccc can you please try GraalVM-ce-JAVA-11 and let us know the results

**Comment by agibsonccc** [comment]
@mcraj017  this also happens on java 11. What I've noticed to keep the image size small enough (below 2 billion) I needed to strip down the number of resources I bundled. That helps keep it from overflowing.

**Comment by adinn** [comment]
@mcraj017 I'm sure this has nothing to do with the JDK in use.

The image creation code lays out various of the pre-generated image section contents using RelocatableBuffer. This class stores its content in a ByteBuffer. In consequence it can only construct sections with lengths that fit into a Java int. If a build time inited static field references an int[] array whose length is anywhere near MAXINT then that array wiil occupy almost all the space in the associated ByteBuffer. So, you are almost certainly not going to be able to lay out the rest of the initial heap without overflowing the available space.

Fixing this will require some fairly wide-spread changes to the image creation code. It is probably not difficult to do but it is certainly going to be laborious and tricky to work the required changes through all affected code.

I'm not offering to do it btw  -- just explaining what is involved ;-)

**Comment by agibsonccc** [comment]
@adinn yeah that reflects my understanding as well. The workaround for me was just to scale down the number of resources in use. In our case, we have a ton of native libs that get loaded on top of classes and it was causing an overflow in the RelocatableBuffer.

**Comment by johanvos** [comment]
I notice that there is a call to `safeToInt(long v)` in RelocatableBuffer that is applied to convert the long to int.
Its implementation will assert on `isInt(v)` but with assertions disabled, this will totally fail.
I think it would be better to do a check and throw a friendly exception (which would save developers running into this lots of time).

**Comment by agibsonccc** [comment]
I agree with @johanvos - if this can be a documented limitation with a helpful error message, I would be fine with that.
I've found when tuning native image creation that as long as you keep the heap size near where it needs to be (no excess heap) and only add what resources you need it's fine.

In my case, the build used about 12g of RAM and output a 1.9g image at the end.
Most of what goes in there for us is native resources using https://github.com/bytedeco/javacpp - if you download the jars for some of the https://github.com/bytedeco/javacpp-presets you'll see some fairly sizable jars there.

I'd expect this to be an edge case.

**Comment by mcraj017** [comment]
@adinn and @johanvos thanks for your inputs

**Comment by mcraj017** [comment]
@agibsonccc we have added the information in our documentation 
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/MemoryManagement.md#serial-garbage-collector

**Comment by agibsonccc** [comment]
@mcraj017 this doesn't remotely address the root problem, nor the underlying feature that needed to be implemented. This is not even close to a fix. @adinn mentioned that there would need to be a significant change to the underlying runtime to allow the native heap to be more than 2 billion objects. Documenting the limitation is fine, but I don't really see how documenting the different GC options available even helps address this.

**Comment by adinn** [comment]
> @adinn mentioned that there would need to be a significant change to the underlying runtime to allow the native heap to be more than 2 billion objects.

That's not exactly what I said. The limit is that an image cannot currently be created with a build-time initialised heap section containing more than 2 billion *bytes*. Apologies for being fussy but I like to ensure that reports of what I say are precise.

> @mcraj017 this doesn't remotely address the root problem, nor the underlying feature that needed to be implemented.

That is perhaps correct but I think you need to consider what you are asking for. It might well be possible to modify GraalVM Native to accommodate applications that start up with static data in the build-time generated heap whose total size exceeds 2 billion bytes. However, it would require a lot of rework to do so. I am not surprised that the initial response to your request has been to document the current limitation.

Why the lack of surprise? My understanding is that your problem is an extremely uncommon one. That is not to doubt its seriousness as far as your requriements are concerned. What I mean to note is that implementing what you are asking for implies a significant shift of resources away from the needs of the majority of users.

That's also not to say that you are just left high and dry with no way forward. The workaround for this sort of problem is for applications that need large amounts of static state to create and populate some of it it at runtime i.e. reduce their use of build time initialization. If that is not possible or not easy to configure then another option is to run your application on the dynamic JVM where, once again, the data will get created at runtime. As a last resort you could consider writing your whole app from scratch in some other language that does support building images with very large static data areas, using whatever library support that language offers.

I cannot speak for Oracle's GraalVM team and do not wish to be taken as doing so. However, if your expectation is that their plans for GraalVM Native work should change to address this problem now or in the near future then my advice would be to check your expectations.

**Comment by agibsonccc** [comment]
@adinn first of all thanks for commenting. I agree with you that it wouldn't make sense for them to make that change without a ton of work. I was ok with it being a documented limitation, but the GC change doesn't really reflect the hard coded number. 

It's not very user friendly to just have an overflow error thrown on the number of entries when it clearly should just be a warning to the user: you can't have more than Integer.MAX_VALUE of entries in your classpath. At least the user will know what to check for: reduce the number of entries.

I also agree that this problem is actually fairly specific. We build a whole operating system's worth of native binaries for various platforms that we bundle with our projects (see: https://bytedeco.org/) and so I understand that this would be rare. Downstream for our users, we will of course document this, but it would still be nice for other tools providers within the ecosystem to know of this limitation.

Hopefully this clarifies my expectations on the resolution. I'm not really asking for or expecting much here, I just don't think the docs posted here really reflect something that would help the user, nor do I think the GC docs were actually related to the underlying problem.
