### ISSUE TITLE
Supporting rust automatically

### ISSUE THREAD

**Issue by mrveera** [oracle/graal#360]
As graal already includes llvm we can load rust libs as well without manually specifying.

**Comment by rschatz** [comment]
I assume you're referring to the need to specify the standard libraries manually from http://www.graalvm.org/docs/reference-manual/languages/llvm/#running-rust

I'm not sure there is much we can do about that. The problem is that the bitcode files don't contain information about which libraries are required. This makes sense for rust, since usually rust is linked statically, but it is a bit unfortunate for GraalVM.

But I'm no expert in rust, so maybe I'm missing something. Did you have a concrete approach in mind?
