### ISSUE TITLE
[native-image] Java 9 and above.

### ISSUE THREAD

**Issue by svladykin** [oracle/graal#363]
GraalVM ships with Java 8, but Graal compiler is known to work with Java 9 and 10.
Is it possible to produce native images for Java 9 and above?

**Comment by chrisseaton** [comment]
I'm not an expert on the native image tool so someone else might want to comment, but I believe that it isn't possible to use Java 9 at the moment, because Java 9 has new intrinsics and a new implementation of classes such as `String` that the SubstrateVM needs to know about to use.

We do plan to support Java 9 soon-ish however.

**Comment by cstancu** [comment]
@christianwimmer is already working on Java 9 support.

**Comment by svladykin** [comment]
Thanks for your answers!

@christianwimmer Can you share your view on how long it may take?

**Comment by cstancu** [comment]
I'll close this issue as there is a newer one tracking the same feature: https://github.com/oracle/graal/issues/561.
