### ISSUE TITLE
Is Espresso confined by  org.graalvm.polyglot.io.FileSystem?

### ISSUE THREAD

**Issue by zenbones** [oracle/graal#3679]
org.graalvm.polyglot.Context allows the setting of a org.graalvm.polyglot.io.FileSystem, which allows for sandboxing polyglot languages. I presume that org.graalvm.polyglot.io.FileSystem is sufficient for the current crop of "scripting" languages, e.g. python, R, javascript, and ruby, as their file system 'objects' are not overly complex. However, I imagine that espresso code doing something as innocent as Paths.get("/some/path") is going to break out of the sandbox, as that code will engage the full power of Java's java.nio.file.FileSystem, which will grab the actual default FIleSystem for the os, which can't be backed or replaced by something based on org.graalvm.polyglot.io.FileSystem? Or am I mistaken in that assumption?

This was less of a problem as SecurityManager would at least allow sandboxing a thread to limited sub-sections of the file system, but, with the deprecation of SecurityManager, is there any hope of sandboxing Java on Java? I know the SecurityManager is brittle, difficult to maintain, and a drain on performance, but it also allowed sandboxing a Java thread, which is way more efficient than sandboxing the JVM itself via containerization, where we have to try to account for the complete overhead of the VM, including memory management, over and over again.

Espresso brings back a possible sandboxed environment for JVM bytecode-based languages, but only if the polyglot context holds for Espresso.

**Comment by mcraj017** [comment]
@gilles-duboscq Please advice

**Comment by gilles-duboscq** [comment]
At the moment, espresso does not integrate with `org.graalvm.polyglot.io.FileSystem`. Espresso doesn't re-implement any part of the OpenJDK standard library so that means all the I/O path go through the OpenJDK Java and native code.
You might have noticed that you can't do much with espresso currently in a context that doesn't allow native-code access for this reason.

However it's definitely something we want to support. One way is through Sulong managed: then the OpenJDK native code would be executed by Sulong managed with integrates with `org.graalvm.polyglot.io.FileSystem`. The second way is to provide a guest `java.nio.file.FileSystem` implementation that goes through `org.graalvm.polyglot.io.FileSystem` on the host.

**Comment by zenbones** [comment]
Thanks.
