### ISSUE TITLE
Support `MinHeapFreeRatio` and `MaxHeapFreeRatio` in GraalVM Native

### ISSUE THREAD

**Issue by jvican** [oracle/graal#3751]
**Feature request**

**Is your feature request related to a problem? Please describe.**

Looks like the `MinHeapFreeRatio` and `MaxHeapFreeRatio` memory flags are not supported in the Serial GC available in the GraalVM Native, judging by their absence in `native-image --expert-options-all`.

**Describe the solution you'd like.**

I'd like to be able to set these flags to control how much does the heap grow under allocation and deallocation pressure, in the same way you can do the same on the JVM. All in all, this is very useful to control the memory footprint of the JVM process and would like the same capability for native.

**Describe who do you think will benefit the most.**

This feature will be useful for anyone that runs Netty or other libraries that are configured to use a lot of heap. In my case, I use vert.x, grpc and a few more JVM technologies for native programs.

**Describe alternatives you've considered.**

I can' use G1GC because I don't have a GraalVM Enterprise license. Also, I prefer the simplicity of the Serial GC as I don't have low-latency requirements.

**Comment by mcraj017** [comment]
@jvican Thanks for the feature request, we will check it out and get back to you

**Comment by mcraj017** [comment]
@jvican I have raised this request with the native-image team, they will respond you accordingly

**Comment by peter-hofer** [comment]
Hi @jvican , the native-image serial GC does not work in the same way as the HotSpot SerialGC: it allocates objects in chunks instead of a contiguous range, and we generally only reserve free chunks up to the (current) size of eden. We are currently working on a new GC policy that balances throughput and footprint, based on the policy of HotSpot's ParallelGC: https://github.com/oracle/graal/pull/3589

Can you give us more details on your workload and what you are specifically using these options for, to see how it could translate to our new policy? Do you have a benchmark or example where their effect is significant?
