### ISSUE TITLE
[native-image] native image failed to build jar

### ISSUE THREAD

**Issue by sound2gd** [oracle/graal#411]
I am a clojure user and I use leiningen to build a executable fat jar.

it can be runned directly using `java -jar`, but when I use `native-image -jar`

It stucked and hung forever

here is the output
![image](https://user-images.githubusercontent.com/10735388/39767564-a705887e-5319-11e8-8909-b369f26f9e2b.png)

```bash
$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
GraalVM 1.0.0-rc1 (build 25.71-b01-internal-jvmci-0.42, mixed mode)

lein -v
Leiningen 2.8.1 on Java 1.8.0_161 GraalVM 1.0.0-rc1
```

**Comment by cstancu** [comment]
@sound2gd thank you for your report, we'll look into it!

**Comment by cstancu** [comment]
@sound2gd can you provide the steps to build that jar?

**Comment by sound2gd** [comment]
@cstancu  sorry for late reply. here is the step.

first make sure you have installed [leiningen](https://leiningen.org/)
then

```bash
$ lein new luminus graal-test
Retrieving luminus/lein-template/2.9.12.54/lein-template-2.9.12.54.pom from clojars
Retrieving luminus/lein-template/2.9.12.54/lein-template-2.9.12.54.jar from clojars
Generating a Luminus project.

$ cd graal-test
$ lein uberjar
....
Created graal-test/target/uberjar/graal-test-0.1.0-SNAPSHOT.jar
Created graal-test/target/uberjar/graal-test.jar

$ native-image -jar ./target/uberjar/graal-test.jar
```

**Comment by cstancu** [comment]
@sound2gd I tried to replicate the issue on my machine and I get a different behavior. The `native-image` runs for ~4 minutes but the build crashes because it detects unsupported features. On my machine the heap size of `native-image` gets up to the max, 14GB. You probably have less memory on your machine so the `native-image` runs with much less and at some point the GC occupies most of the execution. Eventually you would have probably seen an out of memory error from the JVM. I will analyze this further to see why it needs to allocate this much memory.

**Comment by mping** [comment]
I have the same problem while trying to build https://github.com/mping/compojure-api-chassis. There's a makefile in that repo for building with `native-image` in case you need a test repo.
