### ISSUE TITLE
What about graal used for light VM of blockchain

### ISSUE THREAD

**Issue by BottosGroup** [oracle/graal#413]
As we know , blockchain could use light vm to run a light operation, just like evm or wasm. What about the graal used for blockchain? Who are interested in this issue?  Is it possible?

**Comment by pekd** [comment]
Of course you can embed Graal into your blockchain. But the big question is: why would you want to do that?

A scripting environment for a blockchain has certain requirements like determinism and limited resources (i.e. starting the program from the same initial state always has to lead to the same final state, and every program is guaranteed to terminate within a certain number of steps). Graal doesn't support concepts like limiting resources (e.g. limiting the number of executed intructions) and I'm quite sure you don't get determinism either (think of something as simple as float arithmetic, which has a few implementation dependent cases, e.g. NaN where the bit representation is different between architectures).

It's also possible to develop an evm interpreter on top of Graal/Truffle, but then again: why? Graal is a compiler for long running server workloads. It has quite some warmup times. However, a typical program for the evm is run once, and its execution time is quite short. It is finished long before Graal would even think about compiling/optimizing the program. The only usecase of such a Graal/Truffle based evm interpreter would be fuzzing/brute forcing evm programs where you have to re-execute the program numerous times, but that's also not useful, since tools are available for symbolic execution.

I don't understand how Graal (+ Truffle?) could be useful in such an environment. Maybe you can explain that?

**Comment by BottosGroup** [comment]
OK， I know graal may be heavy for blockchain. But now the blockchain's evm can support specific lang and the tool chain is not popular for coder. So we want to find out a common enviroment which can load and excute some langs to easy it's development. Also the evm can plugin any excutor . So we want to adjust the graal  to adopt the chain.

**Comment by BottosGroup** [comment]
We also want find some developers to join our team and make a new type evm
