### ISSUE TITLE
[GR-36414] Truffle blocklist methods issues / Missing @TruffleBoundary

### ISSUE THREAD

**Issue by LilPoppy** [oracle/graal#4192]
Hi, I know it's not a bug but I'm curious how can we remove methods from blocklist.

[Stack Overflow](https://stackoverflow.com/questions/70646496/graalvm-build-failure-with-blocklisted-methods-are-reachable-for-runtime-compil)

**Comment by rubyFeedback** [comment]
I think it would be better if you could describe the problem here - it's a bit cumbersome to read them in an external website, in my opinion.

**Comment by fniephaus** [comment]
> Hi, I know it's not a bug but I'm curious how can we remove methods from blocklist.

The [CI log you linked](https://github.com/SpamanDev/StoreChain-Server/runs/4755546198?check_suite_focus=true#step:9:305) does suggest that GraalVM's Python implementation is missing a `@TruffleBoundary`, which is a bug we need to fix. I've already informed the GraalPython team.

While turning off the blocklist might help you work around the bug, it can certainly cause other problems. The warning protects us from including too much code in PE, that's why it's enabled by default. I wouldn't turn if off in production.

**Comment by LilPoppy** [comment]
> 

Thank you so much! And graal python is not work in Mac Platform is that correct?

**Comment by fniephaus** [comment]
GraalPython is still considered experimental, but we ship builds for Linux and Darwin so macOS should work. Windows is not yet supported.

**Comment by LilPoppy** [comment]
> GraalPython is still considered experimental, but we ship builds for Linux and Darwin so macOS should work. Windows is not yet supported.

But I got build failure on MacOS which return message is Unsupported platform. Not sure it’s another bug or I should add another arg in native-image beside language:python

**Comment by fniephaus** [comment]
GraalPython can be built with native image on macOS. However, it does require additional configuration (see [here](https://github.com/oracle/graalpython/blob/master/mx.graalpython/native-image.properties)). Note that building it as an embedded part of a Java application is definitely not supported in any way at this point.

Could you please open an issue for the "Unsupported platfork" error incl. a reproducer at: https://github.com/oracle/graalpython/issues/new ?

**Comment by fniephaus** [comment]
Closed via https://github.com/oracle/graalpython/commit/2195e455f1cbae52f03500aacb195a8e093142e6.
