### ISSUE TITLE
Incredible slow (up to 10 times) graalvm native-image vs java on trivial code

### ISSUE THREAD

**Issue by DeivAstra** [oracle/graal#4214]
**Describe the issue**
I had create some chunk of code for internal purposes and found that my code builded by image-native is executes slower up to 10 times.
I have use native-maven-plugin (0.9.9) without any specific settings. Main class configured only.

Source code here:
[IncredibleSlowGraalVmTest.java](https://github.com/danykey/incredible-slow-graalvm/blob/master/src/main/java/test/IncredibleSlowGraalVmTest.java)

FYI: executable file sizes also are different.  ~15MB (21.3.0) vs ~12MB (22.1.0-dev-20220113_2228)

Execution results:
```
// JDK 17 (OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)
generateRandomData >
end generateRandomData (2937 ms)
search synonyms in data >
end search synonyms (4564 ms)

$ ./incredible-slow-graalvm_ce-java17-21.3.0
generateRandomData >
end generateRandomData (29441 ms) !!! slower to 10 times !!!
search synonyms in data >
end search synonyms (11510 ms) !!! slower to 2 times !!!

$ ./incredible-slow-graalvm_ce-java17-22.1.0-dev-20220113_2228
generateRandomData >
end generateRandomData (55176 ms) !!! slower than 21.3.0 !!!
search synonyms in data >
end search synonyms (11433 ms) !!! slower to 2 times !!!
```

**Steps to reproduce the issue**

1. **git clone --depth 1 https://github.com/danykey/incredible-slow-graalvm.git**
2. **Set in file build-graalvm.sh JAVA_HOME variable as path to graalvm folder.**
3. **Make it executable: chmod +x build-graalvm.sh**
4. **Run: ./build-graalvm.sh**

**Compiled executables Linux (x86_64 only)**
[incredible-slow-graalvm_ce-java17-21.3.0_linux_x86_64](https://github.com/danykey/incredible-slow-graalvm/releases/download/0.1/incredible-slow-graalvm_ce-java17-21.3.0_linux_x86_64)
[incredible-slow-graalvm_ce-java17-22.1.0-dev-20220113_2228_linux_x86_64](https://github.com/danykey/incredible-slow-graalvm/releases/download/0.1/incredible-slow-graalvm_ce-java17-22.1.0-dev-20220113_2228_linux_x86_64)

**Describe GraalVM and your environment:**
 - GraalVM: **graalvm-ce-java17-21.3.0 and GraalVM CE 22.1.0-dev-20220113_2228**
 - JDK: **OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)**
 - OS: **Manjaro Linux 21.2.1 Kernel: Linux 5.15.12-1-MANJARO SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021 x86_64 GNU/Linux**
 - Architecture: **AMD64**

**More details**
Maven compilation logs here:
[mvn-compile-graalvm-21.3.0.log](https://github.com/danykey/incredible-slow-graalvm/blob/master/mvn-compile-graalvm-21.3.0.log)
[mvn-compile-graalvm-22.1.0-dev-20220113_2228.log](https://github.com/danykey/incredible-slow-graalvm/blob/master/mvn-compile-graalvm-22.1.0-dev-20220113_2228.log)

**Comment by rodrigar-mx** [comment]
Thanks for reporting this issue. We will take a look into it and get back to you.

**Comment by christianwimmer** [comment]
Thanks for sharing. In summary, these are two microbenchmarks that trigger behavior that we are already working on to optimize, so things should get a lot better in a few months.

First, two notes:
* The random number generation makes the benchmark non-deterministic. That can easily be solved by changing the code to use a `Random` object with constant seed, so that every run produced the same (now no longer really random) numbers:
```
        /* Make benchmark deterministic by using random number generator with constant seed. */
        static final Random myRandom = new Random(1234);
        
	private static int getRandomNumber(final int min, final int max) {
		return (int) ((myRandom.nextDouble() * (max - min)) + min);
	}
```
* When running on the HotSpot VM, the timing includes the JIT compilation time, since there is no proper warmup. But since the benchmark runs for long enough, using a harness such as JMH to control warmup is of course a bit of a overkill. Just wanted to mention it though.

The benchmark actually consists of two independent micro-benchmarks, that are not really related to each other:

### generateRandomData

While this is not immediately obvious, this is a microbenchmark for `System.arraycopy` of `Object[]` arrays. The execution time is dominated by the time spent in `ArrayList.remove` in the innermost loop, which is itself not much more than call to `System.arraycopy`. We have started to optimize `System.arraycopy`, but we know that much more needs to be done. Currently, there is still a write barrier and a safepoint check for each copied element.

### getCharBySynonym

In this microbenchmark you have two-dimensional array accesses where the first dimension access is actually loop invariant (so you could hoist it out into a local variable in the outer loop). The JIT compiler is able to do this hoisting, because it can do speculative optimizations and deoptimize in case an exception needs to be thrown. The AOT compiler of Native Image needs to always preserve the Java exception semantics, and therefore does not do any hoisting yet. We need to compile two versions of the loops, a fast version where bounds checks are hoisted out of the loop (which would always run in case of the benchmark because it does not throw exceptions), and second version with full checks as a fallback when an exception is necessary.

**Comment by jigneshkhatri** [comment]
Any update on this thread? I am also observing speed issues while running same code on standard JDK vs on Graalvm JDK.

**Comment by wirthi** [comment]
Serveral improvements in this area have been implemented since this was initially reported. You might want to try again on a latest version of GraalVM. A few general optimizations are still pending, but nothing to be tracked in this specific ticket.
