### ISSUE TITLE
[native-image] installation error on Windows

### ISSUE THREAD

**Issue by ManjuCaroline** [oracle/graal#4295]
I am trying to install native image using the command "gu install native-image" in my cmd. But it is showing the below mentioned error,

Downloading: Release index file from oca.opensource.oracle.com
Error: Error reading component list: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I tried executing the command as Administrator but it doesn't seem to help. Kindly help.

**Comment by Karm** [comment]
You most likely need to update you Windows to have a fresh truststore. A good way to check would be to use PowerShell to access the site: https://oca.opensource.oracle.com/
If it fails too, you know you need to update your truststore.

IMHO

**Comment by rodrigar-mx** [comment]
Hi @ManjuCaroline. Try the suggested approach. Otherwise, please share which graalvm specific version did you download and your windows version. You can also try downloading the native image [installable](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.0.0.2)  and install with `gu install -L <native-image-installable-file>`

**Comment by wirthi** [comment]
Closing this older ticket. Please reopen if the problem still remains.
