### ISSUE TITLE
Backport JDK-8276314 to GraalVM Java 8

### ISSUE THREAD

**Issue by lic9** [oracle/graal#4465]
JDK-8276314 fixed a JVMCI alignment check issue, but it was only backported to Java 11. Do we have plans to patch it to GraalVM Java 8?

**Comment by dougxc** [comment]
That bug was part of a long process to fix a crash which we ultimately believe is due to https://bugs.openjdk.java.net/browse/JDK-8283306.

We have modified Graal to try avoid this problem altogether: 4ae7b0eb591fa32732349a6dbb17cde5d5c75e3d

BTW, since there are [no more GraalVM CE releases on JDK 8](https://oss.oracle.com/pipermail/graalvm-announce/2021-September/000048.html), all backporting to https://github.com/graalvm/graal-jvmci-8 has stopped.

**Comment by lic9** [comment]
Thanks for sharing all the details!
