### ISSUE TITLE
Build time initialization of org.springframework.util.unit.DataSize

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graal#4489]
Hey,

I'm struggling to understand build time initialization. I don't get why the build time initialization of `org.springframework.util.unit.DataSize` is necessary in our spring-boot native image.

The native image building fails if we don't include `--initialize-at-build-time=org.springframework.util.unit.DataSize`.

I wasn't able to build a minimal reproducer for this. Here's the full reproducer:

```
git clone --depth=1 --branch mh/data-size https://github.com/mhalbritter/spring-framework.git
cd spring-framework
./gradlew publishToMavenLocal -xtest -xjavadoc -xdokkaHtmlPartial

git clone --depth=1 --branch aot https://github.com/spring-projects/spring-boot.git
cd spring-boot
./gradlew publishToMavenLocal -xtest -xaggregatedJavadoc -xasciidoctor -xasciidoctorPdf -xzip

git clone https://github.com/snicoll-scratches/demo-native-sample.git
cd demo-native-sample
./mvnw package -Pnative
```

When running this, i get the error

```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.springframework.util.unit.DataSize are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=org.springframework.util.unit.DataSize.
```

When adding the `--trace-object-initialization=...` from the error message, I get:

```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of org.springframework.util.unit.DataSize are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
```

Adding `--initialize-at-build-time=org.springframework.util.unit.DataSize` works, but why is this necessary?

The only thing which we initialize at build time ([via native-image.properties file in `spring-core.jar`](https://github.com/mhalbritter/spring-framework/blob/mh/data-size/spring-core/src/main/resources/META-INF/native-image/org.springframework/spring-core/native-image.properties)) is [`org.springframework.core.NativeDetector`](https://github.com/mhalbritter/spring-framework/blob/mh/data-size/spring-core/src/main/java/org/springframework/core/NativeDetector.java).

I used the latest available 22.1-dev build (https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.1.0-dev-20220411_0809)

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0-dev (build 17.0.3+5-jvmci-22.1-b04)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0-dev (build 17.0.3+5-jvmci-22.1-b04, mixed mode, sharing)
```

OS is Linux aarch64.

**Comment by sdeleuze** [comment]
Please tag this issue with the `spring` label. FYI we have this issue from the beginning.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this we will take a look into it and get back to you

**Comment by snicoll** [comment]
Yes, sorry about that. Please remove that tomcat class as well as the import that it references on the main class as neither are necessary to reproduce. Alternatively you could checkout the previous commit. 

Thanks for looking at this!

**Comment by christianwimmer** [comment]
I can reproduce the problem. This is a corner case triggered by the combination of annotations, enums, and classes that cannot trivially be initialized at image build time:
* The class `DataSize` cannot be proven safe for initialization at build time due to the `static final Pattern PATTERN` whose initialization is too complex to analyze.
* `DataSize` is used by the enum `DataUnit` when allocating the enum instances. So initialization of `DataUnit` triggers initialization of `DataSize`.
* `DataUnit` is used by various annotations. The random first hit I had in the debugger (and for sure not the only usage) is https://github.com/spring-projects/spring-boot/blob/23b5a3f70e3ab8d1319632c82056bdcddb3f42f6/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoProperties.java#L59
* Since currently all annotations are parsed eagerly at image build time, these annotations transitively trigger the initialization of `DataSize`.

We are trying to fix this corner case (fyi @loicottet, @vjovanov) but it requires re-working a lot of code that currently accesses annotations eagerly.

But I think you can work around the problem in Spring: you only need to get the field `PATTERN` out of `DataSize` in https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/util/unit/DataSize.java#L58
The easiest way is to wrap it in a static inner class. The remaining static final fields in `DataSize` are not a problem because their initialization can be proven to have no side effects. Putting `PATTERN` in its own class also has startup benefits on HotSpot: currently every usage of `DataSize` triggers the expensive compilation of the regular expression. When the field is in a separate class, the compilation only happens when `DataSize.parse` is invoked the first time (which might be never).

**Comment by sbrannen** [comment]
Thanks for the analysis and tips, @christianwimmer.

We will start initializing the `PATTERN` field lazily in Spring Framework 5.3.21.

- See https://github.com/spring-projects/spring-framework/issues/28560

**Comment by nicolasesprit** [comment]
https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_datasize_was_unintentionally_initialized_at_build_time

**Comment by sdeleuze** [comment]
@nicolasesprit I am not sure why you are linking this Spring Native (based on Spring Framework 5.3) troubleshooting documentation entry. We modified Spring Framework 6 to workaround this issue as pointed our by @sbrannen. Could you share more details?

**Comment by loicottet** [comment]
The underlying issue of initializing annotations at build-time has been patched on master by https://github.com/oracle/graal/commit/9da460f36f3ee45ac6ccbbcf408ac20e0179929d

**Comment by sdeleuze** [comment]
Thanks!
