### ISSUE TITLE
Duplicated resources with GraalVM 22.1

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#4493]
GraalVM 22.1 (branch or latest dev build) breaks Spring Native build because 2 resources are detected instead of 1 with GraalVM 22.0 or the JVM. Related issue on Spring side is https://github.com/spring-projects-experimental/spring-native/issues/1584.

To reproduce:
 - Clone https://github.com/spring-projects-experimental/spring-native
 - With Java 11 run `./build.sh` at the root
 - `cd samples/jdbc-tx`
 - `mvn clean test -P native` works with GraalVM 22.0 and fails with GraalVM 22.1

With debug logs, we can see a difference of behaviour.

22.0
```
Executing SQL script from URL [resource:schema.sql]
```
22.1
```
Executing SQL script from URL [resource:/schema.sql]
Executing SQL script from URL [resource:/schema.sql#1]
```
So `ClassLoader#getResources("schema.sql")` returns one result with GraalVM 22.0 and 2 with 22.1 for our use case, with `ClassLoader` instance being `jdk.internal.loader.ClassLoaders.AppClassLoader#AppClassLoader` and `schema.sql` just in `src/main/resources`.

Please tag this issue with the `spring` label.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this we will take a look into it and get back to you

**Comment by olpaw** [comment]
Hi @sdeleuze 

From native-image perspective, the observed behavior is correct.

Looking into `spring-native/samples/jdbc-tx` you find
```
./src/main/resources/schema.sql
./target/classes/schema.sql
```
By adding `--verbose` to the native-image command you can see that **the image build above specifies the following classpath entries**:
```
.../spring-native/samples/jdbc-tx/src/main/resources
.../spring-native/samples/jdbc-tx/target/classes
```
Thus `schema.sql` is visible twice from different places and since pattern `"pattern": "schema.sql"` that is given by `spring-aot/resource-config.json` matches in both cases we have to add them both.

To fix the issue I suggest to make sure that `.../spring-native/samples/jdbc-tx/src/main/resources` is not part of the image classpath.

**Comment by mhalbritter** [comment]
Thanks for analysis. I'll take a look.

**Comment by sdeleuze** [comment]
Good point @olpaw, closing this one in favor of https://github.com/graalvm/native-build-tools/issues/234.
