### ISSUE TITLE
Question about GraalVM Memory structure

### ISSUE THREAD

**Issue by tellmewhattodo** [oracle/graal#4604]
**Describe the issue**
I updated my application from Graal VM 21.2 JDK8 to Graal VM 21.3.2 JDK11, and encountered some memory issues.

I have some questions followed, it's all about GraalVM's memory structure(Heap & non-heap).
1.I found there is no 'CodeCache' area in my case(no data showed in my monitor), I wander if it's JDK11 changed it's behavior or libgraal take place of it. (CodeCache exists and works fine on Graal VM 21.2 JDK8 )
2.I noticed there's an area of memory used by 'libgraal' and could set limitation by 'Dlibgraal.Xmx=512M', I wander if there is a README or GUIDE about a reasonable limit value.
3.I enabled 'XX:NativeMemoryTracking' and found there's no info about 'libgraal', but it showed memory consumption of 'CodeCache'. it confused me a lot.

above all ,I'd like to know the difference about memory structure between Stock-JDK and GraalVM 21.3.2 JDK11, is there any memory area I didn't know , how CodeCache works , and the relationship between libgraal memory and CodeCache.
 it's important to solve my problem ( a lot of Docker pod OOM and main thread exits)

**Steps to reproduce the issue**
no, just questions

**Describe GraalVM and your environment:**
Graal VM 21.3.2 
JDK11
CentOS 7.2
AMD64

**More details**

no more for now.

**Comment by tellmewhattodo** [comment]
https://github.com/oracle/graal/issues/2224
read this and got the idea of setting Dlibgraal.Xmn lower.
I'll have a try, and set it to 128m with Xmx=1g.


since libgraal is enabled since 19.x, I wander why this became a problem after my upgrade.

while switching to jargraal is also an options, I really want to know how to limit the maximum memory consumption of GraalVM.

Any help ?

**Comment by tellmewhattodo** [comment]
at Graal CE 21.3.2, when limit with -Dlibgraal.Xmx=512m, libgraal crashes sometimes( in my case ,once per hour).

 I switched to Graal CE 22.1.0 to continue test, it seems better for now(not crashed yet).

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out, we will take a look into this and get back to you

**Comment by dougxc** [comment]
The (non-CodeCache) memory used by libgraal is influenced by the underlying JDK classes against which Graal is developed. That might explain some of the memory difference between libgraal on 8 vs 11.
Code compiled by libgraal is installed in the standard HotSpot CodeCache.

The CodeCache questions might be answered by this article: https://www.baeldung.com/jvm-code-cache
In particular, look the part of the [segmented code cache](https://www.baeldung.com/jvm-code-cache#segmented).

The `-XX:NativeMemoryTracking` flag is only used for memory allocated with libjvm.so so excludes memory allocated by libgraal.so. The `-Dlibgraal.PrintGC=true` option may be useful in terms of inspecting libgraal memory usage. Also, tools such as `ps` can be used to monitor memory usage per shared library.

When HotSpot compilation becomes idle, the VM stops compiler threads. On GraalVM EE, this means when all libgraal compiler threads are stopped, the memory used by libgraal is released (until compilation loads picks up again). As of the next GraalVM release, GraalVM CE will also include this feature (due to https://bugs.openjdk.java.net/browse/JDK-8242440 having been merged).

I hope that answers most of your questions.
