### ISSUE TITLE
[native-image] DatagramChannel Unsupported?

### ISSUE THREAD

**Issue by Anuken** [oracle/graal#474]
I'm trying to compile a headless server for my Java game with `native-image`. 

I use [KryoNet](https://github.com/EsotericSoftware/kryonet) as my network library. When a client tries to connect to the server, I get [this error](https://hastebin.com/pidemaxoma.bash). 

It appears that the `sun.nio.ch.DatagramChannelImpl` class that Kryonet uses for (UDP?) communication is not implemented. Did I do something wrong, or is this class completely unsupported? If it's the latter, are there any plans to support it in the future?

**Comment by cstancu** [comment]
@Anuken `sun.nio.ch.DatagramChannelImpl` is currently not supported. Yes, we plan to support it in the future, but we don't have any estimation at this point as of when it will be ready.

**Comment by cstancu** [comment]
As a workaround for now you could try to configure your KryoNet server to use a `com.esotericsoftware.kryonet.TcpConnection` instead? I see that it internally it uses `java.nio.channels.SocketChannel` which we support.

**Comment by Anuken** [comment]
Alright, I'll try that. Thanks for the response.

**Comment by bobmcwhirter** [comment]
Taking a look into this, and I find the sun.nio.ch stuff lives in `com.oracle.svm.core` but to translate the code, I need `SOCKADDR` which lives in `com.oracle.svm.core.posix`.

Would it be weird/disallowed to add a dependency between the two? It somewhat seems to invert the relationship and possibly cause a circular dependency to have `core` depend upon `core.posix`.

Would a better route be to move the NIO bits over to `core.posix` or some other module instead of within `core`?

**Comment by Peter-B-Kessler** [comment]
If you need `com.oracle.svm.core.posix.headers.Socket.sockaddr` then you should be writing in a `com.oracle.svm.core.posix` package.  You can have substitutions that are partly in `core` and partly in `core.posix`.  See `Target_sun_nio_ch_Net`, the platform-independent (:-) parts of which are in `SunNioSubstitutions.java`, and the POSIX-dependent parts of which are in `PosixJavaNIOSubstitutions.java`.  (I see we have to clean up our capitalization rules.)

If you are implementing `DatagramChannelImpl.receive0` and `DatagramChannelImpl.send0` for POSIX, then I think those belong in `PosixJavaNIOSubstitutions.java`.

**Comment by bobmcwhirter** [comment]
Yah, I think I just assumed since the `VMerror` is here:

https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SunNioSubstitutions.java#L107-L115

that the translation would go there also.  But sounds like delete those, move the substitutions for those methods to `PosixJavaNIOSubstitutions.java` in the `posix` package?

**Comment by Peter-B-Kessler** [comment]
This issue will be addressed when we switch from translations of the JDK native code to a JNI-based approach.

**Comment by dmlloyd** [comment]
That would be a shame considering how much extra size JNI brings.

**Comment by christianwimmer** [comment]
> That would be a shame considering how much extra size JNI brings.

I don't understand that concern. Currently, we have C code from the JDK manually translated to low-level Java code. That sounded like a good idea at first, but it turned out to be not maintainable (too many operating systems, too many different JDK version). So we are going to link in the C code of the JDK instead of using our own low-level Java code. But the amount of code remains about the same.

**Comment by dmlloyd** [comment]
Nevertheless, including JNI seems to bring a constant extra 5-6MB or so of image size.  This recurring cost would be borne by all users of SubstrateVM, as opposed to maintenance cost which is not recurring to nearly the same degree; being able to exclude this extra size brings a large cumulative benefit.

After all one could use the same argument to say that SubstrateVM itself should be discontinued because the JDK does ship jaotc which does the same thing, so that there's one code base to maintain instead of two.  However both arguments completely discount the benefit brought by the cost.

Allowing Java code to call directly to and from C is a very powerful feature - much more powerful than JNI - and I for one would happily spend time to help maintain the code base that allows SubstrateVM to use this mechanism to avoid bringing in the extra weight that the JDK brings.

Using the JDK libraries means requiring that the JDK libraries are present for the native image - a step backwards, architecturally.  Also, having dead code elimination extend into formerly native code seems very powerful as well.

Overall I find this design decision surprising, and a little baffling.

**Comment by christianwimmer** [comment]
> Using the JDK libraries means requiring that the JDK libraries are present for the native image

No, the JDK native code will be linked in statically into the native image. There is still no need that any extra JDK library is present, and there is still no runtime dependency on anything from a JDK.

> Nevertheless, including JNI seems to bring a constant extra 5-6MB or so of image size.

What are you measuring here? The hosted option `SubstrateOption.JNI` already has the default value `true` since quite a while, i.e., JNI support is by default built into every image.

> I for one would happily spend time to help maintain the code base
Considering how much time we spent for our current Linux and MacOS support (and that is still far from complete), adding and maintaining just the Windows support would be a full time person. That does not sound like a good use of resources.

**Comment by dmlloyd** [comment]
> > Using the JDK libraries means requiring that the JDK libraries are present for the native image
> 
> No, the JDK native code will be linked in statically into the native image. There is still no need that any extra JDK library is present, and there is still no runtime dependency on anything from a JDK.

And this is included regardless of what features are actually used?  Or is DCE able to sniff these out?  What if we've substituted all of the JDK code that would have otherwise been linked in?

> > Nevertheless, including JNI seems to bring a constant extra 5-6MB or so of image size.
> 
> What are you measuring here? The hosted option `SubstrateOption.JNI` already has the default value `true` since quite a while, i.e., JNI support is by default built into every image.

Flat image size with JNI turned off versus turned on.  Let's assume that the default value is irrelevant to us because we've always explicitly controlled it for the reason of image size control.

> > I for one would happily spend time to help maintain the code base
> 
> Considering how much time we spent for our current Linux and MacOS support (and that is still far from complete), adding and maintaining just the Windows support would be a full time person. That does not sound like a good use of resources.

It's not a question of whether any one person thinks it's a good use of resources; it's a cost-benefit proposition.  The cost is maintainership; the benefit is higher performance and reduced image size.  The cost applies to few; however the cumulative benefit applies to many and could be huge, and is part of the basic value proposition of the project AFAICT.  One full time person seems to be a tiny price in comparison.

**Comment by christianwimmer** [comment]
We care about executable size and startup performance as much as you. But I still believe switching to JNI will have a major impact. We will see when we have the first prototype running.

I would still like to understand where you see a 5-6MB overhead. A "Hello, World!" image with JNI support (the default) has about 2 MByte, the with `-H:-JNI` it is about 300 KByte smaller. And these 300 KByte are mostly JDK methods that would be reachable in a larger application anyway.

**Comment by dmlloyd** [comment]
We last tested several releases ago.  I can give it a try with a recent version and see how it goes.
