### ISSUE TITLE
Documentation: jni-config.json

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graal#4766]
Hello,

[This documentation about JNI](https://www.graalvm.org/22.1/reference-manual/native-image/JNI/) mentions that you have to include JNI config by specifying `-H:JNIConfigurationFiles`. It doesn't mention that the config gets picked up too when stored in `jni-config.json` under `META-INF/native-image`. That caused some confusion in our team and we had to test it. Would be great if that could be mentioned in the documentation.

Thanks!

**Comment by rubyFeedback** [comment]
I'd like to +1 this - a few months ago I read from a java dev who got swing + graalvm to work but he
had to use some INI thingy. I think it was the same mhalbritter pointed out above.

At that time I was fairly new to Java; I could run basic swing applications and built a simple one but
the extra stuff I had to go through was too complicated for me at that time so I stopped. Having that
information on the official docs would be super helpful. I found the GraalVM documentation overall
quite useful - if it exists. It's a good read per page and it contains "to the point" info, which helps
a LOT. So if anyone wants to have a look at the JNI stuff, and explain some context around it
(for instance, I still don't know WHY we need such a config file for getting swing to work with
GraalVM, remember we may have first built without such a config file and suddenly we need one),
it would be good.

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
cc @olyagpl

**Comment by olyagpl** [comment]
@rubyFeedback , we hope the [Native Image documentation](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/JNI/) has improved since the last time you visited it. The reachability of some dynamic Java features may not be discoverable by `native-image`  by default. It can lead to failures at run time.  Individual elements accessible via JNI must be specified in a configuration file. 
Here is a JSON schema for specifing JNI metadata: https://www.graalvm.org/latest/reference-manual/native-image/metadata/#specifying-metadata-with-json. 
You can apply the Java agent, shipped with Native Image, as an option, to help you generate the configuration: https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/#tracing-agent.
