### ISSUE TITLE
Unable to find JNI bindings in GraalVM 22.2.0

### ISSUE THREAD

**Issue by yeswanthkumark** [oracle/graal#4800]
We use JNI in our native images to communicate with Java. For this we use the existing JNI bindings found in GraalVM such as com.oracle.svm.jni.nativeapi.JNIEnvironment and com.oracle.svm.jni.nativeapi.JNIObjectHandle.

When we upgraded GraalVM and our maven dependencies (e.g. org.graalvm.nativeimage:svm) from 22.0.0 to 22.2.0, we noticed that we were still able to compile, but we get a runtime error that the JNI binding classes couldn't be found in the native image. After some investigation, it looks like they were moved to a different package (com.oracle.svm.core.jni.headers) in the GraalVM source code. However, the same thing has not been done in nativeimage-svm. So either the change was unwanted or nativeimage-svm needs to be updated.

Also, we noticed that this (breaking) change is not mentioned as part of documentation.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
@yeswanthkumark are you sure you're using 22.2.0 and not 22.3.0-dev?
cc @lazar-mitrovic

**Comment by yeswanthkumark** [comment]
@oubidar-Abderrahim @lazar-mitrovic  Yes, it is the 22.2.0

**Comment by lazar-mitrovic** [comment]
Hey @yeswanthkumark,
I've just downloaded GraalVM 22.2.0 CE from https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.2.0, installed `native-image` using `gu install native-image`, opened `lib/svm/builder/svm.jar` and the required classes are still there.

Only reason why this could happen (that I can think of) is that you are using a version of GraalVM that is newer than 22.2.0 since this [change](https://github.com/oracle/graal/commit/e6a0296a950b7f45b07fdf2d53cf3c9720b92b2a#diff-4ac33053e3cb3485ffd25b749e59efc313089e0129609903d17db3d185bc46bd) isn't a part of 22.2.0 branch. Can you please run `native-image --version` and run the build with the `--verbose` flag afterwards?
