### ISSUE TITLE
Test Smell: testing private methods is not a good test practice

### ISSUE THREAD

**Issue by TestSmell** [oracle/graal#4808]
Hi!
I notice that in your test code, you try to use reflection to assess and test the private method.
For example, 
the fixture method named ''private static Map<String, Object> invokeLanguageCacheCreateLanguages(ClassLoader... loaders)' in ''LanguageCacheTest.java'' uses the reflection method to test a private method named ''private static synchronized Map<String, LanguageCache> createLanguages(List<AbstractClassLoaderSupplier> suppliers)'' in ''LanguageCache.java''.

But, the problem of testing private methods has a wide discussion in Stack Overflow, and the majority of answers think it is a bad test practice. Because it may cause many problems:
1. many answers believe that if you need to test private methods, it means your production code is not well designed, i.e., design smell.
2. testing private methods breaks the encapsulation.
3. Many answers mention that private methods are invoked by public ones, so test methods just need to test public methods. Otherwise, if a private method needs to be tested separately, it may be dead code.
4. Testing implementation details (private methods) directly would make the tests harder to maintain and the code-under-test
more difficult to refactor.

Although several methods are used to access private methods (e.g., reflection methods, mock tests, changing the modifier to make it visible), refactoring the corresponding code is regarded as the best practice to eliminate this bad test practice.

So, we kindly suggest you refactor the corresponding source code instead of using the reflection method to test the private method.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for your suggestion, we will take this into consideration

**Comment by TestSmell** [comment]
:-)

**Comment by chumer** [comment]
I understand your concerns and the best practices you mention are typically applicable. However, there are situations where you need to break encapsulation to test certain error cases in the behavior. 
For example, in the LanguageCacheTest we want to test what happens if there are multiple languages with the same id installed. We want to make sure that the engine fails to initialize if that happens. However if we just regularly register the languages classes like we do in other tests all other tests would also fail to initialize because of the duplicate ID. So in order to avoid the failing of other tests we somewhat hack the internals to swap out the typically statically determined languages to test the errors and then switch back to the old version of the regularly installed languages.

Yes, this is somewhat hacky, but I do not see a simpler solution to test this. We do not want to introduce a public API that generally allows you to swap out the statically loaded classes. We could eventually use context class loaders for that, but that would be more complicated to understand, so not really a good trade-off.

As a safeguard, if the internal contracts change for some reason, the test would fail and we would notice.

I think the test is as good as it gets. But thanks for the suggestion!
