### ISSUE TITLE
[GR-40455] Getting unimplemented error with unsafe after upgrading to latest

### ISSUE THREAD

**Issue by agibsonccc** [oracle/graal#4837]
**Describe the issue**
This did not occur with graalvm 20.x.

More  context:

We are using a JNI library called javacpp which is at least one source of the unsafe usage. Is there something we should be doing differently for the build for 22.x?

Edit: My guess is this is due to something invoking unsafe at build time causing an unimplemented error to be thrown? It's trying to load the unsafe plugins. I'm not sure what's invoking it yet but was wondering if that could be a possible cause.

Edit 2:
It appears graalvm is triggering this behavior with JNI. Unsafe seems tangentially related here but does appear to be new behavior. I've triggered the debugger and can't figure out what method is triggering this yet. Any help there would be appreciated.

Stack trace here is below:
Full stack trace here:
https://gist.github.com/agibsonccc/9f2aefa3f5b462ddf3744785b971b7c3

Snippet here:
```
read:89] scope: ForkJoinPool-2-worker-3.InlineBeforeAnalysis.PEGraphDecode
    Context: StructuredGraph:59407{AnalysisMethod<com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_Unsafe_compareAndSwapInt_62ce9b4a90dec45bbff2e4786db99b07947d0e1a -> com.oracle.svm.jni.hosted.JNIJavaCallWrapperMethod@281e0e5a>}
    Exception raised in scope ForkJoinPool-2-worker-3.InlineBeforeAnalysis.PEGraphDecode: org.graalvm.compiler.debug.GraalError: unimplemented
        at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.unimplemented(GraalError.java:39)
```

**Comment by fniephaus** [comment]
Hi @agibsonccc,
This has been already been fixed on `master`, so please retry with the [latest dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases/latest). Anyway, I'm guessing you may experience another issue when you do this because you're using javacpp. Native Image uses a shadowed version of javacpp itself and due to another bug, you may see you builds failing due to some javacpp class starting a thread during build time. We are aware of the root cause and are working on a fix.

**Comment by agibsonccc** [comment]
Confirmed fixed in latest dev branch. Thanks for updating!
