### ISSUE TITLE
Expected performance of node

### ISSUE THREAD

**Issue by mlucool** [oracle/graal#486]
Hi,

What type of performance should we expect from node? I wrote a simple fib.js test and saw it is ~18x slower than the standard node.js on my machine.

Code tested via [benchmark.js](https://benchmarkjs.com):
```
function fib(n) {
  if (n <= 1) return 1;
  return fib(n - 1) + fib(n - 2);
}
```
Graal:
```bash
$ graalvm-ce-1.0.0-rc2/bin/node -v
v8.11.1
$ graalvm-ce-1.0.0-rc2/bin/node fib.js
fib20 x 615 ops/sec ±125.37% (44 runs sampled)
```
Native:
```
$ node-v8.11.1-linux-x64/bin/node -v
v8.11.1
$ node-v8.11.1-linux-x64/bin/node fib.js
fib20 x 10,900 ops/sec ±0.07% (96 runs sampled)
```

I have also run the example on the homepage of benchmark.js and found similar slowness (regex was 15x, indexOf was 64x, and match was 7x slower).

Is this expected? What do you think we'll see in the long run?

P.S. Very cool that it does just work and that I can call out to other languages from JS!

**Comment by wirthi** [comment]
Hi Marc,

thanks for trying out GraalVM; we appreciate you report your results!

GraalVM is expected to be in the ballpark of Node.js on peak performance, maybe a bit slower on average; depending on the kind of workload. GraalVM is better - often even faster than Node.js - on mostly algorithmic/arithmetic code; GraalVM is slower on code stressing Node.js internals a lot. In general, anything between 2x slower and 2x faster is not unlikely.

Note that GraalVM needs longer than Node.js to warmup. When writing a peak performance benchmark, give GraalVM a few iterations to warm up and compile the code, before starting to measure. We are working on improving compilation performance, but for now, this needs to be considered in a benchmark.

A 18x slowdown is definitly not expected and can be considered a bug. We are aware of the problem with benchmark.js already. There are three things to note:
* While your benchmark is only 4 lines, benchmark.js adds ~2800 lines that need to be compiled. On the other hand, the benchmark will by default only run 1-2 seconds - too little for Graal to jump in and optimize all of the relevant code.
* in addition, benchmark.js by default does not benchmark peak performance - its measurements include the time needed to compile ("warmup") the code.
* finally, given enough iterations to warmup, benchmark.js is exposing a bug in our compiler (deoptimization loop), causing performance to stay behind Node.js even then.

You can mitigate the warmup problem by measuring more iterations, or doing explizit warmup iterations upfront. The compilation problem will be fixed by us in a future release.

When using a self-written harness, results are significantly better for GraalVM (for serious benchmarking, please DO use a well-known harness though; this code here should just prove my point):

```
function fib(n) {
  if (n <= 1) return 1;
  return fib(n - 1) + fib(n - 2);
}

var N = 100;
var start = Date.now();
var sum=0;
for (var i=0;i<N;i++) {  sum += fib(30); }
var end = Date.now();
var delta = end-start;
console.log("result: "+sum);
console.log("total: "+delta+"ms, "+(delta/N)+"ms per iteration");
```
On my machine, GraalVM takes 11.66 iterations per ms, while Node 8.11.1 requires 10.1; lower is better, GraalVM is ~15% slower on that measurement (much better than 18x!). Note that this still includes the warmup; because of that, the result shifts to the favor of Node if you lower the iterations from 100 down to e.g. 10.
```
christian:~/$ GRAALVM/bin/node micro2.js
result: 134626900
total: 1166ms, 11.66ms per iteration
christian:~/$ NODE8/bin/node micro2.js
result: 134626900
total: 1010ms, 10.1ms per iteration
```

**Comment by mlucool** [comment]
Thanks for the detailed response. I'll watch for future benchmarks and improvements in compilation

**Comment by olegchir** [comment]
For history: I tried to run Octane2 (it's in my [forked repo](https://github.com/graalvm-community/graalvm-carbon)) and found that Node had dramatic slowdowns on different things like regexps.  Which of course isn't a big surprise. We discussed it in the gitter. By the way, can we SVM-compile JS code?

![](https://files.gitter.im/graalvm/graal-core/xzWs/______-______-2018-06-20-_-1.56.39.png)

**Comment by chumer** [comment]
>  can we SVM-compile JS code

Short answer no. 

Long answer: We can SVM compile the JS interpreter but not JS code itself. We are planning to allow some embedding of preparsed (maybe also preoptimized) JS sources in a JS interpreter native-image. That would mean that you create a specialized JS VM for your JS application. Cannot promise anything at this point, still only experiments.

**Comment by wirthi** [comment]
Hi,

I've sampled again and now compare our RC9 release with Node.js 10.9.0.

GraalVM CE RC9:
```
fib(30) try 1 x 33.13 ops/sec ±12.84% (36 runs sampled)
fib(30) try 2 x 29.57 ops/sec ±17.71% (41 runs sampled)
fib(30) try 3 x 36.50 ops/sec ±13.51% (45 runs sampled)
```

GraalVM EE RC9:
```
fib(30) try 1 x 75.84 ops/sec ±19.84% (48 runs sampled)
fib(30) try 2 x 76.04 ops/sec ±16.29% (53 runs sampled)
fib(30) try 3 x 85.80 ops/sec ±12.95% (58 runs sampled)
```

Node.js 10.9.0:
```
fib(30) try 1 x 94.76 ops/sec ±2.19% (69 runs sampled)
fib(30) try 2 x 94.84 ops/sec ±2.32% (71 runs sampled)
fib(30) try 3 x 97.12 ops/sec ±1.92% (70 runs sampled)
```

All this is run on a benchmark.js based setup (with the drawbacks as discussed above already). Higher numbers are better (operations per second).

Takeaway: 
* Node.js is 2.5x faster than GraalVM CE
* Node.js is 15% faster than GraalVM EE

Benchmark code:
```
var Benchmark = require("benchmark");
var suite = new Benchmark.Suite;

function fib(n) {
  if (n <= 1) return 1;
  return fib(n - 1) + fib(n - 2);
}

suite.add('fib(30) try 1', function() {
  fib(30);
})
.add('fib(30) try 2', function() {
  fib(30);
})
.add('fib(30) try 3', function() {
  fib(30);
})
.on('cycle', function(event) {
  console.log(String(event.target));
})
.run({ 'async': true });
```

GraalVM EE is on par with Node.js if I drop benchmark.js and use a hand-written benchmark harness. Seems there is still some optimization potential for GraalVM around benchmark.js.
