### ISSUE TITLE
SecretKeyFactory support

### ISSUE THREAD

**Issue by schmitch** [oracle/graal#514]
Hello, I tried to make a small tool to generate PBKDF2 Password Hashes with Java and wanted to try out native-image support.

However it looks like loading stuff via SecretKeyFactory is not supported?

My Code is something like that (Scala):
```
    val spec                  = new PBEKeySpec(password.toCharArray, salt.getBytes(StandardCharsets.UTF_8), iterations, digestSize)
    val skf: SecretKeyFactory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
    val hash: Array[Byte]     = skf.generateSecret(spec).getEncoded
    base64encoder.encodeToString(hash)
```

I also tried to use a reflect config to load some com.sun.crypto.provider classes (no luck so far):
```
[
  {
    "name": "com.sun.crypto.provider.PBKDF2KeyImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  },
  {
    "name": "com.sun.crypto.provider.PBKDF2HmacSHA1Factory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  },
  {
    "name": "com.sun.crypto.provider.PBKDF2Core",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  }
]
```

I can build the image, but it will fail at runtime with `Caused by: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA256 SecretKeyFactory not available`

**Comment by cstancu** [comment]
This should be fixed in https://github.com/oracle/graal/commit/76d043560571c3f6c4c0d76f89cb876451062251 which adds support for HTTPS and JCA security services. These features will be available in the rc7 realease. See [JCA-SECURITY-SERVICES.md](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md) for details. You need to run `native-image` with `--enable-all-security-services` for `SecretKeyFactory` services to be available.
