### ISSUE TITLE
[Feature Request / Idea] Add an Editor/IDE to the GraalVM package [this feature requestcan be closed at your discretion at any moment in time]

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/graal#5180]
Hey there GraalVM devs,

This issue can be closed at any moment in time. It is meant as an idea. I assume there may be resistance
to this, but either way it would be nice if a few GraalVM devs can read it - the rationale used herein may
not be completely invalid or pointless after all.

Proposal:

It is herein proposed that GraalVM offers an editor/IDE bundled with the default (or, in a "fat package" variant, similar to my older suggestion to bundle more goodies by default, including things such as upx; right now I download these from external sites so it's not a real issue for me but I'd love to have a "fat graalvm distribution" too).

Some folks may say "use vim, emacs or Visual Studio or Eclipse or IDEA-J". I get it. There are existing tools. They are good, no doubt.

But this proposal is not about these other tools. I'd more like a "graalvm world". Really, literally to use it for EVERYTHING.

I already used native-image for static commandline binaries on linux. That works very well. It's super fast.

On Windows it is a bit harder ... I struggle with cmd.exe too. So an IDE or editor for graalvm specifically would be nice.

"But you can use and adapt IDEA-J". Ok, I get it, but I'd prefer to stay in the graalvm world ideally.

The idea here is that the editor/IDEA would be super-fine-tuned towards graalvm. Ideally also simple. Perhaps one can
start with a simple GUI in JavaFX or something. And continue from there.

The editor/IDEA-J could also help make graalvm more popular after all.

Anyway. This is just an idea. Evidently one trade off is the time investment and time is a finite resource, I get it. But perhaps
one day at a later time, this idea and suggestion could be re-considered. Of course TONS of details are missing, I get it,
but I assumed that this has no realistic chance to be considered at THIS moment in time. But perhaps in the future. 
We can tie tons of functionality into an editor/IDEA e. g. simplify polyglot programming and what not. Note: I refer to
BASIC functionality, make this work and then expand from this point, so I am not suggesting a fully fledged IDE
from the get go. Just as a focus point for a later moment in time.

**Describe who do you think will benefit the most.**

GraalVM users and devs who may like to use an editor/IDE. ;)

**Describe alternatives you've considered.**
I just continue as-is via commandline compilation. This works fine, I use ruby to automatically insert appropriate flags and what not. But I'd also like to have an editor/IDEA specifically fine tuned for GraalVM usage.

Either way thank you for reading this!

**Comment by fniephaus** [comment]
Thanks for the suggestions. I totally understand your thinking but I believe there's one problem that you may have left out: developers are very opinionated when it comes to the tools that they use. Even within our team, developers use very different setups and IDEs. So I don't think there's a single "GraalVM world" as you said.

Instead of shipping an IDE prepared for GraalVM development, however, we already provide lots of great integrations: mx, our build tool, can [generate configurations for many Java IDEs](https://github.com/graalvm/mx#ide-configuration-generation). Also, we recently merged a contribution that added support for [dev containers, which in turn make it super easy to develop GraalVM in GitHub codespaces](https://twitter.com/graalvm/status/1559476511706697729).

Again, thanks for the suggestions. I hope you agree that providing good integrations that enable developers to use their preferred tools is better than focusing on a single IDE everyone is supposed to use.

**Comment by fniephaus** [comment]
Having said that, please let us know if you have any suggestions how we can improve any of these integrations and help you do more with GraalVM!
