### ISSUE TITLE
make reachable methods accessible from jclass by default in `-g` mode

### ISSUE THREAD

**Issue by vvlevchenko** [oracle/graal#5252]
**make reachable methods accessible from jclass by default in `-g` mode**

Please include the following information:

as discussed on meeting with @fniephaus and @olpaw for expression evaluation in debugger we need get JNI reference for methods and constructors for the later calling. This make expression evaluation safer in term of GC.

**Describe who do you think will benefit the most.**
Debuggers might need this feature 

**Describe alternatives you've considered.**
Currently our debugger use `call` gdb command, but it isn't safe because call made on alternative stack that breaks GC.

**Comment by peter-hofer** [comment]
I believe there are misunderstandings surrounding this topic. Calling methods like in #5184 does not need `jmethodID`s, it just needs the method's entry point address that is already known from the debug information. Using JNI calls instead of what I proposed does not solve any of the problems with alternative stacks in the debugger either. Making reachable methods (including constructors) accessible via JNI does not just populate a dictionary (which on its own can change application behavior and mask configuration problems). It leads to extra compilations of methods which would only be inlined where they are called (especially getters and setters) and introduces stub code, all of which contributes to image size.

With the approach from #5184, it's possible to invoke any method that is compiled on its own. Doing so still needs stub code because of the differences between native calling convention and our Java-to-Java calling convention, but the amount should be much smaller -- only one stub function per unique signature, where all parameter types map to one of `int`, `long`, `float` and `double`. Methods that are not compiled on their own cannot be invoked, but I was under the impression that this is an acceptable limitation.

**Comment by peter-hofer** [comment]
Closing as discussed.
