### ISSUE TITLE
[GR-41952] NPE in thread "Performance data" when using JFR on JDK19

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#5258]
When building a JDK19-based GraalVM from [current master](https://github.com/oracle/graal/commit/31728d24ba26b283217600fb211dc67f90b57e69), a simple JFR example fails with a NPE in thread "Performance data":
```
$ $GRAALVM_HOME/bin/native-image --enable-monitoring -m jdk.httpserver
$ ./jdk.httpserver -XX:+FlightRecorder -XX:StartFlightRecording="filename=recording.jfr"
Binding to loopback by default. For all interfaces use "-b 0.0.0.0" or "-b ::".
Serving /home/fniephaus/dev/tmp/jwebserver and subdirectories on 127.0.0.1 port 8000
URL http://127.0.0.1:8000/
Exception in thread "Performance data" java.lang.NullPointerException: [no exception stack trace available because exception is thrown from code that must be allocation free]
```

Could you take a look at this please, @roberttoyonaga?

**Comment by roberttoyonaga** [comment]
Hi Fabio! I think the problem should be fixed by: https://github.com/oracle/graal/pull/5214

There the performance data thread uses a `Thread.sleep` [here](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jvmstat/PerfManager.java#L195). I believe this is why it is throwing an exception with JDK19.

**Comment by fniephaus** [comment]
Hi Robert, thanks for checking...this is good news. :) Enjoy your weekend!

**Comment by roberttoyonaga** [comment]
Hi @fniephaus  I think this is fixed now. This PR had the thread sleep fix https://github.com/oracle/graal/pull/5807 that I mentioned above.

**Comment by fniephaus** [comment]
Thanks for the update, @roberttoyonaga. I can confirm this works now, great! :)
