### ISSUE TITLE
logback cannot get real hostname when nativeb binary run on other hosts,but always is  name of the host where native-image run build

### ISSUE THREAD

**Issue by enderwsp** [oracle/graal#5306]
how to resolve this , on graal 22.0.0.2

**Comment by oubidar-Abderrahim** [comment]
Hi, I'm not sure I understand the issue, please provide the following information:

1. What is the expected behavior Vs the actual behavior?
2. Did you test with the latest GraalVM version? if not, please do so (the latest currently is 22.3.0)
3. Did you generate the config files using our agent? if not, please do so by referring to this documentation: https://www.graalvm.org/22.0/reference-manual/native-image/Agent/
4. Could you please share a reproducer example that we can use to debug the issue?

**Comment by oubidar-Abderrahim** [comment]
Any updates?

**Comment by oubidar-Abderrahim** [comment]
Closed for inactivity. please reopen if you still face the same issue and share the requested information
