### ISSUE TITLE
Document how to run a Truffle on SubstrateVM

### ISSUE THREAD

**Issue by pmurias** [oracle/graal#540]
I'm trying to get by language NQP https://github.com/perl6/nqp/tree/truffle to work on SubstrateVM and I don't know how to configure native-image for because it's not documented.

**Comment by olpaw** [comment]
The easiest approach it to add a subfolder for your language in `<graalvm_root>/jre/languages` e.g. `mylang`. There you place the jar files that contain your truffle language implementation. e.g.
```
jre/languages/mylang/mylang-truffle-impl.jar
```
By having the subfolder `mylang` in `jre/languages` native-image understands that it contains jars of a truffle-language implementation named `mylang` and automatically adds the required image-builder arguments for truffle language building. Running
```
bin/native-image --language:mylang <fully-qualified-mylang-main-class>
```
would give you a native-image for your truffle language.

By adding a `native-image.properties` to you `mylang` subfolder you can further refine image building for you language. Take a look how e.g. `--language:llvm` works. Native-image will look into `<graalvm_root>/jre/languages/llvm/native-image.properties`
```
 This file contains native-image arguments needed to build sulong
# 

ImageName = lli

Requires = tool:truffle

JavaArgs = -Xmx3G

LauncherClass = com.oracle.truffle.llvm.launcher.LLVMLauncher
LauncherClassPath = lib/graalvm/launcher-common.jar:lib/graalvm/sulong-launcher.jar

Args = -H:MaxRuntimeCompileMethods=10000 -H:+AddAllCharsets
```
The `Requires` clause here is redundant because `Requires = tool:truffle` is the default for subfolders in `<graalvm_root>/jre/languages` anyway. Sometimes tough it makes sense to provide a `Requires` property e.g. if you implement a truffle-language that depends on another a truffle-language (like it is the case for ruby). The other properties are more interesting here:
* `ImageName` can be used to provide a default image-name
* `JavaArgs` allow you to pass additional Java arguments to the JVM that runs the image-builder.
* `Args` allow you to pass arguments to the image-builder. For serious truffle language implementations you will likely need this to specify an upper bound of runtime-compileable methods you expect you languages might have (`-H:MaxRuntimeCompileMethods=10000`)
* `LauncherClass` allows you to specify the default main entry point class that you would want have when your language is built.

**Comment by pmurias** [comment]
Thank you, it works for me

**Comment by eregon** [comment]
@olpaw I think it would be useful to add this documentation in the SVM repository, as that would be easier to find.
