### ISSUE TITLE
Graal jrunscript does not work

### ISSUE THREAD

**Issue by davidpcaldwell** [oracle/graal#546]
Graal version: 1.0.0-rc3 (Mac OS X)

Graal command:
jrunscript jrunscript.js

Script (jrunscript.js)
print("Hello, jrunscript!");

Graal result:
script error in file <system-init> : org.graalvm.polyglot.PolyglotException: ReferenceError: java is not defined
Exit status: 10

Expected result (JVM jrunscript)
Hello, jrunscript!

**Comment by iamstolis** [comment]
This problem has been fixed by https://github.com/graalvm/graaljs/commit/50995a398c53c022d86292040a8290eebff154aa i.e. it will be part of `rc5` build (hopefully). In case you switch to `rc4` build before that note that a different workaround is needed there: you can use `jrunscript -J-Dpolyglot.js.nashorn-compat=true`. Plain `jruncript` should work in `rc5` (once it is released).

**Comment by davidpcaldwell** [comment]
Actually, @iamstolis, it worked out-of-the-box:
```
Graal command:
js --js.nashorn-compat=true --jvm jrunscript.js

Script (jrunscript.js)
print("Hello, jrunscript!");


Graal result (1.0.0-rc4):
Hello, jrunscript!

Expected result (JVM jjs)
Hello, jrunscript!
```

**Comment by lscoughlin** [comment]
so like...
```

🦄 ~ $ uname -a
Darwin mbp-2016.attlocal.net 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64

🦄 ~ $ which jrunscript
/Library/Java/JavaVirtualMachines/graalvm-ee-java11-20.2.0/Contents/Home/bin/jrunscript

🦄 ~ $ jrunscript -e "print('hello world');"
script error in file <system-init> : org.graalvm.polyglot.PolyglotException: ReferenceError: java is not defined

```
