### ISSUE TITLE
graalvm breaks write once run anywhere promise

### ISSUE THREAD

**Issue by mk** [oracle/graal#5499]
**Describe the issue**
We're using `org.graalvm.js/js` at version `"21.3.2.1"` as a maven dependency to execute JavaScript also in regular (non-graalvm) JDKs.

This works everywhere **except** on the latest graalvm. The problem seems to be that GraalVM refuses to use the declared dependency on `org.graalvm.js/js`. The problem goes away with a manual install of `gu install js`.

Is there a switch to let GraalVM use the declared dependency over the (missing) built-in one without asking my users to perform a manual install?

**Steps to reproduce the issue**

This repro is built using Clojure which needs to be [installed](https://clojure.org/guides/install_clojure). I hope that doesn't obfuscate the problem here but if it does I can also provide a repro in plain Java. 

1. `git clone https://gist.github.com/mk/52bbfec146d01b56abc83764b35ab1a3 graal-js-repro; cd graal-js-repro`
2. `clojure -J-Dclojure.main.report=stderr -X graal-js-repro/build-context`

**Describe GraalVM and your environment:**
 - GraalVM version **GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08)**
 - JDK major version: **19**
 - OS: **macOS Monterey**
 - Architecture: **aarm64**

**More details**
```
Execution error (IllegalArgumentException) at com.oracle.truffle.polyglot.PolyglotEngineException/illegalArgument (PolyglotEngineException.java:131).
Could not find option with name js.esm-eval-returns-exports.
```
Full stacktrace
https://gist.github.com/mk/52bbfec146d01b56abc83764b35ab1a3#file-stacktrace-txt

**Comment by kristofdho** [comment]
As of GraalVM 22.2, JS is not bundled in the default installation anymore: https://www.graalvm.org/release-notes/22_2/#platform-updates
The correct solution is as you put it, to run `gu install js`.
It is also not possible to "let GraalVM use the declared dependency over the missing built-in one" because what you get from maven is just an API layer to access the JS engine, not the entire engine itself. Hence why you still need to run `gu`.

**Comment by mk** [comment]
> It is also not possible to "let GraalVM use the declared dependency over the missing built-in one" because what you get from maven is just an API layer to access the JS engine, not the entire engine itself.

Then I don't understand how this works on non Graal JVMs.

Is there a way to improve the error message to point users in the right direction? As you can see in https://github.com/nextjournal/clerk/issues/296 this isn't very obvious right now.

**Comment by oubidar-Abderrahim** [comment]
Hi @woess could you please check this issue.

**Comment by mk** [comment]
Looks like the only short-term solution is for me to catch and rethrow the `IllegalArgumentException` and prompting my users to `gu install js` in case they're on GraalVM. I still wish this was solved properly in GraalVM. 

Is checking if the `"java.vendor"` system property contains `GraalVM` a future-proof way for me to perform this check?

**Comment by sgammon** [comment]
@mk I think that property may vary with EE and CE (I remember seeing `"Oracle"` as the vendor...)

**Comment by mk** [comment]
@sgammon then checking this property isn’t so well suited… Any other way you can recommend to detect GraalVM?

**Comment by sgammon** [comment]
@mk I am not sure this will apply to your case, but I have been using [Gradle toolchains](https://docs.gradle.org/current/userguide/toolchains.html) from a plugin. I halt the build if the `vendor` is not set to either`GRAALVM` or the string `"Oracle"` (but `"Oracle"` is only eligible if the user opts in to GraalVM EE support via a special flag).

This has been okay for us, it does yield a few contributors asking how to install JS (we direct them to run `gu install js` and that's that). I agree, a more reliable detection mechanism would be welcome.

**Comment by woess** [comment]
I agree we should try to provide a better error message in this case. By the way, without the option, the error message is more useful (but maybe not obvious enough):
`A language with id 'js' is not installed. Installed languages are: [].`

If you just want to check if JS is installed/available, you could probably use sth like this:
```java
Engine.newBuilder().build().getLanguages().containsKey("js")
```
And then direct the user to install JS by running `gu install js`.

**Comment by mk** [comment]
@woess thanks for this.

To check if I'm running on GraalVM I now leaning towards querying the runtime to find out if `org.graalvm.polyglot.Engine` comes from a jar or is a jdk built-in (on Graal).

```clojure
(.getCodeSource (.getProtectionDomain org.graalvm.polyglot.Engine))
;; => #object[java.security.CodeSource 0x39140a14 "(jrt:/org.graalvm.sdk <no signer certificates>)"]

(.getCodeSource (.getProtectionDomain org.graalvm.polyglot.Engine))
;; => #object[java.security.CodeSource 0x10869e92 "(file:/Users/mk/.m2/repository/org/graalvm/sdk/graal-sdk/21.3.2.1/graal-sdk-21.3.2.1.jar <no signer certificates>)"]
```

Do you think that's a good check?

I'd still prefer it if it would be possible to fall back to the polyglot engine from the jar if the user doesn't have the `js` language installed. @woess can you help me understand why this is not an option? I believe this would be the most user friendly option going forward.

**Comment by woess** [comment]
> Do you think that's a good check?

@mk sounds like that could be a viable approach. That is of course assuming someone doesn't build their own JDK image including these modules, but I guess that's not much of a practical concern.

It is indeed possible to load js from the maven dependency by circumventing GraalVM's language class loader:
e.g. `clojure -J-Dgraalvm.locatorDisabled=true -J-Dclojure.main.report=stderr -X graal-js-repro/build-context` works for me.
However, this is not a supported way of running GraalVM and I can't recommend this for production use (use at your own risk!). It will still use the built-in modules (org.graalvm.sdk etc.) instead of the jars afaik, and things will very likely break if there's a version mismatch between GraalVM and JS (i.e. not user-friendly either). You also don't get the class loader isolation you'd normally get from GraalVM.

It's not the first time we get this feedback and we've already been thinking for a while about ways to make the deployment more seamless in the future, so that ideally you could just pull the required dependencies from maven. It's not clear yet when or how that will happen, once we have concrete plans, we'll share them.

**Comment by zenbones** [comment]
Any progress on adding graalvm languages by including an appropriate set of maven dependencies? Maybe thought has gone into this over the last year and a half?

**Comment by sgammon** [comment]
@zenbones yes, that's how they work now

**Comment by woess** [comment]
yes, that's exactly how it works since 23.1; there's no more `gu` (or built-in language dependency), you simply include the required maven dependencies (see below) now and it should work™️.

Read more on the changes here: https://medium.com/graalvm/truffle-unchained-13887b77b62c

```xml
<dependency> 
    <groupId>org.graalvm.polyglot</groupId> 
    <artifactId>polyglot</artifactId> 
    <version>${graalvm.version}</version> 
</dependency>
<dependency> 
    <groupId>org.graalvm.polyglot</groupId> 
    <artifactId>js</artifactId> 
    <version>${graalvm.version}</version> 
    <type>pom</type>
</dependency>
```

I think this issue therefore resolved and can be closed now.
