### ISSUE TITLE
[GR-42823] Add native-image API for defining built-in system-properties for image-runtime

### ISSUE THREAD

**Issue by olpaw** [oracle/graal#5557]
Based on @kristofdho's suggestion we should add an API method that allows users to define system-property key-value pairs that are automatically available at image runtime. This already exists internally as `ImageSingletons.lookup(SystemPropertiesSupport.class).initializeProperty("property.name", "value")` and should be made available though public API.

**Comment by olpaw** [comment]
Originally suggested here: https://github.com/oracle/graal/issues/4862#issuecomment-1303158555

**Comment by kristofdho** [comment]
`SystemPropertiesSupport` already contains functionality to compute defaults at runtime if they are dependent on the runtime environment of the user. It would be nice if that could also be exposed, as something like `initializeProperty(String key, Supplier<String> supplier)`.

**Comment by olpaw** [comment]
> It would be nice if that could also be exposed, as something like `initializeProperty(String key, Supplier<String> supplier)`

Exposing the variant with the supplier requires a very compelling use-case, as this goes beyond what you can do on the JVM. Also note that the supplier-variant has less trivial semantics. On first access to system-properties at runtime the suppliers are evaluated. ss @christianwimmer @wirthi

**Comment by kristofdho** [comment]
For our usecase, before we switched to GraalVM native-image we were using Excelsior JET. This did not allow you to pass JVM properties to the exe directly, and this used environment variables.
So for backwards compatibility, we need to take these env vars into account and set certain properties accordingly. An example of such a property is `java.awt.headless`.
A secondary usecase is that we need to modify/override the value of `java.library.path` to include additional subfolders of the installation directory in which the native-image exe is located. And because the native-image compiled through GluonFX fails if there is an older JDK8 on the classpath https://github.com/gluonhq/substrate/issues/940. Since only the initial resolution of the library uses this value, and transitive dependencies are handled by Windows and the PATH content, it suffices to overwrite `java.library.path` to just the dir of the exe and our additional subdirs.

For now we're doing everything in a helper class that sets all these properties accordingly, which we're calling as first thing in all our entrypoints.

**Comment by olpaw** [comment]
> For now we're doing everything in a helper class that sets all these properties accordingly, which we're calling as first thing in all our entrypoints.

There is nothing wrong with that :slightly_smiling_face:

**Comment by kristofdho** [comment]
> There is nothing wrong with that 🙂

No there isn't, except if an additional entrypoint is created, whoever is doing it has to be aware of the obligatory boilerplate required to make native-image work as well.

**Comment by olpaw** [comment]
Fixed since

commit a34907667a7ea95cb0a30e7699fae5c8251f97fb
Merge: 30272516c63 c434bfe8bb3
Author: Paul Wögerer <paul.woegerer@oracle.com>
Date:   Thu Dec 15 20:17:51 2022 +0000

    [GR-42823] Add native-image API for defining built-in system-properties for image-runtime #5557.
    
    PullRequest: graal/13313
