### ISSUE TITLE
The webSite Document need update--Access Environment Variables at Run Time 

### ISSUE THREAD

**Issue by chenliuyang1989** [oracle/graal#5641]
**Describe the issue**
there is one document Issue at website，The link is：https://www.graalvm.org/22.0/reference-manual/native-image/Properties/
The example  at website is not mateched with the Expected result。

![image](https://user-images.githubusercontent.com/4150132/208331798-cf5ce135-acc3-4978-ab31-ae2295e255f7.png)

A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

**Steps to reproduce the issue**

Please open the bellow link
https://www.graalvm.org/22.0/reference-manual/native-image/Properties/

**Describe GraalVM and your environment:**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by fniephaus** [comment]
Hi @chenliuyang1989, thanks for the issue. We've fixed this already, you just don't see the fix because you've been looking at the docs for GraalVM 22.0 (and we unfortunately can't backport all fixes like this). [Here's the latest version](https://www.graalvm.org/latest/reference-manual/native-image/guides/build-native-shared-library/).

/cc @olyagpl
