### ISSUE TITLE
[GR-52223] Components licensed under UPL: Copyright notice missing

### ISSUE THREAD

**Issue by ZwoCa** [oracle/graal#5723]
Hi,
I just noticed that the GraalVM components which are licensed under UPL do not contain a copyright notice in their LICENSE.md files, for example: https://github.com/oracle/graal/blob/master/truffle/LICENSE.md

I think this is problematic when one want's to correctly follow the license conditions, because the Universal Permissive License states "**The above copyright notice [...] must be included** in all copies or substantial portions of the Software.". Without an "above copyright notice" present, one is not able to comply with this condition.

Therefore, is there any chance to include a copyright notice in the LICENSE files of the UPL licensed components?

**Comment by wirthi** [comment]
Hi,

to clarify: you mean that we are missing the Oracle copyright attribution like

```
Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 ```
 
from the LICENSE.md file? That might either be an oversight, or it is intentional in order not to change the content of the LICENSE file and have it only contain the pure UPL text.

Note that we have the correct attribution in _every_ source code file (at the very least every Java file) - this is even checked by our CI. For all practical purposes, you can copy it from there.

-- Christian

**Comment by ZwoCa** [comment]
Hi Christian,

exactly, I mean this copyright attribution. According to https://opensource.org/licenses/UPL the attribution actually should be a part of the LICENSE.md file. Without it, the LICENSE.md seem a bit inconsistent, because it is not possible to follow the license condition it states.

Thank you for the hint with the Java files. However, different files will also state different years. So I think it's not an appropriate source for the copyright notice.

-- Sebastian

**Comment by fernando-valdez** [comment]
Thanks for reporting this @ZwoCa. 

@shaunsmith, do you think we need to explore this a little more?

**Comment by shaunsmith** [comment]
Yes, it seems we are missing the copyright notice at the top of the LICENSE.md file.

**Comment by olyagpl** [comment]
The copyright notice is added to the appropriate LICENSE.md files. Thank you for the notice.
