### ISSUE TITLE
Command line class initialization not being respected

### ISSUE THREAD

**Issue by guitcastro** [oracle/graal#5817]
**Describe the issue**

I am trying to compile a to native-image and explicit setting to initialize the class in runtime, but it's not being respected.

The class_initialization_configuration shows the following entry:

`org.apache.avro.file.XZCodec, RUN_TIME, from command line with 'org.apache.avro.file.XZCodec'`

However, the compilation fails with:
`
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.apache.commons.compress.compressors.xz.XZCompressorInputStream.<init>(java.io.InputStream). This error is reported at image build time because class org.apache.avro.file.XZCodec is registered for linking at image build time by command line
`

**Steps to reproduce the issue**

1. Create a quarkus projected and add ` io.quarkus:quarkus-confluent-registry-avro` as dependency
2. Try to build the image passing `--initialize-at-run-time=org.apache.avro.file.XZCodec'` as argument

**Describe GraalVM and your environment:**

openjdk version "17.0.5" 2022-10-18 LTS
OpenJDK Runtime Environment GraalVM 22.3.0 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM GraalVM 22.3.0 (build 17.0.5+8-LTS, mixed mode, sharing)

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this issue, I tried reproducing it using the getting-started example with the said dependency but I was able to build the image even after adding the flag above.

Could you please try with GraalVM 22.3.1 and see if the issue is still reproduced there? if yes, please share a reproducer code with steps that we can use to reproduce the issue.

also, provide information about what OS you're using, and why you need to initialize that class on runtime.

**Comment by oubidar-Abderrahim** [comment]
Hi, is there any updates?

**Comment by guitcastro** [comment]
@oubidar-Abderrahim Sorry, I removed the dependency and move on. I would love to take some time and try to create a reproducible  project. Unfortunately, this is now a 0 priority on the company, as we already found an workaround. So, the issue can be closed. If I find a time to re-created the issue I will re-open it. 

Anyway, thanks for the help!
