### ISSUE TITLE
How can i skip or exclude some classes When i  building native image ?

### ISSUE THREAD

**Issue by acodervic** [oracle/graal#5959]
A helloword image has 5 MB size, It is too big for me. When I checked the image, I found so many classes I never used ! Like java.util.regex . Is there has any way to skip(exclude) some classes when i  building native image ? I'm willing to take the risk of doing this. Thanks for graal team !
![image](https://user-images.githubusercontent.com/57204004/218381087-13cdf190-8311-4892-b244-23882c6c3226.png)

**Comment by fniephaus** [comment]
Thanks for the question, @acodervic. We don't allow users to cut out arbitrary parts of the JDK because it is simply too easy that you end up with a malfunctioning binary. We can internally do this with [`@Delete`](https://github.com/oracle/graal/blob/e76f6ccf9ab630f3b5368e53f69645219d8aa651/sdk/src/com.oracle.svm.core.annotate/src/com/oracle/svm/core/annotate/Delete.java) or [@Substitute](https://github.com/oracle/graal/blob/e76f6ccf9ab630f3b5368e53f69645219d8aa651/sdk/src/com.oracle.svm.core.annotate/src/com/oracle/svm/core/annotate/Substitute.java), which can remove or replace certain methods, fields, and even types of the JDK. This, however, requires you to modify Native Image and [build it from source](https://github.com/oracle/graal/blob/e76f6ccf9ab630f3b5368e53f69645219d8aa651/docs/reference-manual/native-image/contribute/DevelopingNativeImage.md).

Hope this helps!

**Comment by acodervic** [comment]
> Thanks for the question, @acodervic. We don't allow users to cut out arbitrary parts of the JDK because it is simply too easy that you end up with a malfunctioning binary. We can internally do this with [`@Delete`](https://github.com/oracle/graal/blob/e76f6ccf9ab630f3b5368e53f69645219d8aa651/sdk/src/com.oracle.svm.core.annotate/src/com/oracle/svm/core/annotate/Delete.java) or [@Substitute](https://github.com/oracle/graal/blob/e76f6ccf9ab630f3b5368e53f69645219d8aa651/sdk/src/com.oracle.svm.core.annotate/src/com/oracle/svm/core/annotate/Substitute.java), which can remove or replace certain methods, fields, and even types of the JDK. This, however, requires you to modify Native Image and [build it from source](https://github.com/oracle/graal/blob/e76f6ccf9ab630f3b5368e53f69645219d8aa651/docs/reference-manual/native-image/contribute/DevelopingNativeImage.md).
> 
> Hope this helps!

Thank you ! I will try it, Good luck to you !
