### ISSUE TITLE
output differs when same C code is run via  ` lli `   and via ` java ` command.

### ISSUE THREAD

**Issue by preetnitkkr** [oracle/graal#600]
Hi,

I am encountering a very weird issue. I have a cpp file something like - 
// main.cpp
```
extern "C" int main() {
std::string result = doSomething() // calls another classes' functions and does some stuff and returns it.
std::cout<<result<<endl;
}
```
There are around 8-10 files in the Cpp project. and i am creating the ` myapp.bc ` by compiling every files with:
` clang++ -O1 -c -emit-llvm -std=c++11 -stdlib=libc++ -I$GRAALVM_HOME/jre/languages/llvm -c -o file2.bc file2.cpp ` 
and then finally, linking all .bc files into one as:
`  llvm-link -o myapp.bc file1.bc file2.bc file3.bc file4.bc `

I also have a java code to run it:
```
import java.io.*;
import java.util.function.Function;
import org.graalvm.polyglot.*
public class Encoder {
        public static void main(String[] args) {
                try (Context context = Context.newBuilder().allowNativeAccess(true).build()) {
                        final Value library;
                        try {
                                library = context.eval(Source.newBuilder("llvm", new File("myapp.bc")).build());
                        } catch (IOException e) {                 }
                        final Value main = library.getMember("main");
                        main.execute();
}}}
```
I am checking the result in 2 different ways:
[1] ` javac Encoder.java && java Encoder `
[2] ` lli myapp.bc `
I am using lli that comes inside ` bin `of `$GRAALVM_HOME`
For the above kind of example, as per my understanding, both [1] and [2] should have given same output (from main() in cpp ). Because java and lli both (in my understanding) use Sulong implementation. Kindly correct me if that's not the case.

Problem: I am getting different output in [1] and [2] . Does someone have any idea why this might be happening ?

Thanks !

**Comment by preetnitkkr** [comment]
More information on this - 
running the same ` .bc ` file via lli several times gives same output - which is correct.
But,
running the same ` .bc ` file via java command several times give different output. - which is weird.

Could somebody please explain this.

**Comment by rschatz** [comment]
There is a difference between `library.getMember("main").execute()` and `library.execute()` (which is what the `lli` tool does). In C, the actual entry point of the program is not `main`, but `_start`. The `_start` function is usually defined in the standard library. When you run a normal executable, what happens is that the dynamic linker loads the executable and the standard library, and then jumps to the `_start` function. The `_start` function then does some initialization, and then calls `main`.

When you now do `library.getMember("main")`, this is roughly equivalent to doing `dlopen(...)`, then `dlsym(library, "main")` and then call this function. I'm not saying that's wrong, usually in the embedding scenario this is exactly what you want to do. But it might be a source of difference.

Another thing that might be different has to do with locales. Usually, programs start running in the `C` locale, and you have to call `setlocale` manually to get the locale from the environment. This is what happens when you use the `lli` launcher (without `--jvm` argument). But if you use the `java` launcher, the Java runtime already calls `setlocale` in its own startup, so the locale will be different.

Other than that, it's hard to tell without more information what the program is doing. Global variables (either in your program or in a library you're using) might be another source of difference.

**Comment by preetnitkkr** [comment]
Hi Ronald,
I have stripped down the code very much and uploaded at ( https://github.com/preetnitkkr/aztec ) in case it can provide some more information.

I did parallel debugging and found that workflow is differen at
` if ( ssum <= usableBitsInLayers) ` loop in Encoder::encode()  line 87.

could you please take a look ?

Thanks !

**Comment by preetnitkkr** [comment]
Hi Ronald, 

Sorry the back and forth. Looks like some issue with chrome inspector. putting print statements showed that flow is same on both side. Now, i am on to narrowing down the issue more.
Hopefully will be able to provide some more concrete on this.

Thanks !

**Comment by preetnitkkr** [comment]
Hi Ronald, 

I am able to narrow down the issue. A newly allocated 2d integer array in ` myapp.bc ` was not being initialised and used directly - which means that the behaviour is undefined. 
After initialising the memory in C code, output is coming same in both case - ` lli myapp.bc` and ` lli --jvm myapp.bc` 

Thanks for all the information you shared. It was very helpful indeed. 

Thanks !
