### ISSUE TITLE
My superior asks me why deployment to production takes 3 days? What should I tell him?

### ISSUE THREAD

**Issue by ghost** [oracle/graal#6647]
1. I used to program in php:
I make a change, save the file and the change is visible on the screen in the same second

2. then I switched to java:
compile time and only compile time
not to mention starting the server (glassfish, tomcat, websphere...).
half the time I watch the screens: compiling - building - deploying

3. then I switched to kotlin:
even longer compile time

4. then I switched to graalvm (native):
compiling takes 100% cpu and the computer is unusable during that time
not to mention the automatic generation of *-config.json files where the jvm runs for 3 days
native code is then generated from these files for another 3 days

if we want to speed it up, then it is better to create *-config.json files manually, but then each subsequent version of hibernate breaks the application startup
of course, the 3-day build passes, but the application reports an error when starting

I change one line of code and the application can be put into production in 3 days since native-compile takes that long

if there were more such good programmers like YOU who create such high-quality, fast and reliable technologies
and a little less US, bad programmers, who don't know how to use this smart technology

so much for environmental care and low CO2 emissions, when we have 1-line-of-code applications that have been generating for centuries
however, it's done by the computer, so it's not that important, right?

tell me how to explain to the boss that deploying the application takes 3 days, because native-compile takes that long?
can you speed up native-compile a bit so that it takes at least 2.5 days? that would help a lot

**Comment by Karm** [comment]
Hello @dick2tick,

> I used to program in php:
> I make a change, save the file and the change is visible on the screen in the same second

I feel you. The good news is that you can have exactly the same immediate dev experience with Java server side applications too these days, e.g. with Quarkus. (full disclosure: I contribute to Quarkus.)

```bash
$ curl -O -J 'https://code.quarkus.io/d?e=resteasy-reactive&cn=code.quarkus.io'
$ unzip code-with-quarkus.zip
$ cd code-with-quarkus/
$ ./mvnw quarkus:dev
```

Starts your server in a dev mode and all changes you do in your IDE to your Java code are almost instantaneously live. Before you do Alt-tab from your IDE to your browser, it's there.

> then I switched to java:
> compile time and only compile time
> not to mention starting the server (glassfish, tomcat, websphere...).
> half the time I watch the screens: compiling - building - deploying

As above, there is a lot of new options these days. The age of waiting a long time for a giant Maven run to complete and a long time for an app server to restart or to re-deploy an EAR archive is hopefully gone.

> then I switched to graalvm (native):
> compiling takes 100% cpu and the computer is unusable during that time
> not to mention the automatic generation of *-config.json files where the jvm runs for 3 days
> native code is then generated from these files for another 3 days

The compilation of a Java application with all its dependencies into a native executable is resource intensive and it takes time.
I usually develop in JVM mode and then compile and test in native. My usual build time is in single digit minutes. And like everyone, I'd love to see that number to go down.

If you are hitting something like:
```
=== Image generator watchdog is aborting image generation. To configure the watchdog, use the options
-H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
```
It would be great if you could share a reproducer, e.g. your app stripped of business logic and sanitized so as you are comfortable sharing it publicly. There is likely something wrong, a bug. Or there is some kind of an architectural misunderstanding, e.g. a Maven setup that builds the native-image of your app *for every single test case*, instead of building it once and running tests.

Cheers

**Comment by zakkak** [comment]
Closing as the reporter deleted their account.
