### ISSUE TITLE
Governing class init behavior via annotation

### ISSUE THREAD

**Issue by dmlloyd** [oracle/graal#683]
It would be kinda nice if one could govern class init behavior (eager, rerun, delay) by a class-level annotation.

**Comment by christianwimmer** [comment]
We thought about such an annotation, but the problem is where to define the annotation. The only place we have is in the `org.graalvm.nativeimage` API. This means that code that wants to use the annotation needs to have a dependeny on our API - and in that case it is probably better to just refactor the code and remove the need to initialize the class at run time. Or that code can also define a `Feature` and register the class from within  code using https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/RuntimeClassInitialization.java

**Comment by dmlloyd** [comment]
Naturally, however ``org.graalvm.nativeimage`` is present in the ``graal-sdk`` artifact, so I don't really see the problem?

**Comment by spavlusieva** [comment]
hi @dmlloyd , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
