### ISSUE TITLE
Is org.graalvm.nativeimage.c available inside of GraalVM?

### ISSUE THREAD

**Issue by dpetrick** [oracle/graal#694]
We're currently in the process of migrating our Scala application to SubstrateVM in order to compile it to a native binary. Since there is SubstrateVM incompatible code, we're replacing it with native code. We chose the `org.graalvm.nativeimage.c` to call out to that native code.

We can't move the entire application in one go, hence compiling with SubstrateVM from the get go is not possible. For this transitionary phase, we thought about letting our application run on GraalVM instead. However, for this to work we need the `org.graalvm.nativeimage.c` package to be available in GraalVM. We tried a few things, but we're unable to get our application up and running on GraalVM. The error is always: `Exception in thread "main" java.lang.UnsatisfiedLinkError: ...`. We made sure `graal-sdk.jar` is available on the classpath and tried loading the native library with `System.load`.

Is `org.graalvm.nativeimage.c` supposed to work with GraalVM?

Thank you!

**Comment by christianwimmer** [comment]
`org.graalvm.nativeimage.c` cannot work outside of native images because it 1) requires build-time steps (finding out struct offsets and struct sizes) that run at image build time, and 2) requires Graal intrinsics that the HotSpot interpreter does not understand.

There is project Panama that will provide a similar interface for a normal JVM, and once Panama is released we will support it for native images too. But it will probably be a while before Panama is ready.

So in the meantime, the only C interface that works everywhere is JNI.

**Comment by dpetrick** [comment]
Thanks for the clarification!
