### ISSUE TITLE
Error: Failed to find 'vcvarsall.bat' in a Visual Studio installation.

### ISSUE THREAD

**Issue by robozb** [oracle/graal#7121]
Dear All, 

What can I do to solve this problem?

![image](https://github.com/oracle/graal/assets/8656998/d98fe669-4607-4c03-8b23-774f99f43a0e)

Thank you!

Bela

**Comment by fniephaus** [comment]
In what location did you install VS? Native Image can only look for standard locations.

**Comment by fniephaus** [comment]
Do you have the build tools installed?
![](https://www.graalvm.org/docs/getting-started/img/windows-10-installed.png)
More info at https://www.graalvm.org/latest/docs/getting-started/windows/#prerequisites-for-native-image-on-windows

**Comment by robozb** [comment]
Dear @fniephaus , 

Thank You, I will check it out.

Bela

**Comment by robozb** [comment]
I installed into another folder. Thanks your help! I don't know that is the soultion becase of I changed the bulding environment to Ubuntu.

**Comment by zhaoxbmsdn** [comment]
I had this problem too.  I installed into another folder, and use _mklink_ to "C:\Program Files (x86)\Microsoft Visual Studio\VC" . 
unfortunately,It not work

**Comment by guwan** [comment]
I had this problem too。
![image](https://github.com/oracle/graal/assets/5222986/92eee069-c16d-459e-8f37-15e6ccb9a79c)

**Comment by nhoclahola** [comment]
I have same error but I have already installed build tools
![image](https://github.com/oracle/graal/assets/125201610/d6d8524d-16d0-4007-83bf-a18352276275)
Is it must be Windows 10 SDK instead of Windows 11 SDK?

**Comment by Zhu-junwei** [comment]
> Do you have the build tools installed? ![](https://camo.githubusercontent.com/ad91ae3090223cda97da1bc75cebf11706ddb8706b6cd95e9217b13ba45f3067/68747470733a2f2f7777772e677261616c766d2e6f72672f646f63732f67657474696e672d737461727465642f696d672f77696e646f77732d31302d696e7374616c6c65642e706e67) More info at https://www.graalvm.org/latest/docs/getting-started/windows/#prerequisites-for-native-image-on-windows

There is a problem with the current version provided by the official website,  in `graalvm-JDk-21_windows-x64_bin.zip \ graalvm-JDK-21.0.2 +13.1\lib\graalvm\ SVm-driver.jar \com\oracle\svm\driver\WindowsBui ldEnvironmentUtil.class` has a fixed path written in it。

![image](https://github.com/oracle/graal/assets/29745871/1747dcf7-478f-4913-9dfb-8c1f10e743a3)

I noticed that the code has since changed and the problem has been fixed, but no new versions are available.

**Comment by HuangDayu** [comment]
The problem lies in the default MVS path, which may occur if you install it in a custom path. reference resources: https://stackoverflow.com/questions/77840039/graalvm-failed-to-find-vcvarsall-bat-in-a-visual-studio-installation

```shell
The official code package is a fixed path, which has been changed, but without the latest release, graalvm-jdk-21.0.2+13.1 is now problematic.

https://github.com/oracle/graal/commit/bc2fbe9459f3a9150fe85e314c8a71afec628002#diff-967ec4e4a1a8ba71149a7f0a19524b48ad2e9f9b1a8ed53f0699f28859ab9c02

Try placing the installation path in the following location: C:\Program Files\Microsoft Visual Studio
```

The method I use is to create a folder soft link , Run in the super administrator terminal:

```shell
mklink /d "C:\Program Files\Microsoft Visual Studio" "F:\Microsoft Visual Studio"
```
