### ISSUE TITLE
native-image hangs when IPv6 disabled

### ISSUE THREAD

**Issue by netrikare** [oracle/graal#735]
It looks like native-image hangs when system has disabled IPv6 support (like putting` ipv6.disable=1` in grub, linux). The culprit appears to be  `JavaNetNetUtil.JavaNetNetUtilMD.IPv6_supported()` returning simply true=ipv6 always present which is obviously not the case. This function is used when computing a value returned by `JavaNetNetUtil.ipv6_available()` which in turn is used in `JavaNetNetworkInterface.netaddr.enumInterfaces()`. Enumeration of interfaces then returns null.

I noticed this since rc-6

As a workaround, when on an IPv6 disabled system, use:
`native-image --no-server` (during build) and additionally `-Djava.net.preferIPv4Stack=true` (during build, when your code uses networking functions)

**Comment by Peter-B-Kessler** [comment]
The native image builder assumes that IPv6 is always available on the platform, and bakes that assumption into the generated image.  You can override that assumption with `-Djava.net.preferIPv4Stack=true` when building an image, as you found.  

On all the platforms I have access to `AF_INET6` is defined (in a C header file).  Are you saying you have a platform where `AF_INET6` is not defined?

I have no access, during image building, as to whether `AF_INET6` is defined at the C level, since the image builder is just Java code, and the Java platform tries to hide the distinction between IPv4 and IPv6.  I could change `JavaNetNetUtilMD.IPv6_supported()` to return whether any of the interfaces on the image building platform is an IPv6 interface.  Would that address your issue?  In particular, for images built on platforms without IPv6 interfaces, the code in `JavaNetNetworkInterface.enumInterfaces()` would then not try to open an IPv6 socket at runtime, fail, and return `null`.

In any case, the value returned by `JavaNetNetUtil.ipv6_available()` is the value computed on the platform that builds the image, not on the platform that runs the image.  That is a separate issue.  That will be fixed when we replace all of our runtime substitutions for the native code from the JDK by using the JDK native code itself.

**Comment by Peter-B-Kessler** [comment]
It looks like I can use `DatagramChannel.open(ProtocolFamily)` to test for support for IPv6 on a platform, in the image builder.  Then there is just the usual problem of baking properties of the image building platform into the built image.

**Comment by netrikare** [comment]
> The native image builder assumes that IPv6 is always available on the platform, and bakes that assumption into the generated image. You can override that assumption with `-Djava.net.preferIPv4Stack=true` when building an image, as you found.

but as `native-image` defaults to using image-build server it falls back to using IPv6 to connect to it. Setting `preferIPv4Stack=true` explicitly does not work, only fallback to `--no-server`

> 
> On all the platforms I have access to `AF_INET6` is defined (in a C header file). Are you saying you have a platform where `AF_INET6` is not defined?

Of course not. It is all about runtime detection of os capabilities (which may be different than that on which image was built / or may change when aforementioned boot option is used). Original IPv6 detection routine in JDK takes into consideration many options (like opening socket, reading proc, etc)

> It looks like I can use DatagramChannel.open(ProtocolFamily) to test for support for IPv6 on a platform, in the image builder. Then there is just the usual problem of baking properties of the image building platform into the built image.

ok, so for now `DatagramChannel.open(ProtocolFamily)` would fix issue when building, but when I want to target non IPv6 platform I would still have to use (for now at least) `-Djava.net.preferIPv4Stack=true` as it statically puts ipv6_available result into generated binary, correct?

Ideal scenario would be to dynamically detect IPv6 presence on builder as well as on runner machine.

**Comment by Peter-B-Kessler** [comment]
I have pushed https://github.com/oracle/graal/commit/2290fdfcf0df4f3b19a0a0179d14a3f3b6e3b48c.  Is that enough of a fix for you to close this issue?  

We know that there are issues because of differences between the platform that builds the image and the platform that runs the image (including support for IPv6), but we are not planning on addressing those any time soon.  If you want to build on a platform that supports IPv6 and run on a platform that does not, use `-Djava.net.preferIPv4Stack=true`.

**Comment by netrikare** [comment]
> I have pushed [2290fdf](https://github.com/oracle/graal/commit/2290fdfcf0df4f3b19a0a0179d14a3f3b6e3b48c). Is that enough of a fix for you to close this issue?

sure, but change it to `DatagramChannel.open(ProtocolFamily).close()`  to avoid descriptor leak when call succeeds.

**Comment by Peter-B-Kessler** [comment]
I will add the `close()`.  Thanks for the suggestion.
