### ISSUE TITLE
Script-friendly links for GraalVM community edition

### ISSUE THREAD

**Issue by max-peroch** [oracle/graal#7424]
**Feature request**

According to https://www.graalvm.org/release-notes/JDK_17/ :
> Simplified the GraalVM package naming: it is graalvm-**ce**-jdk-\<java version\>_\<platform\>-\<arch\>, for example: graalvm-**ce**-jdk-17_macos-aarch64_bin.tar.gz.

Which is great and exactly what I am looking for, but on https://github.com/graalvm/graalvm-ce-builds/releases/ all I can find is links with the following format: `graalvm-community-jdk-17.0.8_macos-aarch64_bin.tar.gz`.

Can we please get a way to download CE packages for the latest versions, eg. 17 vs 17.0.8 ?

Thank you,

Max

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into it shortly

**Comment by oubidar-Abderrahim** [comment]
Hi, 

1. Regarding the release note; that was an error on our side. we updated the release note and now it reflects the correct naming.
2. For the possibility of having the URL without the specific version; after discussion with our release and QA teams, we decided not to adopt this approach as it will require multiple changes to our release jobs, CI/CD, and QA/testing.

**Comment by breun** [comment]
The lack of script-friendly URLs for GraalVM Community builds just got worse with the new naming schema introduced with GraalVM 25i1 / Graal 25.1.3, because now 3 version values are required to construct a URL for a particular OS/arch, like https://github.com/graalvm/graalvm-ce-builds/releases/download/graal-25.1.3/graalvm-community-jdk-25i1-25.0.3_linux-x64_bin.tar.gz (Graal version: 25.1.3, GraalVM version 25i1, JDK 25.0.3). This makes it pretty hard to use automated update tooling like Renovate or Dependabot to keep things up-to-date automatically, because the data sources used by those tools typically don't expose all of those values to the update process.

The Docker image tag looks like `25i1-25.0.3` for instance, so it doesn't contain the `25.1.3` version. Or can the `25.1.3` graal version be derived from `25i1-25.0.3` as `${graal_major}.${graal_innovation}.${jvm_patch}`?

**Comment by max-peroch** [comment]
It's interesting that `ghcr.io/graalvm/jdk-community:25` was not updated to point to the latest `25.0.3`
