### ISSUE TITLE
Can't change gc implementation for the native-image utility

### ISSUE THREAD

**Issue by danslapman** [oracle/graal#7496]
**Describe the issue**
According to [documentation](https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildConfiguration.md#memory-configuration-for-native-image-build) default `native-image` JVM options include `-XX:GCTimeRatio`, which is ParallelGC-specific option, which implicitly enables `UseParallelGC` option. Unfortunately, it means that user is unable to use other (e.g. G1GC) for native-image.

**Steps to reproduce the issue**
Just run any `native-image` build with `-J-XX:+PrintFlagsFinal`, it will show
```
...
[info]      bool UseParallelGC                            = true                                      {product} {command line}
...
```
Passing `-J-XX:+UseG1GC` to `native-image` causes
```
[info] Error occurred during initialization of VM
[info] Multiple garbage collectors selected
```

**Describe GraalVM and your environment:**
 - GraalVM version: **Java(TM) SE Runtime Environment Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14)**
 - JDK major version: **Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14, mixed mode, sharing)**
 - OS: **macOS Big Sur**
 - Architecture: **x64**

**Comment by SergejIsbrecht** [comment]
What are you trying to do?

If you want to overwrite the GC policy of the HOST JVM, which is used to generated a native binary, than this is probably not possible, because the ParallelGC-Option is already used. Passing params with `-J` will be used to configure the HOST JVM.

If you want to to define the G1 GC as your GC policy in the generated native binary, you have to pass following parameter:
```
native-image --gc=G1 
```
(https://www.graalvm.org/latest/reference-manual/native-image/optimizations-and-performance/MemoryManagement/)

Please note, G1 is only available in an Oracle GraalVM or EE distribution.

**Comment by danslapman** [comment]
>What are you trying to do?

I'm trying to use G1 as GC for the host JVM. The reason motivated me to do that is free github runners have only 7GB of available memory and it forces me to limit heap for the native-image. Here is example of my build: https://github.com/leviysoft/mockingbird/actions/runs/6310210076/job/17131774660. A huge amount of time spent on garbage collection: `422.0s (36.5% of total time) in 439 GCs | Peak RSS: 5.78GB | CPU load: 1.89`. I just want to follow advice from build log (`Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.`)

**Comment by danslapman** [comment]
>this is probably not possible, because the ParallelGC-Option is already used

This is exact reason for opening this issue. I think any defaults should be overridable

**Comment by oraluben** [comment]
The parallel gc is specified in https://github.com/oracle/graal/blob/9e420a8a11035a6e89aa09e91f2e2e94156fd191/substratevm/mx.substratevm/mx_substratevm.py#L1339. It also mentioned that "native image generation is a throughput-oriented task"

You can try to change and build graal from source to make it effect. If you observe significant difference, I think the team might consider to add control to the gc during native image generation.

**Comment by christianhaeubl** [comment]
Please note that the relevant warning is printed by the tool `sbt` and not by native image.

When building a native image, we explicitly configure the HotSpot VM so that it uses the parallel GC (the image build is a throughput-oriented task, so the parallel GC is a better fit than G1). There should not be any need to change the GC to G1.

If you want to give G1 a try anyways, then you need to disable the parallel GC explicitly before enabling G1: `-J-XX:-UseParallelGC -J-XX:+UseG1GC`
