### ISSUE TITLE
Why has the 'gu' binary been removed from graalvm releases, is there an alternative?

### ISSUE THREAD

**Issue by ashesfall** [oracle/graal#7571]
**Describe the issue**
After installing (on linux x64, mac aarch64, etc) from https://github.com/graalvm/graalvm-ce-dev-builds/releases
None of these contain the 'gu' binary that I have used in the past to install and update other graalvm components and tools.
I have looked all over for an explanation either of how to obtain 'gu' separately or perform the same operations without it, and there is nothing anywhere. Most graalvm documentation, even some updated quite recently, refers directly to 'gu'. Recent release notes don't appear to explain this either.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Download and unpack the graalvm release
2. Check the /bin directory for 'gu', which is no longer available

**Describe GraalVM and your environment:**
 -  graalvm-community-openjdk-21+35.1
 - JDK major version: 21
 - OS: Amazon Linux2
 - Architecture: x64

**Comment by fniephaus** [comment]
Hi @ashesfall, please take a look at https://github.com/oracle/graal/issues/6855. Feel free to get in touch if you have any questions!

**Comment by ashesfall** [comment]
Thank you, I'm glad to finally see the explanation somewhere. It would be great if this was broadcast more clearly (or if an explanation of the change was displayed by the old 'gu' when running commands like 'update' or 'install'). It was very hard to figure out what was going on.

**Comment by fniephaus** [comment]
Apologies for the inconvenience, @ashesfall. We have announced this in different places, including [the community roadmap](https://github.com/orgs/oracle/projects/6). We also planned to ship [a script that print a migration warning](https://github.com/oracle/graal/blob/cd56611004b5dc597896a699aef6a41e6bcd3807/vm/mx.vm/gu-deprecated), but unfortunately, the script was not included in the release due to misconfiguration.
