### ISSUE TITLE
Document deployment dependencies for native image

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/graal#7747]
**Describe the issue**
On Windows, I had to install the [Microsoft Visual C++ 2015-2022 Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) to get my native image working on a host other than the one I built the image on. I assumed native images didn't have any deployment dependencies. It would be good to mention these in [Getting Started with Native Image](https://www.graalvm.org/latest/reference-manual/native-image/).

**Steps to reproduce the issue**
* create a native image (e.g. [this one](https://www.graalvm.org/latest/reference-manual/native-image/#from-a-class))
* attempt to run it on a host without the Visual C++ Redistributable (e.g. a fresh Windows 11 installation)

Expected: prints the hello world message
Actual: exits with code -1073741515 and doesn't print anything

**Describe GraalVM and your environment:**
 - GraalVM version: native-image 21.0.1 2023-10-17
 - JDK major version: 21
 - OS: Windows 11 (Microsoft Windows 10.0.22621)
 - Architecture: AMD64

**More details**
@selhagani I've updated with the requested info

**Comment by selhagani** [comment]
Hi @anthonyvdotbe Could you please share a reproducer with me? Could you also share with me the version of graalVM, the host, and the OS version?

**Comment by selhagani** [comment]
Hi @anthonyvdotbe I have just tested on a fresh installation of windows and it worked just fine for me. On my end having Microsoft Visual C++ 2015-2022 Redistributable is not a requirement to run the executable.

**Comment by anthonyvdotbe** [comment]
So either our executables are different, or your installation of Windows somehow already contains the redistributable.

This is my executable (renamed to .zip because GitHub doesn't allow uploading .exe files):
[helloworld.zip](https://github.com/oracle/graal/files/13412701/helloworld.zip)

And below is a screencast of me reproducing the issue. The initial terminal window is on the host, to show the commands I ran to create the executable. Everything else is in a fresh Windows Sandbox (the only customization I did, is to make the host's Downloads folder accessible within the Windows Sandbox).

https://github.com/oracle/graal/assets/15714253/716191e4-cb6d-4442-9d7f-59edaa6414d6

**Comment by selhagani** [comment]
Actually your issue is indeed normal. You are required to have Visual Studio and Microsoft Visual C++(MSVC) installed on windows to run your application. It is also mentioned in the documentation. If you go to the [windows section of the documentation](https://www.graalvm.org/latest/docs/getting-started/windows/) You'll find that it is mentioned there.

**Comment by anthonyvdotbe** [comment]
I understand that Visual Studio et al. are required to *build* an application with native image. What is *not* documented, is that the resulting .exe is not self-sufficient. In other words: I cannot just send executables built with GraalVM to other people. I'll need to explain them how to install the Visual C++ Redistributable or create an installer to do it for them (and in that case, I could just as well use JDK's jlink and jpackage instead of GraalVM Native Image). This fact is *not* documented in the docs, so please reopen this issue.

**Comment by selhagani** [comment]
I get you now. I'll keep investigating on my end and I'll keep you posted. Thank you!

**Comment by selhagani** [comment]
Could you please specify if the environment you shared with me in the beginning is the one where you try to run your executable? if yes then could you share info of the environment where you built your native image? 
I would also like to get more detail about the error you are encountering. Could you please open event viewer on your windows machine then go to windows logs then find the error corresponding to your issue and send me the details of the error?

**Comment by anthonyvdotbe** [comment]
> Could you please specify if the environment you shared with me in the beginning is the one where you try to run your executable? if yes then could you share info of the environment where you built your native image?

No.

> I would also like to get more detail about the error you are encountering. Could you please open event viewer on your windows machine then go to windows logs then find the error corresponding to your issue and send me the details of the error?

To reproduce: open a [Windows Sandbox](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview), download the executable I attached above and change its extension to `.exe` again (or build the executable yourself if you don't trust the attachment), and try to run it.

**Comment by oubidar-Abderrahim** [comment]
- Visual C++ Redistributable or Visual Studio Build Tools are only required on the machine used to build the native image, they are not a requirement for running previously generated images.
- Native Windows-generated images are not statically linked, meaning they may need specific dependencies (DLL files) based on each use case. Usually, the native image builder extracts these DLLs and puts them in the same directory as you generated EXE file. 
- If installing Visual C++ Redistributable or Visual Studio Build Tools resolves the issue, that does not mean they are necessary for a native image to run, that could also indicate that the missing DLL was installed via these tools.
- Since our team was able to run a HelloWorld example on a freshly installed Windows machine without the need to install any extra dependency, I'm afraid we won't be able to assist you unless you're willing to help us. You can do so by sharing what are the exact version of Windows used for building the image and for running it (I'm assuming what was provided in the description above is the running environment, so kindly provide details on the build environment)
- We do not accept unknown executables for reproducing issues for security reasons, please whenever you need to share a code with us, create a public repository on Github and share with us the steps to build or share the code directly if it's small enough.
- Finally, please keep in mind that GraalVM is an open-source project. As such, you are more than welcome to contribute code and improve our documentation. We also welcome feedback and suggestions from the community, as long as it is [respectful](https://www.graalvm.org/community/conduct/).

**Comment by anthonyvdotbe** [comment]
> * Visual C++ Redistributable or Visual Studio Build Tools are only required on the machine used to build the native image, they are not a requirement for running previously generated images.
> * Native Windows-generated images are not statically linked, meaning they may need specific dependencies (DLL files) based on each use case. Usually, the native image builder extracts these DLLs and puts them in the same directory as you generated EXE file.

In my case, following the instructions to build a helloworld executable [from a class](https://www.graalvm.org/latest/reference-manual/native-image/#from-a-class), it doesn't.

> * If installing Visual C++ Redistributable or Visual Studio Build Tools resolves the issue, that does not mean they are necessary for a native image to run, that could also indicate that the missing DLL was installed via these tools.
> * Since our team was able to run a HelloWorld example on a freshly installed Windows machine without the need to install any extra dependency, I'm afraid we won't be able to assist you unless you're willing to help us. You can do so by sharing what are the exact version of Windows used for building the image and for running it (I'm assuming what was provided in the description above is the running environment, so kindly provide details on the build environment)

Let me clarify what I mean with "freshly installed Windows machine": a Windows installation using [this ISO](https://www.microsoft.com/en-us/software-download/windows11/) or a Windows Sandbox instance.
The Windows versions are as given above, both on the host where I'm building and on the host where I'm running.
 
> * We do not accept unknown executables for reproducing issues for security reasons, please whenever you need to share a code with us, create a public repository on Github and share with us the steps to build or share the code directly if it's small enough.

I'm just using the one from [the guide](https://www.graalvm.org/latest/reference-manual/native-image/#from-a-class):

```
Save this code into file named HelloWorld.java:

 public class HelloWorld {
     public static void main(String[] args) {
         System.out.println("Hello, Native World!");
     }
 }

Compile it and build a native executable from the Java class:

javac HelloWorld.java
native-image HelloWorld
```

> * Finally, please keep in mind that GraalVM is an open-source project. As such, you are more than welcome to contribute code and improve our documentation. We also welcome feedback and suggestions from the community, as long as it is [respectful](https://www.graalvm.org/community/conduct/).

**Comment by selhagani** [comment]
The issue you're facing is pretty much the same as [This one](https://github.com/oracle/graal/issues/1762).
Basically, this behavior is to be expected so it isn't really a bug but more of a new feature. Feel free to follow up on any further discussions about this on the first issue.

**Comment by kristofdho** [comment]
@selhagani closing this as expected, not a bug, and a new feature at the same time is not the right resolution if the entire premise of the issue is to point out that this is not documented anywhere.
Is it expected to be undocumented?
Is it a feature that this is undocumented?
I doubt it.
