### ISSUE TITLE
The use of `-H:ThrowMissingRegistrationErrors` results in different behavior

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#7763]
**Describe the issue**
Using `-H:ThrowMissingRegistrationErrors` changes the items registered for reflection. More specifically it results in automatic registration of items using invocation plugins:

https://github.com/oracle/graal/blob/802c40d1cf9d10050188c25d0458282110c4fddb/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/snippets/ReflectionPlugins.java#L307-L320

These invocation plugins should either be always enabled or never. Their activation should not rely on `-H:ThrowMissingRegistrationErrors`.

The current behavior is confusing and misleading as building and testing with `-H:ThrowMissingRegistrationErrors` exhibits a different behavior and also doesn't indicate that there are missing registrations when not using it.

cc @vjovanov 

**Steps to reproduce the issue**
```
cat > Test.java <<EOF
public class Test {
    public static void main(String[] args) {
        System.out.println("Hello World!");
        Class<?>[] classes = Test.class.getClasses();
        for (Class<?> clazz : classes) {
            System.out.println(clazz.getName());
        }
    }

    public class InnerClass1 {
    }

    public class InnerClass2 {
    }
}
EOF
javac Test.java
java Test
```

prints as expected: 

```
Hello World!
Test$InnerClass2
Test$InnerClass1
```

```
native-image Test
./test
```

prints:

```
Hello World!
```

while:

```
native-image -H:ThrowMissingRegistrationErrors= Test
./test
```

prints:

```
Hello World!
Test$InnerClass2
Test$InnerClass1
```

**Describe GraalVM and your environment:**
 - GraalVM version: **GraalVM CE 21+35.1**
 - JDK major version: **21**
 - OS: **Fedora 38**
 - Architecture: **AMD64**

**Comment by vjovanov** [comment]
This is a very good point, thanks! I don't see why we would not enable this in both modes.

**Comment by zakkak** [comment]
> I don't see why we would not enable the proofs in both modes.

The only reason I can think of would be some potential binary size increase, but in my book these registrations are totally justified. I am +1 on enabling them by default.

**Comment by loicottet** [comment]
The reason we took this decision is to not break the current behaviour where calling `Class.getDeclaredMethods`, for example, would return only the subset of methods that were registered for reflection and not the full list. This makes the plugins tightly linked to the reflection behaviour changes, which is why they have to be placed behind the same flag.

To be able to prepare the transition to `-H:ThrowMissingRegistrationErrors`, you can use it in combination with the `-H:MissingRegistrationReportingMode=Warn` option, which will include the plugins, but will only print a warning instead of throwing a `MissingReflectionRegistrationError` at run-time.
