### ISSUE TITLE
Inherited static field not found at build time/"Discovered unresolved field during parsing"

### ISSUE THREAD

**Issue by dmlloyd** [oracle/graal#8016]
**Describe the issue**

According to [JVMS 17 §5.4.3.2](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-5.html#jvms-5.4.3.2), searching for fields involves recursively traversing superinterfaces and superclasses. However, we have found an issue (quarkusio/quarkus#37598) with searching superclasses for static fields under GraalVM, specifically the class parser which misses them.

**Steps to reproduce the issue**
Try a simple Java file which inherits a static field. In our case, the user included the `jboss-logmanager` project, and referenced the `java.util.logging.Level#ALL` field by way of the subclass `org.jboss.logmanager.Level`. The subclass does not define the field, so the resolution relies on the JVM recursing to the superclass. Examine the test file via `javap` to ensure that the field reference is targeting the subclass.

There is a more comprehensive reproducer in quarkusio/quarkus#37598.

**Describe GraalVM and your environment:**
The original issue was produced via Mandrel: `Java version: 21.0.1+12-LTS, vendor version: Mandrel-23.1.1.0-Final`

I thought we had previously reported this bug but I couldn't find any evidence/history of such a report, so I guess I hallucinated it.

**Comment by solaanan** [comment]
Hello @dmlloyd, thank you for reporting this issue. We will be taking a look at this shortly.

**Comment by christianwimmer** [comment]
@dmlloyd the native image generator uses the class file loader and field/method/class resolution code from the hosting HotSpot VM, via JVMCI. So while it is always possible that there is a bug, it is not the most likely case. If you have a simple Java file to reproduce the problem, please send it to me (together with the .class files for completeness).

For the failing Quarkus reproducer, I would say that the problem is wrong bytecode produced by Quarkus. The unresolved field is the result of the following bytecode:

```
io.quarkus.runtime.generated.Target_org_jboss_logmanager_Logger.isLoggable(Unknown Source) [bci: 11, intrinsic: false]
  11: getstatic     #2          // org.jboss.logmanager.Level.ALL:org.jboss.logmanager.Level
```

The referenced field is supposed to be of type `org.jboss.logmanager.Level`. That field does not exist in any superclass, because the superclass `java.util.logging.Level` defines the field `ALL` of type `java.util.logging.Level` - matching the name but not matching the type. The existing field in the superclass is therefore not a valid resolution for this field lookup.

**Comment by dmlloyd** [comment]
> The referenced field is supposed to be of type `org.jboss.logmanager.Level`. That field does not exist in any superclass, because the superclass `java.util.logging.Level` defines the field `ALL` of type `java.util.logging.Level` - matching the name but not matching the type. The existing field in the superclass is therefore not a valid resolution for this field lookup.

Ah, that's likely the problem, good catch. I guess I need new glasses. I'll confirm that this is the issue, thanks.

I thought it was a pretty strange and unlikely thing... :)

**Comment by dmlloyd** [comment]
Looks like the problem is on our end after all. Thanks for the hint. :+1:
