### ISSUE TITLE
Advertised languages (Python, Ruby, R...) of GraalVM polyglot not available with gu in JDK 17 GraalVM 23.0

### ISSUE THREAD

**Issue by fabrice-ducos** [oracle/graal#8043]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **23.0.2** (obtained from graalvm-jdk-17.0.9+11.1/release)
 - CE or EE: **CE**
 - JDK version: **JDK17**
 - OS and OS Version: **Ubuntu 22.04.2 LTS**
 - Architecture: **x86_64**
 - The output of `java -Xinternalversion`:
```
 Java HotSpot(TM) 64-Bit Server VM (17.0.9+11-LTS-jvmci-23.0-b21) for linux-amd64 JRE (17.0.9+11-LTS-jvmci-23.0-b21), built on Oct 11 2023 14:34:18 by "buildslave" with gcc 11.2.0
```

**Have you verified this issue still happens when using the latest snapshot?** No
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Describe the issue**
I am experimenting the `gu` tool for testing scripting languages (Python, Ruby, R, Javascript...) in GraalVM.

I know that `gu` is deprecated and was removed from GraalVM 23.1. But currently, there is no easy-to-use and well documented alternative, as described in this [issue](https://github.com/oracle/graal/issues/8042).

Therefore, I am sticking to GraalVM 23.0 and to `gu` for now.

**Code snippet or code repository that reproduces the issue**
```
$ echo $JAVA_HOME
/opt/graalvm/graalvm-jdk-17.0.9+11.1
$ which gu
/opt/graalvm/graalvm-jdk-17.0.9+11.1/bin/gu
$ gu available

Downloading: Artifacts catalog from gds.oracle.com
Skipping ULN EE channels, no username provided.
Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
espresso                 23.0.2              Java on Truffle               Supported                     gds.oracle.com
espresso-llvm            23.0.2              Java on Truffle LLVM Java librSupported                     gds.oracle.com
icu4j                    23.0.2              ICU4J                         Supported                     gds.oracle.com
jipher                   23.0.2              Jipher JCE Provider           Supported                     gds.oracle.com
js                       23.0.2              Graal.js                      Supported                     gds.oracle.com
llvm                     23.0.2              LLVM Runtime Core             Supported                     gds.oracle.com
llvm-toolchain           23.0.2              LLVM.org toolchain            Supported                     gds.oracle.com
native-image-llvm-backend23.0.2              Native Image LLVM Backend     Early adopter (experimental)  gds.oracle.com
nodejs                   23.0.2.1            Graal.nodejs                  Supported                     gds.oracle.com
regex                    23.0.2              TRegex                        Supported                     gds.oracle.com
visualvm                 23.0.2              VisualVM                      Supported                     gds.oracle.com
```

No entry is to be found for Python, Ruby, R... Therefore these languages cannot be installed with this version of `gu.`

**Expected behavior**
Maybe what occurs is the expected behaviour, but from a newbie's perspective, one would expect to find the advertised scripting languages of GraalVM, including Python, Ruby, R,...

Have their support been removed (if so, since which version?) or are they available only on certain conditions? Any pointer to relevant documentation would be welcome.

**Comment by fniephaus** [comment]
Hi @fabrice-ducos,

The GraalVM version you've tried to use is a patch update, which does not include any experimental features or languages. Python, Ruby, R, and others are marked as such, so that's why they are not available. At this point, you have four options:

1. Use `17.0.8+9.1` of [Oracle GraalVM for JDK 17 from the archive](https://www.oracle.com/java/technologies/javase/graalvm-jdk17-archive-downloads.html).
  (*easy workaround but not recommended for production settings because older releases are lacking security fixes*)
2. Force install relevant languages manually by downloading the installables and using `gu -f -L ...`.
  (*can be a bit tedious*)
3. Build everything from source
  (*can be a bit tedious as well; CE only, you will loose Oracle GraalVM features*)
4. Upgrade to GraalVM for JDK 21
  (*`gu` is gone; [language runtimes are now Java libraries](https://medium.com/graalvm/truffle-unchained-13887b77b62c)*)

If you're looking for a quick workaround and want to try something out, I'd go with option 1. Otherwise, I'd look into option 4 as this is the new way to use GraalVM language runtimes.

Hope this helps!
-- Fabio
