### ISSUE TITLE
Memory leak in js code using hashmaps and high cardinality properties

### ISSUE THREAD

**Issue by victor-smirnov** [oracle/graal#832]
Memory leak in graal RC9 for code using javascript hash maps and high-cardinality properties like that:

```javascript
const UUID = Packages.java.util.UUID;

setInterval(() => {
    const a = {};
    a[UUID.randomUUID().toString()] = 1;
}, 1);
```

Memory starts growing until the heap is completely exhausted. This is a show stopper for most js applications.

![graaljs-heapdump](https://user-images.githubusercontent.com/15331945/49244750-8b4a6d00-f3de-11e8-95e5-c680bd010c32.png)

**Comment by wirthi** [comment]
Hi @victor-smirnov 

thanks for your report. The problem seems to be that our object model fails to detect this case and stores the keys in its transition map without ever collecting them. Our methods to prevent exactly that fail to to catch this specific case.

A workaround until we fix this is not to use random properties on objects; you could use a more array-like structure or use an ES6 Map object.

Best,
Christian

**Comment by victor-smirnov** [comment]
Thank you, Christian!

Unfortunately, all applications parsing real-life json files (JSON.parse()) are affected, because of unbounded cardinality of real-life data. Memory just doesn't leak so fast as with using UUIDs. For micro-benchmarks running on GraalVM we can avoid using problematic constructions, but it seems there is no workaround for existing data-processing applications.

Regards,
Victor

**Comment by jwatts-integrationtest** [comment]
Are there any updates on this issue?  Multiple RCs have been released (up to RC13 now) and I have to agree with Victor that most real-world use of Javascript would be affected by some way. In particular, this would include parsing arbitrary JSON or using Javsacript APIs that treat a Javascript object as a dictionary instead of using ES6 Map.

We're very excited and loving Graal but this is a showstopper for us.

**Comment by johnwatts** [comment]
Well that's embarrassing! I was doing some unrelated testing and posted under the wrong identity. I wrote the preceding comment.

**Comment by thomaswue** [comment]
And I thought you have a really good bot that almost talks like you ;). 

@wirthi Can you post an update?

**Comment by woess** [comment]
This issue will be fixed in RC14. Sorry for the delay.

**Comment by johnwatts** [comment]
Thank you for the excellent news and the very prompt response. I was only worried because of the time delay since the initial response in December.

**Comment by johnwatts** [comment]
It looks like it didn't ship in RC14. Should we expect it in RC15?

**Comment by woess** [comment]
The fix shipped in RC14 (forgot to mention it in the changelog).

Please give it a try.

**Comment by johnwatts** [comment]
Thank you very much! We're excited to try this out and the new libgraal.

**Comment by victor-smirnov** [comment]
Thank you Andreas! :)

**Comment by victor-smirnov** [comment]
Thank you, Andreas, again! I confirm that RC14 passes our memory leak tests. So I'm closing this issue for now.
