### ISSUE TITLE
Static init failure error reporting is not very useful

### ISSUE THREAD

**Issue by dmlloyd** [oracle/graal#843]
If you have enabled `ReportUnsupportedElementsAtRuntime`, or (now) `AllowIncompleteClasspath`, and static init for some class fails, you get a friendly error message about it.  However there are two problems:

* The exception given in the message is often going to be `ExceptionInInitializerError`, which does not presently include any useful message at all.  So most of the time the message tells you absolutely nothing about what failed.
* There is no stack trace given, so errors cannot be easily pinpointed.

In addition, it doesn't seem like `AllowIncompleteClasspath` should _always_ imply `ReportUnsupportedElementsAtRuntime`.  It is possible that I would for example want to support an incomplete class path for the purposes of run time code but still fail the build if a class init fails (even if it fails due to CNFE/NCDFE).  I can always opt those classes in to runtime reporting one by one if needed, or just add a try/catch, for example.

**Comment by cstancu** [comment]
@dmlloyd `AllowIncompleteClasspath` doesn't imply `ReportUnsupportedElementsAtRuntime`, they are separate options. If something goes wrong in a static initializer and _either_ of them is set then we print the warning message (which includes the message of the original error) and force run time initialization of the corresponding class. We will look into improving the error message, however we cannot show a meaningful stack trace since the initialization is triggered in our code by [a call to `UnsafeAccess.UNSAFE.ensureClassInitialized(clazz)`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ClassInitializationFeature.java#L352).

**Comment by dmlloyd** [comment]
Really the entire stack trace isn't needed: it'd just be a help to see *what* the exception really was, and maybe what line number it occurred on.  The rest of the call stack (below the `<clinit>` itself) isn't really of use but the rest of it definitely is!

**Comment by cstancu** [comment]
The behavior of the class initialization and the format of the error messages has evolved since this issue was open.
