### ISSUE TITLE
GraalVM crashes with "fatal error: Initial size of CodeCache is too small"

### ISSUE THREAD

**Issue by cmorgner** [oracle/graal#8504]
**Describe the issue**
GraalVM crashes with "fatal error: Initial size of CodeCache is too small", after running for about 2-3 weeks, producing hs_error.log.

**Steps to reproduce the issue**
Not easy to reproduce since it happens after a while on one of our production systems.

**Describe GraalVM and your environment:**
OpenJDK Runtime Environment GraalVM CE 22.2.0 (11.0.16+8) (build 11.0.16+8-jvmci-22.2-b06)
Host: Intel Xeon Processor (Skylake, IBRS), 8 cores, 30G, Ubuntu 20.04.3 LTS
Command Line: -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Duser.timezone=Europe/Berlin -Duser.country=US -Duser.language=en -Dfile.encoding=UTF-8 -Dorg.apache.sshd.registerBouncyCastle=false -Dorg.neo4j.io.pagecache.implSingleFilePageSwapper.channelStripePower=0 -Xms6g -Xmx6g -XX:+UseCodeCacheFlushing -XX:+UseNUMA -XX:+UseG1GC org.structr.Server

**More details**
[hs_err_pid3438833.log](https://github.com/oracle/graal/files/14478286/hs_err_pid3438833.log)

**Comment by dougxc** [comment]
Hi @cmorgner , this is fixed in GraalVM 22.3.1 (https://github.com/oracle/graal/commit/44ffa7e5844ad3cfad3f465719a75c81193d4c34).

The problem was that each libgraal isolate installed a new VM `RuntimeStub` for `org.graalvm.compiler.hotspot.stubs.Stub.code` for each instance of `org.graalvm.compiler.hotspot.stubs.Stub`. This resulted in the HotSpot code cache slowly filling up with redundant `RuntimeStub`s.

There's also a JDK fix to prevent Graal stub allocation from crashing the VM (https://bugs.openjdk.org/browse/JDK-8317273) but this should never be encountered as a result of the fix above.

**Comment by cmorgner** [comment]
Great, thank you!
