### ISSUE TITLE
Premature optimization for static final val when build native image.

### ISSUE THREAD

**Issue by guxingke** [oracle/graal#872]
```java
public static final String USER_DIR = System.getProperty("user.dir")
```
The USER_DIR val  always is the path where the native-image exec.

but adaptive of pkg call path.

**Comment by olpaw** [comment]
Hi @guxingke,
this behavior is by design. By default the static initializers of classes are executed at image buildtime unless you specify otherwise with e.g.
```
    --rerun-class-initialization-at-runtime
                          a comma-separated list of classes (and implicitly all of their
                          subclasses) that are initialized both at runtime and during image
                          building
```
For more info see blog article https://medium.com/graalvm/understanding-class-initialization-in-graalvm-native-image-generation-d765b7e4d6ed
