### ISSUE TITLE
No factory for objects of type DefaultGradleConnector available in ConnectorServiceRegistry

### ISSUE THREAD

**Issue by mgroth0** [oracle/graal#8760]
I hit an error when I try to execute a program with the Gradle Tooling Api:

```
org.gradle.internal.service.UnknownServiceException: No factory for objects of type DefaultGradleConnector available in ConnectorServiceRegistry
```

I am new to Graal, just tried it for the first time today. Therefore, it seems possible that there could be some configuration quick-fix I am missing. However, I did try a few things and nothing seemed to work.

Here is the reproducer: https://github.com/mgroth0/graal-8760
Run `nativeRun` in the reproducer project to see the error.

**Comment by selhagani** [comment]
Hi @mgroth0, Thank you for reaching out to us.

Could you please share with us the GraalVM version you're using, your OS version, and your system architecture?

**Comment by selhagani** [comment]
Hi @mgroth0,

Thank you for providing that information.

Have you had a chance to collect the metadata using the tracing agent? If not, please refer to this [documentation link](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/).

Additionally, it's advisable to have the JAR file in order to build the project as a Java application, which would help us ensure that this is indeed a GraalVM issue.

Thank you for your cooperation. Let me know if you need further assistance!
