### ISSUE TITLE
Make language IDs case-insensitive and allow variations?

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#879]
I'm not sure why language IDs are currently case-sensitive, but I think making them case-insensitive would increase usability (`Polyglot.eval("python", "1")` vs. `Polyglot.eval("Python", "1")`). Moreover, I believe it also makes sense to allow multiple IDs per language implementation. Currently, for example, GraalJS uses `js` as its language ID, but I'm sometimes tempted to write `javascript` when using the polyglot APIs. This, of course, also increases the problem of name clashes, but I'm sure there is already some sort of check in place to avoid duplicate language IDs.

Related: https://github.com/oracle/fastr/issues/45

**Comment by fniephaus** [comment]
According to https://github.com/oracle/fastr/issues/45#issuecomment-468313975, the FastR team is continuing to use an uppercase `R` as language ID. It'd still be great to make the language ID case-insensitive when using the interop API. What are your thoughts on this, @chumer?

**Comment by chumer** [comment]
I consider the language id a symbol, that is just dynamic because the API is language agnostic. Symbols should not be case-insensitive unless there is a good reason imo. If you want to make your language polyglot api less strict, you are free to do so, I would however not recommend it.

Note that we make suggestions if the language id is slightly off. I think that is good enough.
