### ISSUE TITLE
PolyglotList is not equal to an equal list

### ISSUE THREAD

**Issue by andreho** [oracle/graal#881]
Hello, 
I believe there is a problem with the "equals" method in the PolyglotList class. The method seems to behave differently from the original Java lists implementations like Vector or ArrayList. 

To reproduce the issue, just try to compare a non-empty instance of "com.oracle.truffle.polyglot.PolyglotList" via the "equals" method with a similar ArrayList or Arrays.asList(...) object. 

Kind Regards, 
Andre.

System: VBox + Linux x64 + GraalVM RC10

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20798.

**Comment by chumer** [comment]
Yes we deliberately don't do structural comparison for the list views.  The reason is that the list view might be mapped to recursive data structures. We had the choice between stack overflow errors in equals, or not doing the structural comparison. We decided against structural comparison. 

If you need structural comparison, you can write a helper method that does it.

Note that, while we don't use structural comparison, if you compare the same instance of a list with equals it is going to be equals.
