### ISSUE TITLE
no error message while having Exception.

### ISSUE THREAD

**Issue by imgoby** [oracle/graal#8849]
Applications compiled using GraalVM, after running, do not trigger certain processes that should have been triggered because there are no business logs. There is also no error message. There may be an abnormality somewhere, but the console or log file cannot see any abnormal information. How to open logs and display error messages?

**Comment by fniephaus** [comment]
Thanks for raising this, @imgoby. Unfortunately, the information that you have provided is not sufficient for us to determine what is going wrong in your application. We recently ran into [a similar issue](https://github.com/oracle/graalvm-reachability-metadata/issues/454), so I'm wonder: is you application using logback and reachability metadata? If not, can you provide us with a reproducer? Otherwise, you could build the app with `-g` to generate debug info and then [debug the application using gdb](https://www.graalvm.org/latest/reference-manual/native-image/guides/debug-native-image-process/).

**Comment by imgoby** [comment]
Thank you.I try it.

**Comment by oubidar-Abderrahim** [comment]
Hi, any updates?

**Comment by oubidar-Abderrahim** [comment]
We are closing this ticket as there isn't enough information to work with. If you still face the issue please create a new ticket and provide all necessary information by following the Github template
