### ISSUE TITLE
MS Windows

### ISSUE THREAD

**Issue by tsatatwer** [oracle/graal#886]
It is possible to download MS Windows builds.

**Comment by shelajev** [comment]
You can obtain a preview build for Windows that has the Graal compiler enabled from the [OTN page](https://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html), but it doesn't include the languages or the native image support. 

When we have working Windows builds, one would be able to download them from the normal download locations.

**Comment by shelajev** [comment]
I'm sorry that you feel this is a diverting answer, it wasn't my intention and I'm sorry we misunderstood each other. Please note that your original issue description said nothing about estimated times or support, which are two different questions as well. 

Windows is not excluded, it's a technical problem, there are currently no working builds of GraalVM yet where all necessary components would work on Windows. For example the native-image utility doesn't work on Windows yet, and it's a part of the GraalVM download, so currently there are no full builds for Windows. We're actively working on making native images support Windows, but there's no estimate for when it's going to be done. Perhaps it'll take months rather than years or days, if this helps.

I understand your frustration, and we know there are many developers working on Windows, so when we have the builds that actually work there, we'll provide them. 

Which GraalVM use-cases on Windows are you looking forward to the most?

PS. I'll reopen this issue so anyone who needs Windows support could provide information what are they looking for, and have a place for a discussion.

**Comment by texasbruce** [comment]
Thanks for reopening. To me I personally would like to see native image running on Windows, to avoid bundling whole JRE with small GUI apps.

I understand there are Windows servers but this is just my use case.

**Comment by tsatatwer** [comment]
Thank you for reopen this issue indeed , and I my self as a java developer would like to use native image feature and will use it  in my software and I know many developers  as well sharing me the same view and as you mention we have really big frustration and disappointing that there are builds for other OS and NOT windows so I joint my voice to @texasbruce and ask the same question :
May I know what's the obstacles of Windows builds right now?

**Comment by shelajev** [comment]
The native image utility currently doesn't work on Windows. It fails to produce a working Windows executable. One reason for that is that the executable is native, which means it's platform specific, which explains how it can work on Linux and not work on Windows. The implementation of the Windows system calls is not complete yet. 

Having a build where some components don't work is not ideal, that's why there's a preview build available on the OTN which have the components that work: the Graal compiler, but not the others.

**Comment by tsatatwer** [comment]
Thanks for the answer , as developers we know that native image is OS specific , one of your colleges estimate windows build will be available at the end of 2018 or beginning of 2019 check this  **#663** .

**Comment by neomatrix369** [comment]
I think it was a clear response, the OTN page also mentions on the same grounds @tsatatwer 
You can already start playing with build scripts at https://github.com/neomatrix369/awesome-graal/ for Linux and MacOS, and help with the Windows version

**Comment by tsatatwer** [comment]
Hi ,

I still waiting an answer please .

**Comment by tsatatwer** [comment]
Hi @shelajev ,

can be closed.
