### ISSUE TITLE
Error in installation Graal from SDK

### ISSUE THREAD

**Issue by Medharoun** [oracle/graal#889]
when i run this command :

"sdk install java 1.0.0-rc8-graal"

i found this error:

Stop! java 1.0.0-rc8-graal is not available. Possible causes:
 * 1.0.0-rc8-graal is an invalid version
 * java binaries are incompatible with Linux64
 * java has not been released yet

**Comment by SergejIsbrecht** [comment]
Hi @Medharoun,

I don't think that SDK is supported by Graal. Please have a look this which versions SDK has:

`sergej@L530:~/GitHub/flamescope$ sdk list java
================================================================================
Available Java Versions
================================================================================
     12.ea.20-open                                                              
     11.0.1-zulu                                                                
     11.0.1-open                                                                
     10.0.2-zulu                                                                
     10.0.2-open                                                                
     9.0.7-zulu                                                                 
     9.0.4-open                                                                 
     8.0.192-zulu                                                               
     8.0.191-oracle                                                             
     7.0.201-zulu                                                               
     6.0.119-zulu                                                               
     1.0.0-rc-10-grl                                                            
     1.0.0-rc-9-grl                                                             
     1.0.0-rc-8-grl`

In order to install the Graal builds, you may use:
`sergej@L530:~/GitHub/flamescope$ sdk install java 1.0.0-rc-10-grl

Downloading: java 1.0.0-rc-10-grl
`

**Comment by Medharoun** [comment]
thanks "sdk install java 1.0.0-rc-10-grl" that's works
