### ISSUE TITLE
[native-image] allow entrypoint to be set when building non-executable

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#940]
Currently, the mainEntryPoint is only set when the target goal is an executable:
https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java#L225

Hence, when building a library based on a Java class with a main method, this method is not used as the mainEntryPoint. 
However, in some cases you want to create a library (or even use the objectfile) and do additional processing on it, but still leverage the fact that the main class has a main method.

Removing the` if (k.executable)` condition achieves this, and doesn't break other things, hence I would recommend that.

**Comment by olpaw** [comment]
@johanvos do you have something like executable shared objects in mind.
E.g. like what the glibc shared object provides?
```
> /lib/libc.so.6 
GNU C Library (GNU libc) stable release version 2.28.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 8.2.1 20181105 (Red Hat 8.2.1-5).
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

**Comment by johanvos** [comment]
No, the shared lib itself does not have to be executable.
An executable still needs to call a function in the shared lib to launch the Java application. But in case the underlying Java project has a main class with a main method, it would be nice if the executable can call that main function  (e.g. JavaWrapper_Main_main), where Main is the classname of the main function. 

The reason I can't use an executable as target format is that there are additional libraries that need to be linked in, and additional processing is needed (e.g. specific signing constraints).

**Comment by olpaw** [comment]
We have added https://github.com/oracle/graal/commit/175738c97f96974ba44251e913a597aa64a7d3c2

With this change users can build shared libraries as if they were building an executable.
E.g. the following is now possible:
```
mx native-image --shared -jar ~/OLabs/git/HelloMaven/target/app-1.0-SNAPSHOT.jar
```
This builds `app-1.0-SNAPSHOT.so` where there is a symbol `run_main`. Additionally the generated header files contain in `app-1.0-SNAPSHOT.h`:
```
int run_main(int paramArgc, char** paramArgv);
```
and in `app-1.0-SNAPSHOT_dynamic.h`:
```
typedef int (*run_main_fn_t)(int paramArgc, char** paramArgv);
```
so that users can programmatically build shared objects that all callable via the same well defined symbol. There is now also a gate check that builds such a shared object and calls its `run_main` function. See: https://github.com/oracle/graal/blob/175738c97f96974ba44251e913a597aa64a7d3c2/substratevm/mx.substratevm/mx_substratevm.py#L819
