### ISSUE TITLE
[GR-59102] Vector API (JEP338) Implementation is very slow on M1 Mac

### ISSUE THREAD

**Issue by RainerXE** [oracle/graal#9889]
- Using latest EA build (24EA16) on M1 Mac (ARM) for a JEP338 benchmark in Scala, s. article:
https://alexklibisz.com/2023/02/25/accelerating-vector-operations-jvm-jdk-incubator-vector-project-panama#complete-benchmark-results

My Benchmark results show that the Jep338 has much less throughput than the baseline and Fma.
This is also consistent with bad performance of Llama3.java on the same machine.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1.  git clone --depth 1 https://github.com/RainerXE/graalvm-performance-m1/tree/main/jdk-incubator-vector-optimizations
2. Install SBT, e.g., $ brew install sbt
3. Run the benchmarks via sbt-jmh: $ sbt "Jmh/run"

**Describe GraalVM and your environment:**
 - GraalVM version: 24 EA 16 ( VM version: JDK 24, Java HotSpot(TM) 64-Bit Server VM, 24+18-jvmci-b01
[info] # VM invoker: ... 24.ea.16-graal/bin/java) 
 - JDK major version: 24
 - OS: MacOS Sonoma
 - Architecture: ARM64 (M1 Mac)

 PASTE YOUR LOG/STACK TRACE HERE -> Benchmark results

[info] Result "com.alexklibisz.BenchPowVsMul.pow":
[info]   35153161,611 ±(99.9%) 900061,893 ops/s [Average]
[info]   (min, avg, max) = (34748015,788, 35153161,611, 35621615,008), stdev = 320970,742
[info]   CI (99.9%): [34253099,717, 36053223,504] (assumes normal distribution)
[info] # Run complete. Total time: 00:16:39
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                              Mode  Cnt           Score          Error  Units
[info] Bench.cosineSimilarityBaseline        thrpt    6   759845073,900 ± 34738455,913  ops/s
[info] Bench.cosineSimilarityFma             thrpt    6   890103808,144 ± 21411663,847  ops/s
[info] Bench.cosineSimilarityJep338FullMask  thrpt    6       99647,476 ±     4594,938  ops/s
[info] Bench.cosineSimilarityJep338TailLoop  thrpt    6     1733057,641 ±    81159,975  ops/s
[info] Bench.cosineSimilarityJep338TailMask  thrpt    6       95086,299 ±     3321,613  ops/s
[info] Bench.dotProductBaseline              thrpt    6   888075119,912 ± 12447115,837  ops/s
[info] Bench.dotProductFma                   thrpt    6   884682203,632 ± 57271028,372  ops/s
[info] Bench.dotProductJep338FullMask        thrpt    6      190269,566 ±    10746,849  ops/s
[info] Bench.dotProductJep338TailLoop        thrpt    6     3743761,628 ±   188224,743  ops/s
[info] Bench.dotProductJep338TailMask        thrpt    6      173911,463 ±     5692,762  ops/s
[info] Bench.l1DistanceBaseline              thrpt    6   883658529,476 ± 28212327,558  ops/s
[info] Bench.l1DistanceFma                   thrpt    6   886794233,555 ± 11035592,960  ops/s
[info] Bench.l1DistanceJep338FullMask        thrpt    6      153015,498 ±     9479,264  ops/s
[info] Bench.l1DistanceJep338TailLoop        thrpt    6     3632973,527 ±   116257,839  ops/s
[info] Bench.l1DistanceJep338TailMask        thrpt    6      143363,748 ±     7699,548  ops/s
[info] Bench.l2DistanceBaseline              thrpt    6   872175493,083 ± 67634584,975  ops/s
[info] Bench.l2DistanceFma                   thrpt    6   869402096,801 ± 41012251,412  ops/s
[info] Bench.l2DistanceJep338FullMask        thrpt    6      141876,642 ±    18089,059  ops/s
[info] Bench.l2DistanceJep338TailLoop        thrpt    6     3611642,024 ±   110319,893  ops/s
[info] Bench.l2DistanceJep338TailMask        thrpt    6      132222,261 ±    11901,056  ops/s
[info] BenchPowVsMul.mul                     thrpt    6  1466849451,660 ± 24136302,625  ops/s
[info] BenchPowVsMul.pow                     thrpt    6    35153161,611 ±   900061,893  ops/s
[success] Total time: 1006 s (16:46), completed 15 Oct 2024, 21:39:24

**Comment by selhagani** [comment]
Hi @RainerXE, 

Thank you for reaching out to us! We will look into this shortly and I'll make sure to keep you updated

**Comment by selhagani** [comment]
Hi @RainerXE, 

I was able to reproduce the issue you reported. We will take a closer look into this and I'll make sure to keep you updated.

**Comment by RainerXE** [comment]
Thank you very much. I also tried the same on the GraalVM 23, Oracle Java 23 and 24EA and all hat the same slowness, so there might be a problem in the Vector API implementation/the JIT not optimizing it …

**Comment by selhagani** [comment]
Thank you for the information! In that case this isn't really a GraalVM issue if you noticed the same slowness even when using Oracle Java 23. I suggest you try to reach out to openJDK about this.
Once again thank you for having reached out to us!

**Comment by RainerXE** [comment]
Hi, my understanding is that is that the Vector API implementation is dependent on the JIT compiler. As GraalVM provide another compiler I think it might be worth for you to still take a look. Also, the Graal Compiler seems to get better when warmed up (by around 20%) while the C2 does not …

**Comment by gergo-** [comment]
Hi @RainerXE,

> This is also consistent with bad performance of Llama3.java on the same machine.

This is a bit surprising. Could you provide a bit more details of what version of Llama3.java you are running and exactly how? I would want to fix this.

Some notes on the other results that surprised you:

```
[info] Bench.dotProductJep338FullMask thrpt 6  190269,566 ± 10746,849 ops/s
[info] Bench.dotProductJep338TailLoop thrpt 6 3743761,628 ± 188224,743 ops/s
[info] Bench.dotProductJep338TailMask thrpt 6  173911,463 ± 5692,762 ops/s
```
This kind of code that uses general masking (and in particular, masked loads from memory) can only be supported by compilers in a meaningful way on architectures that have the appropriate masked load instructions. That means x86 CPUs with the AVX-512 vector instruction set. Future ARM CPUs with SVE instructions should also have this capability, I think. But as I understand it, the M1 does not have SVE. On AVX-512 you might see a difference between Oracle Java and Oracle GraalVM because GraalVM doesn't currently generate masked loads, but I believe Oracle Java's C2 compiler does. This will change in the future.

```
[info] BenchPowVsMul.mul thrpt 6 1466849451,660 ± 24136302,625 ops/s
[info] BenchPowVsMul.pow thrpt 6   35153161,611 ± 900061,893 ops/s
```
There are two issues here: First, you might expect `pow(2)` to be optimized by the compiler into an efficient multiplication. This might work, if the compiler can guarantee that it has the exact same semantics (including for infinities etc.). We would need to check this. Second, `pow` itself is slow. For vector versions of transcendental functions like `pow`, `sin`, `cos`, `tan`, etc., the JVM can call out to a library that provides efficient implementations of these operations. However, as I understand it, the JVM only ships with this library for x86 targets. So on ARM you see no benefit from this, and instead the compiler must fall back to slower non-vector code. On x86 you might see a difference between Oracle Java and Oracle GraalVM because GraalVM doesn't currently call out to this helper library. This too will change in the future.

**Comment by RainerXE** [comment]
Hi,

-  I'm using this Llama3 : https://github.com/mukel/llama3.java 
- I also flagged it there: https://github.com/mukel/llama3.java/issues/7
Hope this helps. 

I'm at the moment to also test all of this on osx/x86... 

Rainer
